//////////////////////////////////////////////////////////////////////////////////
// Config Automatically Generated by ALiVE ORBAT Creator
// Generated with Arma 3 version 204.147719 on Stable branch
// Generated with ALiVE version 1.14.1.2105061
//////////////////////////////////////////////////////////////////////////////////

class CfgFactionClasses {
    class B_UNMar_OPTRE {
        displayName = "UNSCDF [ALiVE]";
        side = 1;
        flag = "\OPTRE_Core\Data\flag_UNSC_ca.paa";
        icon = "\OPTRE_Core\Data\flag_UNSC_ca.paa";
        priority = 0;
    };
};

class CfgGroups {
    class WEST {

        class B_UNMar_OPTRE {
            name = "UNSCDF [ALiVE]";

            class Infantry {
                name = "Infantry";

                class b_bunmaroptre_infantry_sentry {
                    name = "Sentry";
                    side = 1;
                    faction = "B_UNMar_OPTRE";
                    icon = "\A3\ui_f\data\map\markers\nato\b_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 1;
                        vehicle = "B_UNMar_Rifleman_ALiVE_OPTRE_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_UNMar_Grenadier_ALiVE_OPTRE_01";
                    };
                };

                class b_bunmaroptre_infantry_fireteam {
                    name = "Fireteam";
                    side = 1;
                    faction = "B_UNMar_OPTRE";
                    icon = "\A3\ui_f\data\map\markers\nato\b_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 1;
                        vehicle = "B_UNMar_Team_Leader_ALiVE_OPTRE_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_UNMar_Grenadier_ALiVE_OPTRE_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_UNMar_Rifleman_AT_ALiVE_OPTRE_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_UNMar_Autorifleman_ALiVE_OPTRE_01";
                    };
                };

                class b_bunmaroptre_infantry_rifle_squad {
                    name = "Rifle Squad";
                    side = 1;
                    faction = "B_UNMar_OPTRE";
                    icon = "\A3\ui_f\data\map\markers\nato\b_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 1;
                        vehicle = "B_UNMar_Squad_Leader_ALiVE_OPTRE_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_UNMar_Team_Leader_ALiVE_OPTRE_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_UNMar_Team_Leader_ALiVE_OPTRE_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_UNMar_Rifleman_ALiVE_OPTRE_01";
                    };
                    class Unit4 {
                        position[] = {-10,-10,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_UNMar_Rifleman_ALiVE_OPTRE_01";
                    };
                    class Unit5 {
                        position[] = {15,-15,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_UNMar_Grenadier_ALiVE_OPTRE_01";
                    };
                    class Unit6 {
                        position[] = {-15,-15,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_UNMar_Grenadier_ALiVE_OPTRE_01";
                    };
                    class Unit7 {
                        position[] = {20,-20,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_UNMar_Medic_ALiVE_OPTRE_01";
                    };
                    class Unit8 {
                        position[] = {-20,-20,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_UNMar_RTO_ALiVE_OPTRE_01";
                    };
                };

                class b_bunmaroptre_infantry_weapons_squad {
                    name = "Weapons Squad";
                    side = 1;
                    faction = "B_UNMar_OPTRE";
                    icon = "\A3\ui_f\data\map\markers\nato\b_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 1;
                        vehicle = "B_UNMar_Squad_Leader_ALiVE_OPTRE_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_UNMar_Team_Leader_ALiVE_OPTRE_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_UNMar_Team_Leader_ALiVE_OPTRE_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_UNMar_Rifleman_AT_ALiVE_OPTRE_01";
                    };
                    class Unit4 {
                        position[] = {-10,-10,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_UNMar_Rifleman_AT_ALiVE_OPTRE_01";
                    };
                    class Unit5 {
                        position[] = {15,-15,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_UNMar_Rifleman_AA_ALiVE_OPTRE_01";
                    };
                    class Unit6 {
                        position[] = {-15,-15,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_UNMar_Rifleman_AA_ALiVE_OPTRE_01";
                    };
                    class Unit7 {
                        position[] = {20,-20,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_UNMar_Autorifleman_ALiVE_OPTRE_01";
                    };
                    class Unit8 {
                        position[] = {-20,-20,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_UNMar_Autorifleman_ALiVE_OPTRE_01";
                    };
                    class Unit9 {
                        position[] = {25,-25,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_UNMar_RTO_ALiVE_OPTRE_01";
                    };
                };

            };

            class SpecOps {
                name = "Special Forces";

                class b_bunmaroptre_specops_sniper_team {
                    name = "Sniper Team";
                    side = 1;
                    faction = "B_UNMar_OPTRE";
                    icon = "\A3\ui_f\data\map\markers\nato\b_recon.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 1;
                        vehicle = "B_UNMar_Sniper_ALiVE_OPTRE_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_UNMar_Marksman_ALiVE_OPTRE_01";
                    };
                };

                class b_bunmaroptre_specops_fo_team {
                    name = "FO Team";
                    side = 1;
                    faction = "B_UNMar_OPTRE";
                    icon = "\A3\ui_f\data\map\markers\nato\b_recon.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 1;
                        vehicle = "B_UNMar_Marksman_ALiVE_OPTRE_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_UNMar_RTO_ALiVE_OPTRE_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_UNMar_Marksman_ALiVE_OPTRE_01";
                    };
                };

                class b_bunmaroptre_specops_demolitions_team {
                    name = "Demolitions Team";
                    side = 1;
                    faction = "B_UNMar_OPTRE";
                    icon = "\A3\ui_f\data\map\markers\nato\b_recon.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 1;
                        vehicle = "B_BUNMarOPTRE_ODST_Rifleman_ALiVE_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_BUNMarOPTRE_ODST_Corpsman_ALiVE_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_BUNMarOPTRE_ODST_Demolitions_ALiVE_02";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_BUNMarOPTRE_ODST_Demolitions_ALiVE_02";
                    };
                };

                class b_bunmaroptre_specops_strike_team {
                    name = "Strike Team";
                    side = 1;
                    faction = "B_UNMar_OPTRE";
                    icon = "\A3\ui_f\data\map\markers\nato\b_recon.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 1;
                        vehicle = "B_BUNMarOPTRE_ODST_Rifleman_ALiVE_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_BUNMarOPTRE_ODST_Corpsman_ALiVE_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_BUNMarOPTRE_ODST_Rifleman_ALiVE_01";
                    };
                };

            };

            class Motorized {
                name = "Motorized Infantry";

                class b_bunmaroptre_motorized_light_hog_convoy {
                    name = "Light Hog Convoy";
                    side = 1;
                    faction = "B_UNMar_OPTRE";
                    icon = "\A3\ui_f\data\map\markers\nato\b_motor_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 1;
                        vehicle = "B_BUNMarOPTRE_M12_FAV_Army_ALiVE_01";
                    };
                    class Unit1 {
                        position[] = {6,-11,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_BUNMarOPTRE_M12_LRV_MG_Army_ALiVE_01";
                    };
                };

                class b_bunmaroptre_motorized_heavy_hog_convoy {
                    name = "Heavy Hog Convoy";
                    side = 1;
                    faction = "B_UNMar_OPTRE";
                    icon = "\A3\ui_f\data\map\markers\nato\b_motor_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 1;
                        vehicle = "B_BUNMarOPTRE_M12_LRV_MG_Army_ALiVE_01";
                    };
                    class Unit1 {
                        position[] = {7,-11,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_BUNMarOPTRE_M813_TT_Army_ALiVE_01";
                    };
                    class Unit2 {
                        position[] = {-7,-11,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_BUNMarOPTRE_M12G1_LRV_Gauss_Army_ALiVE_01";
                    };
                };

                class b_bunmaroptre_motorized_aa_convoy {
                    name = "AA Convoy";
                    side = 1;
                    faction = "B_UNMar_OPTRE";
                    icon = "\A3\ui_f\data\map\markers\nato\b_motor_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 1;
                        vehicle = "B_BUNMarOPTRE_M12_LRV_MG_Army_ALiVE_01";
                    };
                    class Unit1 {
                        position[] = {6,-11,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_BUNMarOPTRE_M12R_AA_Army_ALiVE_01";
                    };
                };

                class b_bunmaroptre_motorized_troop_convoy {
                    name = "Troop Convoy";
                    side = 1;
                    faction = "B_UNMar_OPTRE";
                    icon = "\A3\ui_f\data\map\markers\nato\b_motor_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 1;
                        vehicle = "B_BUNMarOPTRE_M12_LRV_MG_Army_ALiVE_01";
                    };
                    class Unit1 {
                        position[] = {7,-11,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_BUNMarOPTRE_M813_TT_Army_ALiVE_01";
                    };
                    class Unit2 {
                        position[] = {-7,-11,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_BUNMarOPTRE_M813_TT_Army_ALiVE_01";
                    };
                };

            };

            class Motorized_MTP {
                name = "Motorized Infantry (MTP)";

            };

            class Support {
                name = "Support Infantry";

            };

            class Mechanized {
                name = "Mechanized Infantry";

                class b_bunmaroptre_mechanized_light_mechanized_convoy {
                    name = "Light Mechanized Convoy";
                    side = 1;
                    faction = "B_UNMar_OPTRE";
                    icon = "\A3\ui_f\data\map\markers\nato\b_mech_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 1;
                        vehicle = "B_BUNMarOPTRE_AFV_102_Hound_ALiVE_01";
                    };
                    class Unit1 {
                        position[] = {9,-14,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_BUNMarOPTRE_MGS_32_Timberwolf_ALiVE_01";
                    };
                };

                class b_bunmaroptre_mechanized_heavy_mechanized_convoy {
                    name = "Heavy Mechanized Convoy";
                    side = 1;
                    faction = "B_UNMar_OPTRE";
                    icon = "\A3\ui_f\data\map\markers\nato\b_mech_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 1;
                        vehicle = "B_BUNMarOPTRE_MGS_32_Timberwolf_ALiVE_01";
                    };
                    class Unit1 {
                        position[] = {9,-15,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_BUNMarOPTRE_AFV_102_Hound_ALiVE_01";
                    };
                    class Unit2 {
                        position[] = {-9,-15,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_BUNMarOPTRE_AFV_102_Hound_ALiVE_01";
                    };
                    class Unit3 {
                        position[] = {18,-23,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_BUNMarOPTRE_MGS_32_Timberwolf_ALiVE_01";
                    };
                };

            };

            class Armored {
                name = "Armor";

                class b_bunmaroptre_armored_light_armored_convoy {
                    name = "Light Armored Convoy";
                    side = 1;
                    faction = "B_UNMar_OPTRE";
                    icon = "\A3\ui_f\data\map\markers\nato\b_armor.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 1;
                        vehicle = "B_BUNMarOPTRE_M808_Scorpion_MBT_Army_ALiVE_01";
                    };
                };

                class b_bunmaroptre_armored_heavy_armored_convoy {
                    name = "Heavy Armored Convoy";
                    side = 1;
                    faction = "B_UNMar_OPTRE";
                    icon = "\A3\ui_f\data\map\markers\nato\b_armor.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 1;
                        vehicle = "B_BUNMarOPTRE_M808_Scorpion_MBT_Army_ALiVE_01";
                    };
                    class Unit1 {
                        position[] = {14,-16,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_BUNMarOPTRE_M808_Scorpion_MBT_Army_ALiVE_01";
                    };
                };

            };

            class Artillery {
                name = "Artillery";

            };

            class Naval {
                name = "Naval";

            };

            class Air {
                name = "Air";

                class b_bunmaroptre_air_light_rotary_cas {
                    name = "Light Rotary CAS";
                    side = 1;
                    faction = "B_UNMar_OPTRE";
                    icon = "\A3\ui_f\data\map\markers\nato\b_air.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 1;
                        vehicle = "B_BUNMarOPTRE_UH_144A_Falcon_Army_ALiVE_01";
                    };
                };

                class b_bunmaroptre_air_heavy_rotary_cas {
                    name = "Heavy Rotary CAS";
                    side = 1;
                    faction = "B_UNMar_OPTRE";
                    icon = "\A3\ui_f\data\map\markers\nato\b_air.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 1;
                        vehicle = "B_BUNMarOPTRE_D77_TC_AV_Pelican_Army_ALiVE_01";
                    };
                };

                class b_bunmaroptre_air_light_rotary_cap {
                    name = "Light Rotary CAP";
                    side = 1;
                    faction = "B_UNMar_OPTRE";
                    icon = "\A3\ui_f\data\map\markers\nato\b_air.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 1;
                        vehicle = "B_BUNMarOPTRE_AV_14_Hornet_Army_ALiVE_01";
                    };
                };

                class b_bunmaroptre_air_heavy_rotary_cap {
                    name = "Heavy Rotary CAP";
                    side = 1;
                    faction = "B_UNMar_OPTRE";
                    icon = "\A3\ui_f\data\map\markers\nato\b_air.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 1;
                        vehicle = "B_BUNMarOPTRE_AV_14_Hornet_Army_ALiVE_01";
                    };
                    class Unit1 {
                        position[] = {11,-14,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_BUNMarOPTRE_AV_14_Hornet_Army_ALiVE_01";
                    };
                };

            };


        };

    };
};


class CBA_Extended_EventHandlers_base;

class CfgVehicles {

    class LM_OPCAN_UNSCA_Officer_MIX;
    class LM_OPCAN_UNSCA_Officer_MIX_OCimport_01 : LM_OPCAN_UNSCA_Officer_MIX { scope = 0; class EventHandlers; };
    class LM_OPCAN_UNSCA_Officer_MIX_OCimport_02 : LM_OPCAN_UNSCA_Officer_MIX_OCimport_01 { class EventHandlers; };

    class LM_OPCAN_UNSCA_SL_MIX;
    class LM_OPCAN_UNSCA_SL_MIX_OCimport_01 : LM_OPCAN_UNSCA_SL_MIX { scope = 0; class EventHandlers; };
    class LM_OPCAN_UNSCA_SL_MIX_OCimport_02 : LM_OPCAN_UNSCA_SL_MIX_OCimport_01 { class EventHandlers; };

    class LM_OPCAN_UNSCA_TL_MIX;
    class LM_OPCAN_UNSCA_TL_MIX_OCimport_01 : LM_OPCAN_UNSCA_TL_MIX { scope = 0; class EventHandlers; };
    class LM_OPCAN_UNSCA_TL_MIX_OCimport_02 : LM_OPCAN_UNSCA_TL_MIX_OCimport_01 { class EventHandlers; };

    class LM_OPCAN_UNSCA_Rifleman_MIX;
    class LM_OPCAN_UNSCA_Rifleman_MIX_OCimport_01 : LM_OPCAN_UNSCA_Rifleman_MIX { scope = 0; class EventHandlers; };
    class LM_OPCAN_UNSCA_Rifleman_MIX_OCimport_02 : LM_OPCAN_UNSCA_Rifleman_MIX_OCimport_01 { class EventHandlers; };

    class LM_OPCAN_UNSCA_GL_MIX;
    class LM_OPCAN_UNSCA_GL_MIX_OCimport_01 : LM_OPCAN_UNSCA_GL_MIX { scope = 0; class EventHandlers; };
    class LM_OPCAN_UNSCA_GL_MIX_OCimport_02 : LM_OPCAN_UNSCA_GL_MIX_OCimport_01 { class EventHandlers; };

    class LM_OPCAN_UNSCA_Medic_MIX;
    class LM_OPCAN_UNSCA_Medic_MIX_OCimport_01 : LM_OPCAN_UNSCA_Medic_MIX { scope = 0; class EventHandlers; };
    class LM_OPCAN_UNSCA_Medic_MIX_OCimport_02 : LM_OPCAN_UNSCA_Medic_MIX_OCimport_01 { class EventHandlers; };

    class LM_OPCAN_UNSCA_Marksman_MIX;
    class LM_OPCAN_UNSCA_Marksman_MIX_OCimport_01 : LM_OPCAN_UNSCA_Marksman_MIX { scope = 0; class EventHandlers; };
    class LM_OPCAN_UNSCA_Marksman_MIX_OCimport_02 : LM_OPCAN_UNSCA_Marksman_MIX_OCimport_01 { class EventHandlers; };

    class LM_OPCAN_UNSCA_RTO_MIX;
    class LM_OPCAN_UNSCA_RTO_MIX_OCimport_01 : LM_OPCAN_UNSCA_RTO_MIX { scope = 0; class EventHandlers; };
    class LM_OPCAN_UNSCA_RTO_MIX_OCimport_02 : LM_OPCAN_UNSCA_RTO_MIX_OCimport_01 { class EventHandlers; };

    class LM_OPCAN_UNSCA_Sniper_MIX;
    class LM_OPCAN_UNSCA_Sniper_MIX_OCimport_01 : LM_OPCAN_UNSCA_Sniper_MIX { scope = 0; class EventHandlers; };
    class LM_OPCAN_UNSCA_Sniper_MIX_OCimport_02 : LM_OPCAN_UNSCA_Sniper_MIX_OCimport_01 { class EventHandlers; };

    class LM_OPCAN_UNSCA_AutoRifleman_MIX;
    class LM_OPCAN_UNSCA_AutoRifleman_MIX_OCimport_01 : LM_OPCAN_UNSCA_AutoRifleman_MIX { scope = 0; class EventHandlers; };
    class LM_OPCAN_UNSCA_AutoRifleman_MIX_OCimport_02 : LM_OPCAN_UNSCA_AutoRifleman_MIX_OCimport_01 { class EventHandlers; };

    class LM_OPCAN_UNSCA_Crewman_MIX;
    class LM_OPCAN_UNSCA_Crewman_MIX_OCimport_01 : LM_OPCAN_UNSCA_Crewman_MIX { scope = 0; class EventHandlers; };
    class LM_OPCAN_UNSCA_Crewman_MIX_OCimport_02 : LM_OPCAN_UNSCA_Crewman_MIX_OCimport_01 { class EventHandlers; };

    class LM_OPCAN_UNSCA_Rifleman_AT_MIX;
    class LM_OPCAN_UNSCA_Rifleman_AT_MIX_OCimport_01 : LM_OPCAN_UNSCA_Rifleman_AT_MIX { scope = 0; class EventHandlers; };
    class LM_OPCAN_UNSCA_Rifleman_AT_MIX_OCimport_02 : LM_OPCAN_UNSCA_Rifleman_AT_MIX_OCimport_01 { class EventHandlers; };

    class LM_OPCAN_UNSCA_Engineer_MIX;
    class LM_OPCAN_UNSCA_Engineer_MIX_OCimport_01 : LM_OPCAN_UNSCA_Engineer_MIX { scope = 0; class EventHandlers; };
    class LM_OPCAN_UNSCA_Engineer_MIX_OCimport_02 : LM_OPCAN_UNSCA_Engineer_MIX_OCimport_01 { class EventHandlers; };

    class LM_OPCAN_AFV102_AR_MIX;
    class LM_OPCAN_AFV102_AR_MIX_OCimport_01 : LM_OPCAN_AFV102_AR_MIX { scope = 0; class EventHandlers; class Turrets; };
    class LM_OPCAN_AFV102_AR_MIX_OCimport_02 : LM_OPCAN_AFV102_AR_MIX_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class MainTurret;
        };
    };

    class LM_OPCAN_MGS_AR_MIX;
    class LM_OPCAN_MGS_AR_MIX_OCimport_01 : LM_OPCAN_MGS_AR_MIX { scope = 0; class EventHandlers; class Turrets; };
    class LM_OPCAN_MGS_AR_MIX_OCimport_02 : LM_OPCAN_MGS_AR_MIX_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class MainTurret;
        };
    };

    class LM_OPCAN_AV14_AR_MIX;
    class LM_OPCAN_AV14_AR_MIX_OCimport_01 : LM_OPCAN_AV14_AR_MIX { scope = 0; class EventHandlers; class Turrets; };
    class LM_OPCAN_AV14_AR_MIX_OCimport_02 : LM_OPCAN_AV14_AR_MIX_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class CargoTurret_01;
            class CargoTurret_02;
            class CargoTurret_03;
            class CargoTurret_04;
            class CargoTurret_05;
            class CargoTurret_06;
        };
    };

    class LM_OPCAN_UH144A_AR_MIX;
    class LM_OPCAN_UH144A_AR_MIX_OCimport_01 : LM_OPCAN_UH144A_AR_MIX { scope = 0; class EventHandlers; class Turrets; };
    class LM_OPCAN_UH144A_AR_MIX_OCimport_02 : LM_OPCAN_UH144A_AR_MIX_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class CargoTurret_01;
            class CargoTurret_02;
            class CargoTurret_03;
            class CargoTurret_04;
        };
    };

    class LM_OPCAN_UH144_AR_MIX;
    class LM_OPCAN_UH144_AR_MIX_OCimport_01 : LM_OPCAN_UH144_AR_MIX { scope = 0; class EventHandlers; class Turrets; };
    class LM_OPCAN_UH144_AR_MIX_OCimport_02 : LM_OPCAN_UH144_AR_MIX_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class CargoTurret_01;
            class CargoTurret_02;
            class CargoTurret_03;
            class CargoTurret_04;
        };
    };

    class LM_OPCAN_D77_U_AR_MIX;
    class LM_OPCAN_D77_U_AR_MIX_OCimport_01 : LM_OPCAN_D77_U_AR_MIX { scope = 0; class EventHandlers; class Turrets; };
    class LM_OPCAN_D77_U_AR_MIX_OCimport_02 : LM_OPCAN_D77_U_AR_MIX_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class CopilotTurret;
            class CargoTurret_01;
            class CargoTurret_02;
        };
    };

    class LM_OPCAN_D77_A_AR_MIX;
    class LM_OPCAN_D77_A_AR_MIX_OCimport_01 : LM_OPCAN_D77_A_AR_MIX { scope = 0; class EventHandlers; class Turrets; };
    class LM_OPCAN_D77_A_AR_MIX_OCimport_02 : LM_OPCAN_D77_A_AR_MIX_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class CopilotTurret;
            class CargoTurret_01;
            class CargoTurret_02;
        };
    };

    class LM_OPCAN_M808_AR_MIX;
    class LM_OPCAN_M808_AR_MIX_OCimport_01 : LM_OPCAN_M808_AR_MIX { scope = 0; class EventHandlers; class Turrets; };
    class LM_OPCAN_M808_AR_MIX_OCimport_02 : LM_OPCAN_M808_AR_MIX_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class MainTurret;
            class CargoTurret1;
            class CargoTurret2;
            class CargoTurret3;
            class CargoTurret4;
            class CargoTurret5;
            class CargoTurret6;
            class CargoTurret7;
            class CargoTurret8;
        };
    };

    class OPTRE_M12_FAV;
    class OPTRE_M12_FAV_OCimport_01 : OPTRE_M12_FAV { scope = 0; class EventHandlers; class Turrets; };
    class OPTRE_M12_FAV_OCimport_02 : OPTRE_M12_FAV_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class CargoGunner_1;
            class CargoTurret_02;
            class CargoTurret_03;
        };
    };

    class OPTRE_M12G1_LRV;
    class OPTRE_M12G1_LRV_OCimport_01 : OPTRE_M12G1_LRV { scope = 0; class EventHandlers; class Turrets; };
    class OPTRE_M12G1_LRV_OCimport_02 : OPTRE_M12G1_LRV_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class CargoGunner_1;
            class MainTurret;
        };
    };

    class OPTRE_M12_LRV;
    class OPTRE_M12_LRV_OCimport_01 : OPTRE_M12_LRV { scope = 0; class EventHandlers; class Turrets; };
    class OPTRE_M12_LRV_OCimport_02 : OPTRE_M12_LRV_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class CargoGunner_1;
            class MainTurret;
        };
    };

    class OPTRE_M813_TT;
    class OPTRE_M813_TT_OCimport_01 : OPTRE_M813_TT { scope = 0; class EventHandlers; class Turrets; };
    class OPTRE_M813_TT_OCimport_02 : OPTRE_M813_TT_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class CargoGunner_1;
            class CargoGunner_02;
            class CargoGunner_03;
            class CargoGunner_04;
            class CargoGunner_05;
            class CargoGunner_06;
            class CargoGunner_07;
        };
    };

    class OPTRE_M12R_AA;
    class OPTRE_M12R_AA_OCimport_01 : OPTRE_M12R_AA { scope = 0; class EventHandlers; class Turrets; };
    class OPTRE_M12R_AA_OCimport_02 : OPTRE_M12R_AA_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class CargoGunner_1;
            class MainTurret;
        };
    };

    class OPTRE_M914_RV;
    class OPTRE_M914_RV_OCimport_01 : OPTRE_M914_RV { scope = 0; class EventHandlers; class Turrets; };
    class OPTRE_M914_RV_OCimport_02 : OPTRE_M914_RV_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class CargoGunner_1;
        };
    };

    class OPTRE_UNSC_ODST_Soldier_DemolitionsExpert;
    class OPTRE_UNSC_ODST_Soldier_DemolitionsExpert_OCimport_01 : OPTRE_UNSC_ODST_Soldier_DemolitionsExpert { scope = 0; class EventHandlers; };
    class OPTRE_UNSC_ODST_Soldier_DemolitionsExpert_OCimport_02 : OPTRE_UNSC_ODST_Soldier_DemolitionsExpert_OCimport_01 { class EventHandlers; };

    class OPTRE_UNSC_ODST_Soldier_Paramedic;
    class OPTRE_UNSC_ODST_Soldier_Paramedic_OCimport_01 : OPTRE_UNSC_ODST_Soldier_Paramedic { scope = 0; class EventHandlers; };
    class OPTRE_UNSC_ODST_Soldier_Paramedic_OCimport_02 : OPTRE_UNSC_ODST_Soldier_Paramedic_OCimport_01 { class EventHandlers; };

    class OPTRE_UNSC_ODST_Soldier_Scout;
    class OPTRE_UNSC_ODST_Soldier_Scout_OCimport_01 : OPTRE_UNSC_ODST_Soldier_Scout { scope = 0; class EventHandlers; };
    class OPTRE_UNSC_ODST_Soldier_Scout_OCimport_02 : OPTRE_UNSC_ODST_Soldier_Scout_OCimport_01 { class EventHandlers; };


    class B_UNMar_Officer_ALiVE_OPTRE_01 : LM_OPCAN_UNSCA_Officer_MIX_OCimport_02 {
        author = "Capt. Houlston, L";
        scope = 2;
        scopeCurator = 2;
        displayName = "Officer [ALiVE]";
        side = 1;
        faction = "B_UNMar_OPTRE";

        identityTypes[] = {"Head_NATO","LanguageENG_F","NoGlassesÃ¯Â»Â¿"};

        uniformClass = "LM_OPCAN_UNSCA_WDL_3_UNI";

        linkedItems[] = {"LM_OPCAN_M52A_AR_Light_DES","OPTRE_UNSC_PatrolCap_Army","ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch","OPTRE_NVG"};
        respawnlinkedItems[] = {"LM_OPCAN_M52A_AR_Light_DES","OPTRE_UNSC_PatrolCap_Army","ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch","OPTRE_NVG"};

        weapons[] = {"OPTRE_MA37","OPTRE_M6G_SF"};
        respawnWeapons[] = {"OPTRE_MA37","OPTRE_M6G_SF"};

        magazines[] = {"OPTRE_32Rnd_762x51_Mag","OPTRE_8Rnd_127x40_Mag","OPTRE_32Rnd_762x51_Mag","OPTRE_8Rnd_127x40_Mag"};
        respawnMagazines[] = {"OPTRE_32Rnd_762x51_Mag","OPTRE_8Rnd_127x40_Mag","OPTRE_32Rnd_762x51_Mag","OPTRE_8Rnd_127x40_Mag"};

        ALiVE_orbatCreator_loadout[] = {{"OPTRE_MA37","","","",{"OPTRE_32Rnd_762x51_Mag",32},{},""},{},{"OPTRE_M6G_SF","","OPTRE_M6G_Flashlight","OPTRE_M6G_Scope",{"OPTRE_8Rnd_127x40_Mag",8},{},""},{"LM_OPCAN_UNSCA_WDL_3_UNI",{{"FirstAidKit",1},{"ACE_EarPlugs",1},{"OPTRE_32Rnd_762x51_Mag",9,32},{"OPTRE_8Rnd_127x40_Mag",2,8},{"Chemlight_green",2,1},{"HandGrenade",2,1}}},{"LM_OPCAN_M52A_AR_Light_DES",{}},{},"OPTRE_UNSC_PatrolCap_Army","",{},{"ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch","OPTRE_NVG"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class B_UNMar_Squad_Leader_ALiVE_OPTRE_01 : LM_OPCAN_UNSCA_SL_MIX_OCimport_02 {
        author = "Capt. Houlston, L";
        scope = 2;
        scopeCurator = 2;
        displayName = "Squad Leader [ALiVE]";
        side = 1;
        faction = "B_UNMar_OPTRE";

        identityTypes[] = {"Head_NATO","LanguageENG_F","NoGlassesÃ¯Â»Â¿"};

        uniformClass = "LM_OPCAN_UNSCA_WDL_1_UNI";

        linkedItems[] = {"LM_OPCAN_M52A_AR_TeamLead_DES","LM_OPCAN_CH252_AR_T3_C","ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch","LM_OPCAN_FLACAMUA2"};
        respawnlinkedItems[] = {"LM_OPCAN_M52A_AR_TeamLead_DES","LM_OPCAN_CH252_AR_T3_C","ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch","LM_OPCAN_FLACAMUA2"};

        weapons[] = {"OPTRE_MA37","OPTRE_M6G_SF"};
        respawnWeapons[] = {"OPTRE_MA37","OPTRE_M6G_SF"};

        magazines[] = {"OPTRE_32Rnd_762x51_Mag","OPTRE_8Rnd_127x40_Mag","OPTRE_32Rnd_762x51_Mag","OPTRE_8Rnd_127x40_Mag"};
        respawnMagazines[] = {"OPTRE_32Rnd_762x51_Mag","OPTRE_8Rnd_127x40_Mag","OPTRE_32Rnd_762x51_Mag","OPTRE_8Rnd_127x40_Mag"};

        backpack = "OPTRE_UNSC_Rucksack_Heavy";

        ALiVE_orbatCreator_loadout[] = {{"OPTRE_MA37","","","",{"OPTRE_32Rnd_762x51_Mag",32},{},""},{},{"OPTRE_M6G_SF","","OPTRE_M6G_Flashlight","OPTRE_M6G_Scope",{"OPTRE_8Rnd_127x40_Mag",8},{},""},{"LM_OPCAN_UNSCA_WDL_1_UNI",{{"FirstAidKit",1},{"ACE_EarPlugs",1},{"OPTRE_32Rnd_762x51_Mag",9,32},{"OPTRE_8Rnd_127x40_Mag",2,8},{"Chemlight_green",2,1},{"HandGrenade",2,1}}},{"LM_OPCAN_M52A_AR_TeamLead_DES",{}},{"OPTRE_UNSC_Rucksack_Heavy",{}},"LM_OPCAN_CH252_AR_T3_C","LM_OPCAN_Eyepiece",{},{"ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch","LM_OPCAN_FLACAMUA2"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class B_UNMar_Team_Leader_ALiVE_OPTRE_01 : LM_OPCAN_UNSCA_TL_MIX_OCimport_02 {
        author = "Capt. Houlston, L";
        scope = 2;
        scopeCurator = 2;
        displayName = "Team Leader [ALiVE]";
        side = 1;
        faction = "B_UNMar_OPTRE";

        identityTypes[] = {"Head_NATO","LanguageENG_F","NoGlassesÃ¯Â»Â¿"};

        uniformClass = "LM_OPCAN_UNSCA_WDL_3_UNI";

        linkedItems[] = {"LM_OPCAN_M52A_AR_TeamLead_DES","LM_OPCAN_CH252_AR_D_C","ItemMap","ItemRadio","ItemCompass","ItemWatch","LM_OPCAN_FLACAM"};
        respawnlinkedItems[] = {"LM_OPCAN_M52A_AR_TeamLead_DES","LM_OPCAN_CH252_AR_D_C","ItemMap","ItemRadio","ItemCompass","ItemWatch","LM_OPCAN_FLACAM"};

        weapons[] = {"OPTRE_MA37GL"};
        respawnWeapons[] = {"OPTRE_MA37GL"};

        magazines[] = {"OPTRE_32Rnd_762x51_Mag","1Rnd_HE_Grenade_shell","OPTRE_32Rnd_762x51_Mag","1Rnd_HE_Grenade_shell"};
        respawnMagazines[] = {"OPTRE_32Rnd_762x51_Mag","1Rnd_HE_Grenade_shell","OPTRE_32Rnd_762x51_Mag","1Rnd_HE_Grenade_shell"};

        backpack = "OPTRE_UNSC_Rucksack";

        ALiVE_orbatCreator_loadout[] = {{"OPTRE_MA37GL","","","",{"OPTRE_32Rnd_762x51_Mag",32},{"1Rnd_HE_Grenade_shell",1},""},{},{},{"LM_OPCAN_UNSCA_WDL_3_UNI",{{"FirstAidKit",1},{"ACE_EarPlugs",1},{"ACE_elasticBandage",10},{"ACE_packingBandage",10},{"ACE_quikclot",10},{"ACE_fieldDressing",10},{"ACE_Banana",2},{"ACE_bloodIV",1},{"ACE_DefusalKit",1},{"ACE_EntrenchingTool",1},{"ACE_Flashlight_MX991",1},{"ACE_MapTools",1},{"ACE_splint",10},{"Chemlight_green",2,1},{"HandGrenade",2,1}}},{"LM_OPCAN_M52A_AR_TeamLead_DES",{{"OPTRE_32Rnd_762x51_Mag",8,32}}},{"OPTRE_UNSC_Rucksack",{{"3Rnd_HE_Grenade_shell",10,3},{"ACE_40mm_Flare_white",5,1},{"ACE_40mm_Flare_ir",5,1},{"OPTRE_3Rnd_Smoke_Grenade_shell",5,3},{"OPTRE_1Rnd_SmokeRed_Grenade_shell",5,1},{"OPTRE_1Rnd_SmokeGreen_Grenade_shell",5,1},{"OPTRE_1Rnd_SmokeBlue_Grenade_shell",5,1}}},"LM_OPCAN_CH252_AR_D_C","LM_OPCAN_Eyepiece",{},{"ItemMap","","ItemRadio","ItemCompass","ItemWatch","LM_OPCAN_FLACAM"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class B_UNMar_Rifleman_ALiVE_OPTRE_01 : LM_OPCAN_UNSCA_Rifleman_MIX_OCimport_02 {
        author = "Capt. Houlston, L";
        scope = 2;
        scopeCurator = 2;
        displayName = "Rifleman [ALiVE]";
        side = 1;
        faction = "B_UNMar_OPTRE";

        identityTypes[] = {"Head_NATO","LanguageENG_F","NoGlassesÃ¯Â»Â¿"};

        uniformClass = "LM_OPCAN_UNSCA_WDL_2_UNI";

        linkedItems[] = {"LM_OPCAN_M52A_AR_Rifle_DES","LM_OPCAN_CH252_AR_T_C","ItemMap","ItemRadio","ItemCompass","ItemWatch","LM_OPCAN_COMM"};
        respawnlinkedItems[] = {"LM_OPCAN_M52A_AR_Rifle_DES","LM_OPCAN_CH252_AR_T_C","ItemMap","ItemRadio","ItemCompass","ItemWatch","LM_OPCAN_COMM"};

        weapons[] = {"OPTRE_MA37","OPTRE_M6G_SF"};
        respawnWeapons[] = {"OPTRE_MA37","OPTRE_M6G_SF"};

        magazines[] = {"OPTRE_32Rnd_762x51_Mag","OPTRE_8Rnd_127x40_Mag","OPTRE_32Rnd_762x51_Mag","OPTRE_8Rnd_127x40_Mag"};
        respawnMagazines[] = {"OPTRE_32Rnd_762x51_Mag","OPTRE_8Rnd_127x40_Mag","OPTRE_32Rnd_762x51_Mag","OPTRE_8Rnd_127x40_Mag"};

        ALiVE_orbatCreator_loadout[] = {{"OPTRE_MA37","","","",{"OPTRE_32Rnd_762x51_Mag",32},{},""},{},{"OPTRE_M6G_SF","","OPTRE_M6G_Flashlight","OPTRE_M6G_Scope",{"OPTRE_8Rnd_127x40_Mag",8},{},""},{"LM_OPCAN_UNSCA_WDL_2_UNI",{{"FirstAidKit",1},{"ACE_EarPlugs",1},{"OPTRE_32Rnd_762x51_Mag",9,32},{"OPTRE_8Rnd_127x40_Mag",2,8},{"Chemlight_green",2,1},{"HandGrenade",2,1}}},{"LM_OPCAN_M52A_AR_Rifle_DES",{}},{},"LM_OPCAN_CH252_AR_T_C","LM_OPCAN_Eyepiece",{},{"ItemMap","","ItemRadio","ItemCompass","ItemWatch","LM_OPCAN_COMM"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class B_UNMar_Grenadier_ALiVE_OPTRE_01 : LM_OPCAN_UNSCA_GL_MIX_OCimport_02 {
        author = "Capt. Houlston, L";
        scope = 2;
        scopeCurator = 2;
        displayName = "Grenadier [ALiVE]";
        side = 1;
        faction = "B_UNMar_OPTRE";

        identityTypes[] = {"Head_NATO","LanguageENG_F","NoGlassesÃ¯Â»Â¿"};

        uniformClass = "LM_OPCAN_UNSCA_WDL_4_UNI";

        linkedItems[] = {"LM_OPCAN_M52A_AR_Grenadier_DES","LM_OPCAN_CH252_AR_Y_C","ItemMap","ItemRadio","ItemCompass","ItemWatch","LM_OPCAN_CAM"};
        respawnlinkedItems[] = {"LM_OPCAN_M52A_AR_Grenadier_DES","LM_OPCAN_CH252_AR_Y_C","ItemMap","ItemRadio","ItemCompass","ItemWatch","LM_OPCAN_CAM"};

        weapons[] = {"OPTRE_MA37GL"};
        respawnWeapons[] = {"OPTRE_MA37GL"};

        magazines[] = {"OPTRE_32Rnd_762x51_Mag","1Rnd_HE_Grenade_shell","OPTRE_32Rnd_762x51_Mag","1Rnd_HE_Grenade_shell"};
        respawnMagazines[] = {"OPTRE_32Rnd_762x51_Mag","1Rnd_HE_Grenade_shell","OPTRE_32Rnd_762x51_Mag","1Rnd_HE_Grenade_shell"};

        backpack = "OPTRE_UNSC_Rucksack";

        ALiVE_orbatCreator_loadout[] = {{"OPTRE_MA37GL","","","",{"OPTRE_32Rnd_762x51_Mag",32},{"1Rnd_HE_Grenade_shell",1},""},{},{},{"LM_OPCAN_UNSCA_WDL_4_UNI",{{"FirstAidKit",1},{"ACE_EarPlugs",1},{"ACE_fieldDressing",10},{"ACE_elasticBandage",10},{"ACE_packingBandage",10},{"ACE_quikclot",10},{"ACE_bloodIV",1},{"ACE_MapTools",1},{"ACE_Flashlight_MX991",1},{"ACE_EntrenchingTool",1},{"ACE_splint",10},{"Chemlight_green",2,1},{"HandGrenade",2,1}}},{"LM_OPCAN_M52A_AR_Grenadier_DES",{{"OPTRE_32Rnd_762x51_Mag",9,32}}},{"OPTRE_UNSC_Rucksack",{{"1Rnd_HE_Grenade_shell",10,1},{"3Rnd_HE_Grenade_shell",3,3},{"ACE_40mm_Flare_white",4,1},{"OPTRE_3Rnd_Smoke_Grenade_shell",2,3},{"OPTRE_3Rnd_SmokeGreen_Grenade_shell",2,3},{"OPTRE_3Rnd_SmokeYellow_Grenade_shell",2,3},{"OPTRE_1Rnd_SmokeOrange_Grenade_shell",2,1},{"OPTRE_1Rnd_SmokeBlue_Grenade_shell",2,1}}},"LM_OPCAN_CH252_AR_Y_C","LM_OPCAN_Eyepiece",{},{"ItemMap","","ItemRadio","ItemCompass","ItemWatch","LM_OPCAN_CAM"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class B_UNMar_Medic_ALiVE_OPTRE_01 : LM_OPCAN_UNSCA_Medic_MIX_OCimport_02 {
        author = "Capt. Houlston, L";
        scope = 2;
        scopeCurator = 2;
        displayName = "Medic [ALiVE]";
        side = 1;
        faction = "B_UNMar_OPTRE";

        identityTypes[] = {"Head_NATO","LanguageENG_F","NoGlassesÃ¯Â»Â¿"};

        uniformClass = "LM_OPCAN_UNSCA_TRO_UNI";

        linkedItems[] = {"LM_OPCAN_M52A_AR_Rifle_DES","LM_OPCAN_CH252_AR_T_M_C","ItemMap","ItemRadio","ItemCompass","ItemWatch","LM_OPCAN_COMM"};
        respawnlinkedItems[] = {"LM_OPCAN_M52A_AR_Rifle_DES","LM_OPCAN_CH252_AR_T_M_C","ItemMap","ItemRadio","ItemCompass","ItemWatch","LM_OPCAN_COMM"};

        weapons[] = {"OPTRE_M7","OPTRE_M6G_SF"};
        respawnWeapons[] = {"OPTRE_M7","OPTRE_M6G_SF"};

        magazines[] = {"OPTRE_48Rnd_5x23mm_FMJ_Mag","OPTRE_8Rnd_127x40_Mag","OPTRE_48Rnd_5x23mm_FMJ_Mag","OPTRE_8Rnd_127x40_Mag"};
        respawnMagazines[] = {"OPTRE_48Rnd_5x23mm_FMJ_Mag","OPTRE_8Rnd_127x40_Mag","OPTRE_48Rnd_5x23mm_FMJ_Mag","OPTRE_8Rnd_127x40_Mag"};

        backpack = "OPTRE_UNSC_Rucksack_Medic_Filled";

        ALiVE_orbatCreator_loadout[] = {{"OPTRE_M7","","","",{"OPTRE_48Rnd_5x23mm_FMJ_Mag",48},{},""},{},{"OPTRE_M6G_SF","","OPTRE_M6G_Flashlight","OPTRE_M6G_Scope",{"OPTRE_8Rnd_127x40_Mag",8},{},""},{"LM_OPCAN_UNSCA_TRO_UNI",{{"FirstAidKit",1},{"OPTRE_8Rnd_127x40_Mag",2,8},{"Chemlight_green",2,1},{"HandGrenade",2,1}}},{"LM_OPCAN_M52A_AR_Rifle_DES",{{"OPTRE_48Rnd_5x23mm_FMJ_Mag",9,48}}},{"OPTRE_UNSC_Rucksack_Medic_Filled",{{"OPTRE_Biofoam",12},{"OPTRE_MedKit",2},{"ACE_elasticBandage",10},{"ACE_packingBandage",10},{"ACE_quikclot",10},{"ACE_fieldDressing",10},{"ACE_splint",20},{"ACE_tourniquet",20}}},"LM_OPCAN_CH252_AR_T_M_C","",{},{"ItemMap","","ItemRadio","ItemCompass","ItemWatch","LM_OPCAN_COMM"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class B_UNMar_Marksman_ALiVE_OPTRE_01 : LM_OPCAN_UNSCA_Marksman_MIX_OCimport_02 {
        author = "Capt. Houlston, L";
        scope = 2;
        scopeCurator = 2;
        displayName = "Marksman [ALiVE]";
        side = 1;
        faction = "B_UNMar_OPTRE";

        identityTypes[] = {"Head_NATO","LanguageENG_F","NoGlassesÃ¯Â»Â¿"};

        uniformClass = "LM_OPCAN_UNSCA_WDL_1_UNI";

        linkedItems[] = {"LM_OPCAN_M52A_AR_Light_DES","LM_OPCAN_CH252_AR_T_C","ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch","LM_OPCAN_CAMSNI"};
        respawnlinkedItems[] = {"LM_OPCAN_M52A_AR_Light_DES","LM_OPCAN_CH252_AR_T_C","ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch","LM_OPCAN_CAMSNI"};

        weapons[] = {"OPTRE_M392_DMR_ScopedRifle","OPTRE_M6G_SF","OPTRE_Binoculars"};
        respawnWeapons[] = {"OPTRE_M392_DMR_ScopedRifle","OPTRE_M6G_SF","OPTRE_Binoculars"};

        magazines[] = {"OPTRE_15Rnd_762x51_Mag","OPTRE_8Rnd_127x40_Mag","OPTRE_15Rnd_762x51_Mag","OPTRE_8Rnd_127x40_Mag"};
        respawnMagazines[] = {"OPTRE_15Rnd_762x51_Mag","OPTRE_8Rnd_127x40_Mag","OPTRE_15Rnd_762x51_Mag","OPTRE_8Rnd_127x40_Mag"};

        ALiVE_orbatCreator_loadout[] = {{"OPTRE_M392_DMR_ScopedRifle","","","OPTRE_M392_Scope",{"OPTRE_15Rnd_762x51_Mag",15},{},""},{},{"OPTRE_M6G_SF","","OPTRE_M6G_Flashlight","OPTRE_M6G_Scope",{"OPTRE_8Rnd_127x40_Mag",8},{},""},{"LM_OPCAN_UNSCA_WDL_1_UNI",{{"FirstAidKit",1},{"ACE_EarPlugs",1},{"ACE_elasticBandage",10},{"ACE_fieldDressing",10},{"ACE_packingBandage",10},{"ACE_quikclot",10},{"ACE_bloodIV",1},{"ACE_EntrenchingTool",1},{"ACE_Flashlight_MX991",1},{"ACE_tourniquet",3},{"ACE_splint",2},{"ACE_RangeCard",1},{"OPTRE_8Rnd_127x40_Mag",2,8},{"Chemlight_green",2,1},{"HandGrenade",2,1}}},{"LM_OPCAN_M52A_AR_Light_DES",{}},{},"LM_OPCAN_CH252_AR_T_C","LM_OPCAN_Shemagh",{"OPTRE_Binoculars","","","",{},{},""},{"ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch","LM_OPCAN_CAMSNI"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class B_UNMar_RTO_ALiVE_OPTRE_01 : LM_OPCAN_UNSCA_RTO_MIX_OCimport_02 {
        author = "Capt. Houlston, L";
        scope = 2;
        scopeCurator = 2;
        displayName = "RTO [ALiVE]";
        side = 1;
        faction = "B_UNMar_OPTRE";

        identityTypes[] = {"Head_NATO","LanguageENG_F","NoGlassesÃ¯Â»Â¿"};

        uniformClass = "LM_OPCAN_UNSCA_WDL_3_UNI";

        linkedItems[] = {"LM_OPCAN_M52A_AR_Light_DES","LM_OPCAN_CH252_AR_T2_C","ItemMap","ItemRadio","ItemCompass","ItemWatch","LM_OPCAN_COMMCAMSNI"};
        respawnlinkedItems[] = {"LM_OPCAN_M52A_AR_Light_DES","LM_OPCAN_CH252_AR_T2_C","ItemMap","ItemRadio","ItemCompass","ItemWatch","LM_OPCAN_COMMCAMSNI"};

        weapons[] = {"OPTRE_M7","OPTRE_M6G_SF"};
        respawnWeapons[] = {"OPTRE_M7","OPTRE_M6G_SF"};

        magazines[] = {"OPTRE_48Rnd_5x23mm_FMJ_Mag","OPTRE_8Rnd_127x40_Mag","OPTRE_48Rnd_5x23mm_FMJ_Mag","OPTRE_8Rnd_127x40_Mag"};
        respawnMagazines[] = {"OPTRE_48Rnd_5x23mm_FMJ_Mag","OPTRE_8Rnd_127x40_Mag","OPTRE_48Rnd_5x23mm_FMJ_Mag","OPTRE_8Rnd_127x40_Mag"};

        backpack = "OPTRE_ANPRC_521_Green";

        ALiVE_orbatCreator_loadout[] = {{"OPTRE_M7","","","",{"OPTRE_48Rnd_5x23mm_FMJ_Mag",48},{},""},{},{"OPTRE_M6G_SF","","OPTRE_M6G_Flashlight","OPTRE_M6G_Scope",{"OPTRE_8Rnd_127x40_Mag",8},{},""},{"LM_OPCAN_UNSCA_WDL_3_UNI",{{"FirstAidKit",1},{"OPTRE_48Rnd_5x23mm_FMJ_Mag",9,48},{"OPTRE_8Rnd_127x40_Mag",2,8},{"Chemlight_green",2,1},{"HandGrenade",2,1}}},{"LM_OPCAN_M52A_AR_Light_DES",{{"ACE_elasticBandage",10},{"ACE_fieldDressing",10},{"ACE_packingBandage",10},{"ACE_quikclot",10},{"ACE_splint",5},{"ACE_tourniquet",4}}},{"OPTRE_ANPRC_521_Green",{}},"LM_OPCAN_CH252_AR_T2_C","",{},{"ItemMap","","ItemRadio","ItemCompass","ItemWatch","LM_OPCAN_COMMCAMSNI"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class B_UNMar_Sniper_ALiVE_OPTRE_01 : LM_OPCAN_UNSCA_Sniper_MIX_OCimport_02 {
        author = "Capt. Houlston, L";
        scope = 2;
        scopeCurator = 2;
        displayName = "Sniper [ALiVE]";
        side = 1;
        faction = "B_UNMar_OPTRE";

        identityTypes[] = {"Head_NATO","LanguageENG_F","NoGlassesÃ¯Â»Â¿"};

        uniformClass = "LM_OPCAN_UNSCA_WDL_2_UNI";

        linkedItems[] = {"LM_OPCAN_M52A_AR_Light_DES","LM_OPCAN_CH252_AR_D_C","ItemMap","ItemRadio","ItemCompass","ItemWatch","LM_OPCAN_COMMCAMSNI"};
        respawnlinkedItems[] = {"LM_OPCAN_M52A_AR_Light_DES","LM_OPCAN_CH252_AR_D_C","ItemMap","ItemRadio","ItemCompass","ItemWatch","LM_OPCAN_COMMCAMSNI"};

        weapons[] = {"OPTRE_SRS99C_SC_LS","OPTRE_M6G_SF"};
        respawnWeapons[] = {"OPTRE_SRS99C_SC_LS","OPTRE_M6G_SF"};

        magazines[] = {"OPTRE_4Rnd_145x114_APFSDS_Mag","OPTRE_8Rnd_127x40_Mag","OPTRE_4Rnd_145x114_APFSDS_Mag","OPTRE_8Rnd_127x40_Mag"};
        respawnMagazines[] = {"OPTRE_4Rnd_145x114_APFSDS_Mag","OPTRE_8Rnd_127x40_Mag","OPTRE_4Rnd_145x114_APFSDS_Mag","OPTRE_8Rnd_127x40_Mag"};

        ALiVE_orbatCreator_loadout[] = {{"OPTRE_SRS99C_SC_LS","","","OPTRE_SRS99C_Scope",{"OPTRE_4Rnd_145x114_APFSDS_Mag",4},{},""},{},{"OPTRE_M6G_SF","","OPTRE_M6G_Flashlight","OPTRE_M6G_Scope",{"OPTRE_8Rnd_127x40_Mag",8},{},""},{"LM_OPCAN_UNSCA_WDL_2_UNI",{{"FirstAidKit",1},{"ACE_EarPlugs",1},{"ACE_RangeCard",1},{"ACE_splint",5},{"ACE_tourniquet",4},{"ACE_Tripod",1},{"ACE_Flashlight_MX991",1},{"OPTRE_8Rnd_127x40_Mag",2,8},{"Chemlight_green",2,1},{"HandGrenade",1,1},{"OPTRE_4Rnd_145x114_APFSDS_Mag",5,4}}},{"LM_OPCAN_M52A_AR_Light_DES",{{"HandGrenade",1,1},{"OPTRE_4Rnd_145x114_APFSDS_Mag",3,4},{"OPTRE_4Rnd_145x114_HVAP_Mag",1,4},{"OPTRE_4Rnd_145x114_HEDP_Mag",1,4}}},{},"LM_OPCAN_CH252_AR_D_C","",{},{"ItemMap","","ItemRadio","ItemCompass","ItemWatch","LM_OPCAN_COMMCAMSNI"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class B_UNMar_Autorifleman_ALiVE_OPTRE_01 : LM_OPCAN_UNSCA_AutoRifleman_MIX_OCimport_02 {
        author = "Capt. Houlston, L";
        scope = 2;
        scopeCurator = 2;
        displayName = "Autorifleman [ALiVE]";
        side = 1;
        faction = "B_UNMar_OPTRE";

        identityTypes[] = {"Head_NATO","LanguageENG_F","NoGlassesÃ¯Â»Â¿"};

        uniformClass = "LM_OPCAN_UNSCA_WDL_4_UNI";

        linkedItems[] = {"LM_OPCAN_M52A_AR_Autorifleman_DES","LM_OPCAN_CH252_AR_T_C","ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch","LM_OPCAN_COMM"};
        respawnlinkedItems[] = {"LM_OPCAN_M52A_AR_Autorifleman_DES","LM_OPCAN_CH252_AR_T_C","ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch","LM_OPCAN_COMM"};

        weapons[] = {"OPTRE_M73_AC","OPTRE_M6G_SF"};
        respawnWeapons[] = {"OPTRE_M73_AC","OPTRE_M6G_SF"};

        magazines[] = {"OPTRE_200Rnd_95x40_Box","OPTRE_8Rnd_127x40_Mag","OPTRE_200Rnd_95x40_Box","OPTRE_8Rnd_127x40_Mag"};
        respawnMagazines[] = {"OPTRE_200Rnd_95x40_Box","OPTRE_8Rnd_127x40_Mag","OPTRE_200Rnd_95x40_Box","OPTRE_8Rnd_127x40_Mag"};

        backpack = "OPTRE_UNSC_Rucksack_Heavy";

        ALiVE_orbatCreator_loadout[] = {{"OPTRE_M73_AC","","","OPTRE_M73_SmartLink",{"OPTRE_200Rnd_95x40_Box",200},{},"bipod_01_F_blk"},{},{"OPTRE_M6G_SF","","OPTRE_M6G_Flashlight","OPTRE_M6G_Scope",{"OPTRE_8Rnd_127x40_Mag",8},{},""},{"LM_OPCAN_UNSCA_WDL_4_UNI",{{"FirstAidKit",1},{"ACE_EarPlugs",1},{"ACE_packingBandage",10},{"ACE_quikclot",10},{"ACE_elasticBandage",8},{"ACE_fieldDressing",5},{"ACE_Flashlight_MX991",1},{"OPTRE_8Rnd_127x40_Mag",2,8},{"Chemlight_green",2,1},{"HandGrenade",2,1}}},{"LM_OPCAN_M52A_AR_Autorifleman_DES",{}},{"OPTRE_UNSC_Rucksack_Heavy",{{"OPTRE_100Rnd_95x40_Box",4,100}}},"LM_OPCAN_CH252_AR_T_C","LM_OPCAN_Eyepiece",{},{"ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch","LM_OPCAN_COMM"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class B_UNMar_Crewman_ALiVE_OPTRE_01 : LM_OPCAN_UNSCA_Crewman_MIX_OCimport_02 {
        author = "Capt. Houlston, L";
        scope = 2;
        scopeCurator = 2;
        displayName = "Crewman [ALiVE]";
        side = 1;
        faction = "B_UNMar_OPTRE";

        identityTypes[] = {"Head_NATO","LanguageENG_F","NoGlassesÃ¯Â»Â¿"};

        uniformClass = "LM_OPCAN_UNSCA_WDL_3_UNI";

        linkedItems[] = {"LM_OPCAN_M52A_AR_vest_DES","OPTRE_UNSC_VX16_HelmetV_des","ItemMap","ItemRadio","ItemCompass","ItemWatch","OPTRE_NVG"};
        respawnlinkedItems[] = {"LM_OPCAN_M52A_AR_vest_DES","OPTRE_UNSC_VX16_HelmetV_des","ItemMap","ItemRadio","ItemCompass","ItemWatch","OPTRE_NVG"};

        weapons[] = {"OPTRE_M7","OPTRE_M6G_SF"};
        respawnWeapons[] = {"OPTRE_M7","OPTRE_M6G_SF"};

        magazines[] = {"OPTRE_48Rnd_5x23mm_FMJ_Mag","OPTRE_8Rnd_127x40_Mag","OPTRE_48Rnd_5x23mm_FMJ_Mag","OPTRE_8Rnd_127x40_Mag"};
        respawnMagazines[] = {"OPTRE_48Rnd_5x23mm_FMJ_Mag","OPTRE_8Rnd_127x40_Mag","OPTRE_48Rnd_5x23mm_FMJ_Mag","OPTRE_8Rnd_127x40_Mag"};

        ALiVE_orbatCreator_loadout[] = {{"OPTRE_M7","","","",{"OPTRE_48Rnd_5x23mm_FMJ_Mag",48},{},""},{},{"OPTRE_M6G_SF","","OPTRE_M6G_Flashlight","OPTRE_M6G_Scope",{"OPTRE_8Rnd_127x40_Mag",8},{},""},{"LM_OPCAN_UNSCA_WDL_3_UNI",{{"FirstAidKit",1},{"OPTRE_48Rnd_5x23mm_FMJ_Mag",9,48},{"OPTRE_8Rnd_127x40_Mag",2,8},{"Chemlight_green",2,1},{"HandGrenade",2,1}}},{"LM_OPCAN_M52A_AR_vest_DES",{}},{},"OPTRE_UNSC_VX16_HelmetV_des","",{},{"ItemMap","","ItemRadio","ItemCompass","ItemWatch","OPTRE_NVG"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class B_UNMar_Rifleman_AT_ALiVE_OPTRE_01 : LM_OPCAN_UNSCA_Rifleman_AT_MIX_OCimport_02 {
        author = "Capt. Houlston, L";
        scope = 2;
        scopeCurator = 2;
        displayName = "Rifleman [AT] [ALiVE]";
        side = 1;
        faction = "B_UNMar_OPTRE";

        identityTypes[] = {"Head_NATO","LanguageENG_F","NoGlassesÃ¯Â»Â¿"};

        uniformClass = "LM_OPCAN_UNSCA_TRO_UNI";

        linkedItems[] = {"LM_OPCAN_M52A_AR_Light_DES","LM_OPCAN_CH252_AR_D2_C","ItemMap","ItemRadio","ItemCompass","ItemWatch","LM_OPCAN_COMMCAMUA"};
        respawnlinkedItems[] = {"LM_OPCAN_M52A_AR_Light_DES","LM_OPCAN_CH252_AR_D2_C","ItemMap","ItemRadio","ItemCompass","ItemWatch","LM_OPCAN_COMMCAMUA"};

        weapons[] = {"OPTRE_MA37","OPTRE_M41_SSR"};
        respawnWeapons[] = {"OPTRE_MA37","OPTRE_M41_SSR"};

        magazines[] = {"OPTRE_32Rnd_762x51_Mag","OPTRE_M41_Twin_HEAT","OPTRE_32Rnd_762x51_Mag"};
        respawnMagazines[] = {"OPTRE_32Rnd_762x51_Mag","OPTRE_M41_Twin_HEAT","OPTRE_32Rnd_762x51_Mag"};

        backpack = "OPTRE_UNSC_Rucksack_M41";

        ALiVE_orbatCreator_loadout[] = {{"OPTRE_MA37","","","",{"OPTRE_32Rnd_762x51_Mag",32},{},""},{"OPTRE_M41_SSR","","","",{"OPTRE_M41_Twin_HEAT",2},{},""},{},{"LM_OPCAN_UNSCA_TRO_UNI",{{"FirstAidKit",1},{"ACE_EarPlugs",1},{"OPTRE_32Rnd_762x51_Mag",9,32},{"OPTRE_8Rnd_127x40_Mag",3,8},{"Chemlight_green",2,1},{"HandGrenade",2,1}}},{"LM_OPCAN_M52A_AR_Light_DES",{}},{"OPTRE_UNSC_Rucksack_M41",{{"OPTRE_M41_Twin_HEAT_SACLOS",2,2}}},"LM_OPCAN_CH252_AR_D2_C","",{},{"ItemMap","","ItemRadio","ItemCompass","ItemWatch","LM_OPCAN_COMMCAMUA"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class B_UNMar_Rifleman_AA_ALiVE_OPTRE_01 : LM_OPCAN_UNSCA_Rifleman_AT_MIX_OCimport_02 {
        author = "Capt. Houlston, L";
        scope = 2;
        scopeCurator = 2;
        displayName = "Rifleman [AA] [ALiVE]";
        side = 1;
        faction = "B_UNMar_OPTRE";

        identityTypes[] = {"Head_NATO","LanguageENG_F","NoGlassesÃ¯Â»Â¿"};

        uniformClass = "LM_OPCAN_UNSCA_TRO_UNI";

        linkedItems[] = {"LM_OPCAN_M52A_AR_Light_DES","LM_OPCAN_CH252_AR_D2_C","ItemMap","ItemRadio","ItemCompass","ItemWatch","LM_OPCAN_COMMCAMUA"};
        respawnlinkedItems[] = {"LM_OPCAN_M52A_AR_Light_DES","LM_OPCAN_CH252_AR_D2_C","ItemMap","ItemRadio","ItemCompass","ItemWatch","LM_OPCAN_COMMCAMUA"};

        weapons[] = {"OPTRE_MA37","OPTRE_M41_SSR"};
        respawnWeapons[] = {"OPTRE_MA37","OPTRE_M41_SSR"};

        magazines[] = {"OPTRE_32Rnd_762x51_Mag","OPTRE_M41_Twin_HEAT","OPTRE_32Rnd_762x51_Mag"};
        respawnMagazines[] = {"OPTRE_32Rnd_762x51_Mag","OPTRE_M41_Twin_HEAT","OPTRE_32Rnd_762x51_Mag"};

        backpack = "OPTRE_UNSC_Rucksack_M41";

        ALiVE_orbatCreator_loadout[] = {{"OPTRE_MA37","","","",{"OPTRE_32Rnd_762x51_Mag",32},{},""},{"OPTRE_M41_SSR","","","",{"OPTRE_M41_Twin_HEAT",2},{},""},{},{"LM_OPCAN_UNSCA_TRO_UNI",{{"FirstAidKit",1},{"ACE_EarPlugs",1},{"OPTRE_32Rnd_762x51_Mag",9,32},{"OPTRE_8Rnd_127x40_Mag",3,8},{"Chemlight_green",2,1},{"HandGrenade",2,1}}},{"LM_OPCAN_M52A_AR_Light_DES",{}},{"OPTRE_UNSC_Rucksack_M41",{{"OPTRE_M41_Twin_HEAT_Thermal",2,2}}},"LM_OPCAN_CH252_AR_D2_C","",{},{"ItemMap","","ItemRadio","ItemCompass","ItemWatch","LM_OPCAN_COMMCAMUA"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class B_BUNMarOPTRE_Engineer_ALiVE_01 : LM_OPCAN_UNSCA_Engineer_MIX_OCimport_02 {
        author = "Capt. Houlston, L";
        scope = 2;
        scopeCurator = 2;
        displayName = "Engineer [ALiVE]";
        side = 1;
        faction = "B_UNMar_OPTRE";

        identityTypes[] = {"Head_NATO","LanguageENG_F","NoGlassesÃ¯Â»Â¿"};

        uniformClass = "LM_OPCAN_UNSCA_WDL_1_UNI";

        linkedItems[] = {"LM_OPCAN_M52A_AR_Rifle_DES","LM_OPCAN_CH252_AR_Y2_C","ItemMap","ItemRadio","ItemCompass","ItemWatch","LM_OPCAN_CAM"};
        respawnlinkedItems[] = {"LM_OPCAN_M52A_AR_Rifle_DES","LM_OPCAN_CH252_AR_Y2_C","ItemMap","ItemRadio","ItemCompass","ItemWatch","LM_OPCAN_CAM"};

        weapons[] = {"OPTRE_M45","OPTRE_M6G_SF"};
        respawnWeapons[] = {"OPTRE_M45","OPTRE_M6G_SF"};

        magazines[] = {"OPTRE_6Rnd_8Gauge_Pellets","OPTRE_8Rnd_127x40_Mag_Tracer","OPTRE_6Rnd_8Gauge_Pellets","OPTRE_8Rnd_127x40_Mag_Tracer"};
        respawnMagazines[] = {"OPTRE_6Rnd_8Gauge_Pellets","OPTRE_8Rnd_127x40_Mag_Tracer","OPTRE_6Rnd_8Gauge_Pellets","OPTRE_8Rnd_127x40_Mag_Tracer"};

        backpack = "OPTRE_UNSC_Rucksack_Heavy_Demo";

        ALiVE_orbatCreator_loadout[] = {{"OPTRE_M45","","","",{"OPTRE_6Rnd_8Gauge_Pellets",6},{},""},{},{"OPTRE_M6G_SF","","OPTRE_M6G_Flashlight","OPTRE_M6G_Scope",{"OPTRE_8Rnd_127x40_Mag_Tracer",8},{},""},{"LM_OPCAN_UNSCA_WDL_1_UNI",{{"FirstAidKit",1},{"OPTRE_8Rnd_127x40_Mag_Tracer",2,8},{"OPTRE_6Rnd_8Gauge_Slugs",6,6},{"OPTRE_6Rnd_8Gauge_Pellets",5,6}}},{"LM_OPCAN_M52A_AR_Rifle_DES",{}},{"OPTRE_UNSC_Rucksack_Heavy_Demo",{{"ToolKit",1},{"MineDetector",1},{"UNSCMine_Range_Mag",2,1},{"C12_Remote_Mag",2,1}}},"LM_OPCAN_CH252_AR_Y2_C","",{},{"ItemMap","","ItemRadio","ItemCompass","ItemWatch","LM_OPCAN_CAM"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class B_BUNMarOPTRE_AFV_102_Hound_ALiVE_01 : LM_OPCAN_AFV102_AR_MIX_OCimport_02 {
        author = "Capt. Houlston, L";
        scope = 2;
        scopeCurator = 2;
        displayName = "AFV-102 Hound [ALiVE]";
        side = 1;
        faction = "B_UNMar_OPTRE";
        crew = "B_UNMar_Crewman_ALiVE_OPTRE_01";

        class Turrets : Turrets {
            class MainTurret : MainTurret { gunnerType = "B_UNMar_Crewman_ALiVE_OPTRE_01"; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;_unit setObjectTextureGlobal [0,'A3\Armor_F_Exp\APC_Wheeled_01\data\APC_Wheeled_01_base_olive_CO.paa'];_unit setObjectTextureGlobal [1,'A3\Armor_F_Exp\APC_Wheeled_01\data\APC_Wheeled_01_adds_olive_co.paa'];_unit setObjectTextureGlobal [2,'A3\Armor_F_Exp\APC_Wheeled_01\data\APC_Wheeled_01_tows_olive_co.paa'];_unit setObjectTextureGlobal [3,'a3\Armor_F\Data\camonet_NATO_Green_CO.paa'];_unit setObjectTextureGlobal [4,'a3\Armor_F\Data\cage_olive_CO.paa'];};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_texture = "Olive";

    };

    class B_BUNMarOPTRE_MGS_32_Timberwolf_ALiVE_01 : LM_OPCAN_MGS_AR_MIX_OCimport_02 {
        author = "Capt. Houlston, L";
        scope = 2;
        scopeCurator = 2;
        displayName = "MGS-32 Timberwolf [ALiVE]";
        side = 1;
        faction = "B_UNMar_OPTRE";
        crew = "B_UNMar_Crewman_ALiVE_OPTRE_01";

        class Turrets : Turrets {
            class MainTurret : MainTurret { gunnerType = "B_UNMar_Crewman_ALiVE_OPTRE_01"; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;_unit setObjectTextureGlobal [0,'LM_OPCAN3.0\BLU\UNSC\VEH\MGS_AR_B.paa'];_unit setObjectTextureGlobal [1,'LM_OPCAN3.0\BLU\UNSC\VEH\MGS_AR_G.paa'];_unit setObjectTextureGlobal [2,'a3\Armor_F_Tank\AFV_Wheeled_01\data\afv_wheeled_01_wheel_green_CO.paa'];_unit setObjectTextureGlobal [3,'a3\Armor_F\Data\camonet_NATO_Green_CO.paa'];_unit setObjectTextureGlobal [4,'a3\Armor_F\Data\cage_olive_CO.paa'];};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_texture = "Army";

    };

    class B_BUNMarOPTRE_AV_14_Hornet_Army_ALiVE_01 : LM_OPCAN_AV14_AR_MIX_OCimport_02 {
        author = "Capt. Houlston, L";
        scope = 2;
        scopeCurator = 2;
        displayName = "AV-14 Hornet [Army] [ALiVE]";
        side = 1;
        faction = "B_UNMar_OPTRE";
        crew = "B_UNMar_Crewman_ALiVE_OPTRE_01";

        class Turrets : Turrets {
            class CargoTurret_01 : CargoTurret_01 { gunnerType = ""; };
            class CargoTurret_02 : CargoTurret_02 { gunnerType = ""; };
            class CargoTurret_03 : CargoTurret_03 { gunnerType = ""; };
            class CargoTurret_04 : CargoTurret_04 { gunnerType = ""; };
            class CargoTurret_05 : CargoTurret_05 { gunnerType = ""; };
            class CargoTurret_06 : CargoTurret_06 { gunnerType = ""; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;_unit setObjectTextureGlobal [0,'optre_vehicles\hornet\data\hornet_hull_green_co.paa'];};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_texture = "colorgreen";

    };

    class B_BUNMarOPTRE_UH_144A_Falcon_Army_ALiVE_01 : LM_OPCAN_UH144A_AR_MIX_OCimport_02 {
        author = "Capt. Houlston, L";
        scope = 2;
        scopeCurator = 2;
        displayName = "UH-144A Falcon [Army] [ALiVE]";
        side = 1;
        faction = "B_UNMar_OPTRE";
        crew = "B_UNMar_Crewman_ALiVE_OPTRE_01";

        class Turrets : Turrets {
            class CargoTurret_01 : CargoTurret_01 { gunnerType = ""; };
            class CargoTurret_02 : CargoTurret_02 { gunnerType = ""; };
            class CargoTurret_03 : CargoTurret_03 { gunnerType = ""; };
            class CargoTurret_04 : CargoTurret_04 { gunnerType = ""; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;_unit setObjectTextureGlobal [0,'OPTRE_Vehicles\Falcon\data\falcon_hull_CO.paa'];_unit setObjectTextureGlobal [1,'optre_vehicles\falcon\data\falcon_hullextra_co.paa'];_unit setObjectTextureGlobal [2,'optre_vehicles\falcon\data\falcon_wingtips_co.paa'];_unit setObjectTextureGlobal [3,'optre_vehicles\falcon\data\falcon_skid_co.paa'];};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_texture = "colorgreen";

    };

    class B_BUNMarOPTRE_UH_144_Falcon_Army_ALiVE_01 : LM_OPCAN_UH144_AR_MIX_OCimport_02 {
        author = "Capt. Houlston, L";
        scope = 2;
        scopeCurator = 2;
        displayName = "UH-144 Falcon [Army] [ALiVE]";
        side = 1;
        faction = "B_UNMar_OPTRE";
        crew = "B_UNMar_Crewman_ALiVE_OPTRE_01";

        class Turrets : Turrets {
            class CargoTurret_01 : CargoTurret_01 { gunnerType = ""; };
            class CargoTurret_02 : CargoTurret_02 { gunnerType = ""; };
            class CargoTurret_03 : CargoTurret_03 { gunnerType = ""; };
            class CargoTurret_04 : CargoTurret_04 { gunnerType = ""; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;_unit setObjectTextureGlobal [0,'OPTRE_Vehicles\Falcon\data\falcon_hull_CO.paa'];_unit setObjectTextureGlobal [1,'optre_vehicles\falcon\data\falcon_hullextra_co.paa'];_unit setObjectTextureGlobal [2,'optre_vehicles\falcon\data\falcon_wingtips_co.paa'];_unit setObjectTextureGlobal [3,'optre_vehicles\falcon\data\falcon_skid_co.paa'];};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_texture = "colorgreen";

    };

    class B_BUNMarOPTRE_D77_TC_Pelican_Army_ALiVE_01 : LM_OPCAN_D77_U_AR_MIX_OCimport_02 {
        author = "Capt. Houlston, L";
        scope = 2;
        scopeCurator = 2;
        displayName = "D77-TC Pelican [Army] [ALiVE]";
        side = 1;
        faction = "B_UNMar_OPTRE";
        crew = "B_UNMar_Crewman_ALiVE_OPTRE_01";

        class Turrets : Turrets {
            class CopilotTurret : CopilotTurret { gunnerType = "B_UNMar_Crewman_ALiVE_OPTRE_01"; };
            class CargoTurret_01 : CargoTurret_01 { gunnerType = ""; };
            class CargoTurret_02 : CargoTurret_02 { gunnerType = ""; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;_unit setObjectTextureGlobal [0,'OPTRE_Vehicles\Pelican\data\PelicanExterior_green_CO.paa'];};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_texture = "colorgreen";

    };

    class B_BUNMarOPTRE_D77_TC_AV_Pelican_Army_ALiVE_01 : LM_OPCAN_D77_A_AR_MIX_OCimport_02 {
        author = "Capt. Houlston, L";
        scope = 2;
        scopeCurator = 2;
        displayName = "D77-TC/AV Pelican [Army] [ALiVE]";
        side = 1;
        faction = "B_UNMar_OPTRE";
        crew = "B_UNMar_Crewman_ALiVE_OPTRE_01";

        class Turrets : Turrets {
            class CopilotTurret : CopilotTurret { gunnerType = "B_UNMar_Crewman_ALiVE_OPTRE_01"; };
            class CargoTurret_01 : CargoTurret_01 { gunnerType = ""; };
            class CargoTurret_02 : CargoTurret_02 { gunnerType = ""; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;_unit setObjectTextureGlobal [0,'OPTRE_Vehicles\Pelican\data\PelicanExterior_green_CO.paa'];_unit setObjectTextureGlobal [1,'OPTRE_Vehicles\Pelican\data\PelicanExterior_green_CO.paa'];};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_texture = "colorgreen";

    };

    class B_BUNMarOPTRE_M808_Scorpion_MBT_Army_ALiVE_01 : LM_OPCAN_M808_AR_MIX_OCimport_02 {
        author = "Capt. Houlston, L";
        scope = 2;
        scopeCurator = 2;
        displayName = "M808 Scorpion MBT [Army] [ALiVE]";
        side = 1;
        faction = "B_UNMar_OPTRE";
        crew = "B_UNMar_Crewman_ALiVE_OPTRE_01";

        class Turrets : Turrets {
            class MainTurret : MainTurret { gunnerType = "B_UNMar_Crewman_ALiVE_OPTRE_01"; };
            class CargoTurret1 : CargoTurret1 { gunnerType = ""; };
            class CargoTurret2 : CargoTurret2 { gunnerType = ""; };
            class CargoTurret3 : CargoTurret3 { gunnerType = ""; };
            class CargoTurret4 : CargoTurret4 { gunnerType = ""; };
            class CargoTurret5 : CargoTurret5 { gunnerType = ""; };
            class CargoTurret6 : CargoTurret6 { gunnerType = ""; };
            class CargoTurret7 : CargoTurret7 { gunnerType = ""; };
            class CargoTurret8 : CargoTurret8 { gunnerType = ""; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;_unit setObjectTextureGlobal [0,'OPTRE_Vehicles\Scorpion\data\body_co.paa'];_unit setObjectTextureGlobal [1,'OPTRE_Vehicles\Scorpion\data\decals_ca.paa'];_unit setObjectTextureGlobal [2,'OPTRE_Vehicles\Scorpion\data\interior_co.paa'];_unit setObjectTextureGlobal [3,'OPTRE_Vehicles\Scorpion\data\miscparts_co.paa'];_unit setObjectTextureGlobal [4,'OPTRE_Vehicles\Scorpion\data\trackhousing_co.paa'];_unit setObjectTextureGlobal [5,'OPTRE_Vehicles\Scorpion\data\turret_co.paa'];};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_texture = "colorgreen";

    };

    class B_BUNMarOPTRE_M12_FAV_Army_ALiVE_01 : OPTRE_M12_FAV_OCimport_02 {
        author = "Capt. Houlston, L";
        scope = 2;
        scopeCurator = 2;
        displayName = "M12-FAV [Army] [ALiVE]";
        side = 1;
        faction = "B_UNMar_OPTRE";
        crew = "B_UNMar_Squad_Leader_ALiVE_OPTRE_01";

        class Turrets : Turrets {
            class CargoGunner_1 : CargoGunner_1 { gunnerType = "B_UNMar_RTO_ALiVE_OPTRE_01"; };
            class CargoTurret_02 : CargoTurret_02 { gunnerType = "B_UNMar_Rifleman_ALiVE_OPTRE_01"; };
            class CargoTurret_03 : CargoTurret_03 { gunnerType = "B_UNMar_Marksman_ALiVE_OPTRE_01"; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;_unit setObjectTextureGlobal [0,'\OPTRE_Vehicles\Warthog\data\M12HogMaav_extupper_co.paa'];_unit setObjectTextureGlobal [1,'\OPTRE_Vehicles\Warthog\data\M12HogMaav_extunder_co.paa'];};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_texture = "colorstand";

    };

    class B_BUNMarOPTRE_M12G1_LRV_Gauss_Army_ALiVE_01 : OPTRE_M12G1_LRV_OCimport_02 {
        author = "Capt. Houlston, L";
        scope = 2;
        scopeCurator = 2;
        displayName = "M12G1 LRV [Gauss] [Army] [ALiVE]";
        side = 1;
        faction = "B_UNMar_OPTRE";
        crew = "B_UNMar_Squad_Leader_ALiVE_OPTRE_01";

        class Turrets : Turrets {
            class CargoGunner_1 : CargoGunner_1 { gunnerType = "B_UNMar_Grenadier_ALiVE_OPTRE_01"; };
            class MainTurret : MainTurret { gunnerType = "B_UNMar_Rifleman_ALiVE_OPTRE_01"; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class B_BUNMarOPTRE_M12_LRV_MG_Army_ALiVE_01 : OPTRE_M12_LRV_OCimport_02 {
        author = "Capt. Houlston, L";
        scope = 2;
        scopeCurator = 2;
        displayName = "M12 LRV [MG] [Army] [ALiVE]";
        side = 1;
        faction = "B_UNMar_OPTRE";
        crew = "B_UNMar_Squad_Leader_ALiVE_OPTRE_01";

        class Turrets : Turrets {
            class CargoGunner_1 : CargoGunner_1 { gunnerType = "B_UNMar_Rifleman_ALiVE_OPTRE_01"; };
            class MainTurret : MainTurret { gunnerType = "B_UNMar_Rifleman_ALiVE_OPTRE_01"; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class B_BUNMarOPTRE_M813_TT_Army_ALiVE_01 : OPTRE_M813_TT_OCimport_02 {
        author = "Capt. Houlston, L";
        scope = 2;
        scopeCurator = 2;
        displayName = "M813 TT [Army] [ALiVE]";
        side = 1;
        faction = "B_UNMar_OPTRE";
        crew = "B_UNMar_Squad_Leader_ALiVE_OPTRE_01";

        class Turrets : Turrets {
            class CargoGunner_1 : CargoGunner_1 { gunnerType = "B_UNMar_RTO_ALiVE_OPTRE_01"; };
            class CargoGunner_02 : CargoGunner_02 { gunnerType = "B_UNMar_Grenadier_ALiVE_OPTRE_01"; };
            class CargoGunner_03 : CargoGunner_03 { gunnerType = "B_UNMar_Rifleman_ALiVE_OPTRE_01"; };
            class CargoGunner_04 : CargoGunner_04 { gunnerType = "B_UNMar_Autorifleman_ALiVE_OPTRE_01"; };
            class CargoGunner_05 : CargoGunner_05 { gunnerType = "B_UNMar_Rifleman_AT_ALiVE_OPTRE_01"; };
            class CargoGunner_06 : CargoGunner_06 { gunnerType = "B_UNMar_Rifleman_AA_ALiVE_OPTRE_01"; };
            class CargoGunner_07 : CargoGunner_07 { gunnerType = "B_BUNMarOPTRE_Engineer_ALiVE_01"; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class B_BUNMarOPTRE_M12R_AA_Army_ALiVE_01 : OPTRE_M12R_AA_OCimport_02 {
        author = "Capt. Houlston, L";
        scope = 2;
        scopeCurator = 2;
        displayName = "M12R [AA] [Army] [ALiVE]";
        side = 1;
        faction = "B_UNMar_OPTRE";
        crew = "B_UNMar_Team_Leader_ALiVE_OPTRE_01";

        class Turrets : Turrets {
            class CargoGunner_1 : CargoGunner_1 { gunnerType = "B_UNMar_RTO_ALiVE_OPTRE_01"; };
            class MainTurret : MainTurret { gunnerType = "B_UNMar_Marksman_ALiVE_OPTRE_01"; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class B_BUNMarOPTRE_M914_RH_Army_ALiVE_01 : OPTRE_M914_RV_OCimport_02 {
        author = "Capt. Houlston, L";
        scope = 2;
        scopeCurator = 2;
        displayName = "M914 [RH] [Army] [ALiVE]";
        side = 1;
        faction = "B_UNMar_OPTRE";
        crew = "B_BUNMarOPTRE_Engineer_ALiVE_01";

        class Turrets : Turrets {
            class CargoGunner_1 : CargoGunner_1 { gunnerType = "B_BUNMarOPTRE_Engineer_ALiVE_01"; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class B_BUNMarOPTRE_ODST_Demolitions_ALiVE_02 : OPTRE_UNSC_ODST_Soldier_DemolitionsExpert_OCimport_02 {
        author = "Capt. Houlston, L";
        scope = 2;
        scopeCurator = 2;
        displayName = "ODST Demolitions [ALiVE]";
        side = 1;
        faction = "B_UNMar_OPTRE";

        identityTypes[] = {"Head_NATO","LanguageGRE_F","Miller","Kerry","EPA_B_Northgate","EPA_B_Hardy","EPA_B_James","EPA_B_McKay","G_IRAN_default"};

        uniformClass = "LM_OPCAN_UNSCA_WDL_1_UNI";

        linkedItems[] = {"LM_OPCAN_Demo_ODST_Yellow","LM_OPCAN_CH252D_Yellow","ItemMap","ItemRadio","ItemCompass","ItemWatch","OPTRE_NVG"};
        respawnlinkedItems[] = {"LM_OPCAN_Demo_ODST_Yellow","LM_OPCAN_CH252D_Yellow","ItemMap","ItemRadio","ItemCompass","ItemWatch","OPTRE_NVG"};

        weapons[] = {"OPTRE_M7S","OPTRE_M6G_SF"};
        respawnWeapons[] = {"OPTRE_M7S","OPTRE_M6G_SF"};

        magazines[] = {"OPTRE_60Rnd_5x23mm_Mag_tracer","OPTRE_8Rnd_127x40_Mag_Tracer","OPTRE_60Rnd_5x23mm_Mag_tracer","OPTRE_8Rnd_127x40_Mag_Tracer"};
        respawnMagazines[] = {"OPTRE_60Rnd_5x23mm_Mag_tracer","OPTRE_8Rnd_127x40_Mag_Tracer","OPTRE_60Rnd_5x23mm_Mag_tracer","OPTRE_8Rnd_127x40_Mag_Tracer"};

        backpack = "OPTRE_ILCS_Rucksack_Black";

        ALiVE_orbatCreator_loadout[] = {{"OPTRE_M7S","OPTRE_M7_silencer","OPTRE_M7_Laser","OPTRE_M7_Sight",{"OPTRE_60Rnd_5x23mm_Mag_tracer",60},{},""},{},{"OPTRE_M6G_SF","","OPTRE_M6G_Flashlight","OPTRE_M6G_Scope",{"OPTRE_8Rnd_127x40_Mag_Tracer",8},{},""},{"LM_OPCAN_UNSCA_WDL_1_UNI",{{"OPTRE_Biofoam",4},{"OPTRE_Medigel",5},{"OPTRE_60Rnd_5x23mm_Mag_tracer",3,60},{"OPTRE_M2_Smoke_Orange",1,1},{"OPTRE_M2_Smoke_Green",1,1}}},{"LM_OPCAN_Demo_ODST_Yellow",{{"ACE_M26_Clacker",1},{"OPTRE_60Rnd_5x23mm_Mag_tracer",6,60},{"OPTRE_8Rnd_127x40_Mag_Tracer",3,8},{"OPTRE_M9_Frag",2,1},{"OPTRE_M2_Smoke",1,1}}},{"OPTRE_ILCS_Rucksack_Black",{{"C7_Remote_Mag",5,1}}},"LM_OPCAN_CH252D_Yellow","",{},{"ItemMap","","ItemRadio","ItemCompass","ItemWatch","OPTRE_NVG"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class B_BUNMarOPTRE_ODST_Corpsman_ALiVE_01 : OPTRE_UNSC_ODST_Soldier_Paramedic_OCimport_02 {
        author = "Capt. Houlston, L";
        scope = 2;
        scopeCurator = 2;
        displayName = "ODST Corpsman [ALiVE]";
        side = 1;
        faction = "B_UNMar_OPTRE";

        identityTypes[] = {"Head_NATO","LanguageGRE_F","Miller","Kerry","EPA_B_Northgate","EPA_B_Hardy","EPA_B_James","EPA_B_McKay","G_IRAN_default"};

        uniformClass = "LM_OPCAN_UNSCA_WDL_1_UNI";

        linkedItems[] = {"LM_OPCAN_Light_ODST_REACH","LM_OPCAN_CH252D_REACH","ItemMap","ItemRadio","ItemCompass","ItemWatch","OPTRE_NVG"};
        respawnlinkedItems[] = {"LM_OPCAN_Light_ODST_REACH","LM_OPCAN_CH252D_REACH","ItemMap","ItemRadio","ItemCompass","ItemWatch","OPTRE_NVG"};

        weapons[] = {"OPTRE_M7S","OPTRE_M6G_SF"};
        respawnWeapons[] = {"OPTRE_M7S","OPTRE_M6G_SF"};

        magazines[] = {"OPTRE_60Rnd_5x23mm_Mag_tracer","OPTRE_8Rnd_127x40_Mag_Tracer","OPTRE_60Rnd_5x23mm_Mag_tracer","OPTRE_8Rnd_127x40_Mag_Tracer"};
        respawnMagazines[] = {"OPTRE_60Rnd_5x23mm_Mag_tracer","OPTRE_8Rnd_127x40_Mag_Tracer","OPTRE_60Rnd_5x23mm_Mag_tracer","OPTRE_8Rnd_127x40_Mag_Tracer"};

        backpack = "OPTRE_ILCS_Rucksack_Medical_Filled";

        ALiVE_orbatCreator_loadout[] = {{"OPTRE_M7S","OPTRE_M7_silencer","OPTRE_M7_Laser","OPTRE_M7_Sight",{"OPTRE_60Rnd_5x23mm_Mag_tracer",60},{},""},{},{"OPTRE_M6G_SF","","OPTRE_M6G_Flashlight","OPTRE_M6G_Scope",{"OPTRE_8Rnd_127x40_Mag_Tracer",8},{},""},{"LM_OPCAN_UNSCA_WDL_1_UNI",{{"OPTRE_Biofoam",1},{"OPTRE_60Rnd_5x23mm_Mag_tracer",3,60}}},{"LM_OPCAN_Light_ODST_REACH",{{"OPTRE_60Rnd_5x23mm_Mag_tracer",2,60},{"OPTRE_8Rnd_127x40_Mag_Tracer",3,8}}},{"OPTRE_ILCS_Rucksack_Medical_Filled",{{"OPTRE_Biofoam",12},{"OPTRE_MedKit",2},{"ACE_bloodIV",3},{"ACE_epinephrine",8},{"ACE_morphine",10},{"ACE_splint",10},{"ACE_tourniquet",10}}},"LM_OPCAN_CH252D_REACH","",{},{"ItemMap","","ItemRadio","ItemCompass","ItemWatch","OPTRE_NVG"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class B_BUNMarOPTRE_ODST_Rifleman_ALiVE_01 : OPTRE_UNSC_ODST_Soldier_Scout_OCimport_02 {
        author = "Capt. Houlston, L";
        scope = 2;
        scopeCurator = 2;
        displayName = "ODST Rifleman [ALiVE]";
        side = 1;
        faction = "B_UNMar_OPTRE";

        identityTypes[] = {"Head_NATO","LanguageGRE_F","Miller","Kerry","EPA_B_Northgate","EPA_B_Hardy","EPA_B_James","EPA_B_McKay","G_IRAN_default"};

        uniformClass = "LM_OPCAN_UNSCA_WDL_1_UNI";

        linkedItems[] = {"LM_OPCAN_Vest_ODST_Purple","LM_OPCAN_CH252D_Purple","ItemMap","ItemRadio","ItemCompass","ItemWatch","OPTRE_NVG"};
        respawnlinkedItems[] = {"LM_OPCAN_Vest_ODST_Purple","LM_OPCAN_CH252D_Purple","ItemMap","ItemRadio","ItemCompass","ItemWatch","OPTRE_NVG"};

        weapons[] = {"OPTRE_M7S","OPTRE_M6G_SF"};
        respawnWeapons[] = {"OPTRE_M7S","OPTRE_M6G_SF"};

        magazines[] = {"OPTRE_60Rnd_5x23mm_Mag_tracer","OPTRE_8Rnd_127x40_Mag_Tracer","OPTRE_60Rnd_5x23mm_Mag_tracer","OPTRE_8Rnd_127x40_Mag_Tracer"};
        respawnMagazines[] = {"OPTRE_60Rnd_5x23mm_Mag_tracer","OPTRE_8Rnd_127x40_Mag_Tracer","OPTRE_60Rnd_5x23mm_Mag_tracer","OPTRE_8Rnd_127x40_Mag_Tracer"};

        backpack = "OPTRE_ILCS_Rucksack_Black";

        ALiVE_orbatCreator_loadout[] = {{"OPTRE_M7S","OPTRE_M7_silencer","OPTRE_M7_Laser","OPTRE_M7_Sight",{"OPTRE_60Rnd_5x23mm_Mag_tracer",60},{},""},{},{"OPTRE_M6G_SF","","OPTRE_M6G_Flashlight","OPTRE_M6G_Scope",{"OPTRE_8Rnd_127x40_Mag_Tracer",8},{},""},{"LM_OPCAN_UNSCA_WDL_1_UNI",{{"OPTRE_Biofoam",4},{"OPTRE_Medigel",5},{"OPTRE_60Rnd_5x23mm_Mag_tracer",3,60},{"OPTRE_M2_Smoke_Orange",1,1},{"OPTRE_M2_Smoke_Green",1,1}}},{"LM_OPCAN_Vest_ODST_Purple",{{"ACE_M26_Clacker",1},{"OPTRE_60Rnd_5x23mm_Mag_tracer",6,60},{"OPTRE_8Rnd_127x40_Mag_Tracer",3,8},{"OPTRE_M9_Frag",2,1},{"OPTRE_M2_Smoke",1,1}}},{"OPTRE_ILCS_Rucksack_Black",{{"C7_Remote_Mag",5,1}}},"LM_OPCAN_CH252D_Purple","",{},{"ItemMap","","ItemRadio","ItemCompass","ItemWatch","OPTRE_NVG"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

};