//////////////////////////////////////////////////////////////////////////////////
// Config Automatically Generated by ALiVE ORBAT Creator
// Generated with Arma 3 version 204.147719 on Stable branch
// Generated with ALiVE version 1.14.1.2105061
//////////////////////////////////////////////////////////////////////////////////

class CfgFactionClasses {
    class I_ColMA_OPTRE {
        displayName = "Colonial Military Authority [ALiVE]";
        side = 2;
        flag = "\OPTRE_Core\Data\flag_caa_ca.paa";
        icon = "\OPTRE_Core\Data\flag_caa_ca.paa";
        priority = 0;
    };
};

class CfgGroups {
    class Indep {

        class I_ColMA_OPTRE {
            name = "Colonial Military Authority [ALiVE]";

            class Infantry {
                name = "Infantry";

                class i_icolmaoptre_infantry_sentry {
                    name = "Sentry";
                    side = 2;
                    faction = "I_ColMA_OPTRE";
                    icon = "\A3\ui_f\data\map\markers\nato\n_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 2;
                        vehicle = "I_ColMA_Rifleman_ALiVE_OPTRE_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_ColMA_Grenadier_ALiVE_OPTRE_01";
                    };
                };

                class i_icolmaoptre_infantry_fireteam {
                    name = "Fireteam";
                    side = 2;
                    faction = "I_ColMA_OPTRE";
                    icon = "\A3\ui_f\data\map\markers\nato\n_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 2;
                        vehicle = "I_ColMA_Team_Leader_ALiVE_OPTRE_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_ColMA_Autorifleman_ALiVE_OPTRE_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_IColMAOPTRE_Rifleman_AT_ALiVE_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_ColMA_Grenadier_ALiVE_OPTRE_01";
                    };
                };

                class i_icolmaoptre_infantry_rifle_squad {
                    name = "Rifle Squad";
                    side = 2;
                    faction = "I_ColMA_OPTRE";
                    icon = "\A3\ui_f\data\map\markers\nato\n_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 2;
                        vehicle = "I_ColMA_Squad_Leader_ALiVE_OPTRE_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_ColMA_Team_Leader_ALiVE_OPTRE_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_ColMA_Team_Leader_ALiVE_OPTRE_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_ColMA_Rifleman_ALiVE_OPTRE_01";
                    };
                    class Unit4 {
                        position[] = {-10,-10,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_ColMA_Rifleman_ALiVE_OPTRE_01";
                    };
                    class Unit5 {
                        position[] = {15,-15,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_ColMA_Medic_ALiVE_OPTRE_01";
                    };
                    class Unit6 {
                        position[] = {-15,-15,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_ColMA_RTO_ALiVE_OPTRE_01";
                    };
                    class Unit7 {
                        position[] = {20,-20,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_IColMAOPTRE_Rifleman_AT_ALiVE_01";
                    };
                    class Unit8 {
                        position[] = {-20,-20,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_ColMA_Autorifleman_ALiVE_OPTRE_01";
                    };
                };

                class i_icolmaoptre_infantry_weapons_squad {
                    name = "Weapons Squad";
                    side = 2;
                    faction = "I_ColMA_OPTRE";
                    icon = "\A3\ui_f\data\map\markers\nato\n_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 2;
                        vehicle = "I_ColMA_Squad_Leader_ALiVE_OPTRE_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_ColMA_Team_Leader_ALiVE_OPTRE_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_ColMA_Team_Leader_ALiVE_OPTRE_01";
                    };
                    class Unit3 {
                        position[] = {-10,-10,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_ColMA_RTO_ALiVE_OPTRE_01";
                    };
                    class Unit4 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_ColMA_Medic_ALiVE_OPTRE_01";
                    };
                    class Unit5 {
                        position[] = {-5,-15,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_ColMA_Autorifleman_ALiVE_OPTRE_01";
                    };
                    class Unit6 {
                        position[] = {5,-15,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_ColMA_Autorifleman_ALiVE_OPTRE_01";
                    };
                    class Unit7 {
                        position[] = {-0,-20,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_IColMAOPTRE_Rifleman_AT_ALiVE_01";
                    };
                    class Unit8 {
                        position[] = {0,-20,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_IColMAOPTRE_Rifleman_AT_ALiVE_01";
                    };
                    class Unit9 {
                        position[] = {5,-25,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_ColMA_Grenadier_ALiVE_OPTRE_01";
                    };
                    class Unit10 {
                        position[] = {-5,-25,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_ColMA_Grenadier_ALiVE_OPTRE_01";
                    };
                };

            };

            class SpecOps {
                name = "Special Forces";

                class i_icolmaoptre_specops_strike_team {
                    name = "Strike Team";
                    side = 2;
                    faction = "I_ColMA_OPTRE";
                    icon = "\A3\ui_f\data\map\markers\nato\n_recon.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 2;
                        vehicle = "I_ColMA_Squad_Leader_ALiVE_OPTRE_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_ColMA_Grenadier_ALiVE_OPTRE_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_ColMA_Marksman_ALiVE_OPTRE_01";
                    };
                };

                class i_icolmaoptre_specops_sniper_team {
                    name = "Sniper Team";
                    side = 2;
                    faction = "I_ColMA_OPTRE";
                    icon = "\A3\ui_f\data\map\markers\nato\n_recon.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 2;
                        vehicle = "I_ColMA_Sniper_ALiVE_OPTRE_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_ColMA_Marksman_ALiVE_OPTRE_01";
                    };
                };

                class i_icolmaoptre_specops_fo_team {
                    name = "FO Team";
                    side = 2;
                    faction = "I_ColMA_OPTRE";
                    icon = "\A3\ui_f\data\map\markers\nato\n_recon.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 2;
                        vehicle = "I_ColMA_Marksman_ALiVE_OPTRE_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_ColMA_RTO_ALiVE_OPTRE_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_ColMA_Rifleman_ALiVE_OPTRE_01";
                    };
                };

            };

            class Motorized {
                name = "Motorized Infantry";

                class i_icolmaoptre_motorized_light_convoy {
                    name = "Light Convoy";
                    side = 2;
                    faction = "I_ColMA_OPTRE";
                    icon = "\A3\ui_f\data\map\markers\nato\n_motor_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 2;
                        vehicle = "I_IColMAOPTRE_ARV_13_Ferret_ALiVE_01";
                    };
                    class Unit1 {
                        position[] = {7,-10,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_IColMAOPTRE_ARV_13_Ferret_M247H_ALiVE_01";
                    };
                };

                class i_icolmaoptre_motorized_heavy_convoy {
                    name = "Heavy Convoy";
                    side = 2;
                    faction = "I_ColMA_OPTRE";
                    icon = "\A3\ui_f\data\map\markers\nato\n_motor_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 2;
                        vehicle = "I_IColMAOPTRE_ARV_13_Ferret_M247H_ALiVE_01";
                    };
                    class Unit1 {
                        position[] = {7,-10,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_IColMAOPTRE_ARV_13_Ferret_ALiVE_01";
                    };
                    class Unit2 {
                        position[] = {-7,-10,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_IColMAOPTRE_ARV_13_Ferret_MG460_AGL_ALiVE_01";
                    };
                };

            };

            class Motorized_MTP {
                name = "Motorized Infantry (MTP)";

            };

            class Support {
                name = "Support Infantry";

            };

            class Mechanized {
                name = "Mechanized Infantry";

                class i_icolmaoptre_mechanized_light_mechanized_convoy {
                    name = "Light Mechanized Convoy";
                    side = 2;
                    faction = "I_ColMA_OPTRE";
                    icon = "\A3\ui_f\data\map\markers\nato\n_mech_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 2;
                        vehicle = "I_IColMAOPTRE_FV_720_Odyniec_ALiVE_01";
                    };
                };

                class i_icolmaoptre_mechanized_heavy_mechanized_convoy {
                    name = "Heavy Mechanized Convoy";
                    side = 2;
                    faction = "I_ColMA_OPTRE";
                    icon = "\A3\ui_f\data\map\markers\nato\n_mech_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 2;
                        vehicle = "I_IColMAOPTRE_FV_720_Odyniec_ALiVE_01";
                    };
                    class Unit1 {
                        position[] = {7,-13,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_IColMAOPTRE_FV_720_Odyniec_ALiVE_01";
                    };
                };

            };

            class Armored {
                name = "Armor";

                class i_icolmaoptre_armored_light_armored_convoy {
                    name = "Light Armored Convoy";
                    side = 2;
                    faction = "I_ColMA_OPTRE";
                    icon = "\A3\ui_f\data\map\markers\nato\n_armor.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 2;
                        vehicle = "I_IColMAOPTRE_Wiesel_2MK20_ALiVE_01";
                    };
                    class Unit1 {
                        position[] = {5,-9,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_IColMAOPTRE_Wiesel_2ATGM_ALiVE_01";
                    };
                };

                class i_icolmaoptre_armored_heavy_armored_convoy {
                    name = "Heavy Armored Convoy";
                    side = 2;
                    faction = "I_ColMA_OPTRE";
                    icon = "\A3\ui_f\data\map\markers\nato\n_armor.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 2;
                        vehicle = "I_IColMAOPTRE_Wiesel_2MK20_ALiVE_01";
                    };
                    class Unit1 {
                        position[] = {5,-9,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_IColMAOPTRE_Wiesel_2ATGM_ALiVE_01";
                    };
                    class Unit2 {
                        position[] = {-5,-9,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_IColMAOPTRE_Wiesel_2ATGM_ALiVE_01";
                    };
                    class Unit3 {
                        position[] = {10,-13,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_IColMAOPTRE_Wiesel_2MK20_ALiVE_01";
                    };
                };

                class i_icolmaoptre_armored_aa_convoy {
                    name = "AA Convoy";
                    side = 2;
                    faction = "I_ColMA_OPTRE";
                    icon = "\A3\ui_f\data\map\markers\nato\n_armor.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 2;
                        vehicle = "I_IColMAOPTRE_Wiesel_2RFCV_ALiVE_01";
                    };
                    class Unit1 {
                        position[] = {5,-9,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_IColMAOPTRE_Wiesel_2AA_ALiVE_01";
                    };
                    class Unit2 {
                        position[] = {-5,-9,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_IColMAOPTRE_Wiesel_2AA_ALiVE_01";
                    };
                };

            };

            class Artillery {
                name = "Artillery";

                class i_icolmaoptre_artillery_light_artillery_battery {
                    name = "Light Artillery Battery";
                    side = 2;
                    faction = "I_ColMA_OPTRE";
                    icon = "\A3\ui_f\data\map\markers\nato\n_art.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 2;
                        vehicle = "I_IColMAOPTRE_Zamak_MRL_ALiVE_01";
                    };
                };

                class i_icolmaoptre_artillery_heavy_artillery_battery {
                    name = "Heavy Artillery Battery";
                    side = 2;
                    faction = "I_ColMA_OPTRE";
                    icon = "\A3\ui_f\data\map\markers\nato\n_art.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 2;
                        vehicle = "I_IColMAOPTRE_Zamak_MRL_ALiVE_01";
                    };
                    class Unit1 {
                        position[] = {5,-14,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_IColMAOPTRE_Zamak_MRL_ALiVE_01";
                    };
                    class Unit2 {
                        position[] = {-5,-14,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_IColMAOPTRE_Zamak_MRL_ALiVE_01";
                    };
                };

            };

            class Naval {
                name = "Naval";

            };

            class Air {
                name = "Air";

                class i_icolmaoptre_air_light_rotary_patrol {
                    name = "Light Rotary Patrol";
                    side = 2;
                    faction = "I_ColMA_OPTRE";
                    icon = "\A3\ui_f\data\map\markers\nato\n_air.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 2;
                        vehicle = "I_IColMAOPTRE_AW159_Wildcat_Unarmed_ALiVE_01";
                    };
                };

                class i_icolmaoptre_air_light_rotary_cas {
                    name = "Light Rotary CAS";
                    side = 2;
                    faction = "I_ColMA_OPTRE";
                    icon = "\A3\ui_f\data\map\markers\nato\n_air.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 2;
                        vehicle = "I_IColMAOPTRE_AW159_Wildcat_ALiVE_01";
                    };
                };

                class i_icolmaoptre_air_heavy_rotary_cas {
                    name = "Heavy Rotary CAS";
                    side = 2;
                    faction = "I_ColMA_OPTRE";
                    icon = "\A3\ui_f\data\map\markers\nato\n_air.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 2;
                        vehicle = "I_IColMAOPTRE_AW159_Wildcat_ALiVE_01";
                    };
                    class Unit1 {
                        position[] = {20,-23,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_IColMAOPTRE_AW159_Wildcat_ALiVE_01";
                    };
                };

                class i_icolmaoptre_air_light_fixed_cas {
                    name = "Light Fixed CAS";
                    side = 2;
                    faction = "I_ColMA_OPTRE";
                    icon = "\A3\ui_f\data\map\markers\nato\n_air.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 2;
                        vehicle = "I_IColMAOPTRE_L159_ALCA_ALiVE_01";
                    };
                };

                class i_icolmaoptre_air_heavy_fixed_cas {
                    name = "Heavy Fixed CAS";
                    side = 2;
                    faction = "I_ColMA_OPTRE";
                    icon = "\A3\ui_f\data\map\markers\nato\n_air.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 2;
                        vehicle = "I_IColMAOPTRE_L159_ALCA_ALiVE_01";
                    };
                    class Unit1 {
                        position[] = {15,-20,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_IColMAOPTRE_L159_ALCA_ALiVE_01";
                    };
                };

                class i_icolmaoptre_air_light_fixed_cap {
                    name = "Light Fixed CAP";
                    side = 2;
                    faction = "I_ColMA_OPTRE";
                    icon = "\A3\ui_f\data\map\markers\nato\n_air.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 2;
                        vehicle = "I_IColMAOPTRE_JAS_39_Griphen_ALiVE_01";
                    };
                };

                class i_icolmaoptre_air_heavy_fixed_cap {
                    name = "Heavy Fixed CAP";
                    side = 2;
                    faction = "I_ColMA_OPTRE";
                    icon = "\A3\ui_f\data\map\markers\nato\n_air.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 2;
                        vehicle = "I_IColMAOPTRE_JAS_39_Griphen_ALiVE_01";
                    };
                    class Unit1 {
                        position[] = {13,-26,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_IColMAOPTRE_JAS_39_Griphen_ALiVE_01";
                    };
                };

            };


        };

    };
};


class CBA_Extended_EventHandlers_base;

class CfgVehicles {

    class LM_OPCAN_CMA_Officer;
    class LM_OPCAN_CMA_Officer_OCimport_01 : LM_OPCAN_CMA_Officer { scope = 0; class EventHandlers; };
    class LM_OPCAN_CMA_Officer_OCimport_02 : LM_OPCAN_CMA_Officer_OCimport_01 { class EventHandlers; };

    class LM_OPCAN_CMA_SL;
    class LM_OPCAN_CMA_SL_OCimport_01 : LM_OPCAN_CMA_SL { scope = 0; class EventHandlers; };
    class LM_OPCAN_CMA_SL_OCimport_02 : LM_OPCAN_CMA_SL_OCimport_01 { class EventHandlers; };

    class LM_OPCAN_CMA_TL;
    class LM_OPCAN_CMA_TL_OCimport_01 : LM_OPCAN_CMA_TL { scope = 0; class EventHandlers; };
    class LM_OPCAN_CMA_TL_OCimport_02 : LM_OPCAN_CMA_TL_OCimport_01 { class EventHandlers; };

    class LM_OPCAN_CMA_Rifleman;
    class LM_OPCAN_CMA_Rifleman_OCimport_01 : LM_OPCAN_CMA_Rifleman { scope = 0; class EventHandlers; };
    class LM_OPCAN_CMA_Rifleman_OCimport_02 : LM_OPCAN_CMA_Rifleman_OCimport_01 { class EventHandlers; };

    class LM_OPCAN_CMA_GL;
    class LM_OPCAN_CMA_GL_OCimport_01 : LM_OPCAN_CMA_GL { scope = 0; class EventHandlers; };
    class LM_OPCAN_CMA_GL_OCimport_02 : LM_OPCAN_CMA_GL_OCimport_01 { class EventHandlers; };

    class LM_OPCAN_CMA_Medic;
    class LM_OPCAN_CMA_Medic_OCimport_01 : LM_OPCAN_CMA_Medic { scope = 0; class EventHandlers; };
    class LM_OPCAN_CMA_Medic_OCimport_02 : LM_OPCAN_CMA_Medic_OCimport_01 { class EventHandlers; };

    class LM_OPCAN_CMA_Marksman;
    class LM_OPCAN_CMA_Marksman_OCimport_01 : LM_OPCAN_CMA_Marksman { scope = 0; class EventHandlers; };
    class LM_OPCAN_CMA_Marksman_OCimport_02 : LM_OPCAN_CMA_Marksman_OCimport_01 { class EventHandlers; };

    class LM_OPCAN_CMA_RTO;
    class LM_OPCAN_CMA_RTO_OCimport_01 : LM_OPCAN_CMA_RTO { scope = 0; class EventHandlers; };
    class LM_OPCAN_CMA_RTO_OCimport_02 : LM_OPCAN_CMA_RTO_OCimport_01 { class EventHandlers; };

    class LM_OPCAN_CMA_Sniper;
    class LM_OPCAN_CMA_Sniper_OCimport_01 : LM_OPCAN_CMA_Sniper { scope = 0; class EventHandlers; };
    class LM_OPCAN_CMA_Sniper_OCimport_02 : LM_OPCAN_CMA_Sniper_OCimport_01 { class EventHandlers; };

    class LM_OPCAN_CMA_AutoRifleman;
    class LM_OPCAN_CMA_AutoRifleman_OCimport_01 : LM_OPCAN_CMA_AutoRifleman { scope = 0; class EventHandlers; };
    class LM_OPCAN_CMA_AutoRifleman_OCimport_02 : LM_OPCAN_CMA_AutoRifleman_OCimport_01 { class EventHandlers; };

    class LM_OPCAN_CMA_Rifleman_AT;
    class LM_OPCAN_CMA_Rifleman_AT_OCimport_01 : LM_OPCAN_CMA_Rifleman_AT { scope = 0; class EventHandlers; };
    class LM_OPCAN_CMA_Rifleman_AT_OCimport_02 : LM_OPCAN_CMA_Rifleman_AT_OCimport_01 { class EventHandlers; };

    class LM_OPCAN_CMA_Breacher;
    class LM_OPCAN_CMA_Breacher_OCimport_01 : LM_OPCAN_CMA_Breacher { scope = 0; class EventHandlers; };
    class LM_OPCAN_CMA_Breacher_OCimport_02 : LM_OPCAN_CMA_Breacher_OCimport_01 { class EventHandlers; };

    class LM_OPCAN_CMA_Engineer;
    class LM_OPCAN_CMA_Engineer_OCimport_01 : LM_OPCAN_CMA_Engineer { scope = 0; class EventHandlers; };
    class LM_OPCAN_CMA_Engineer_OCimport_02 : LM_OPCAN_CMA_Engineer_OCimport_01 { class EventHandlers; };

    class LM_OPCAN_ARV_CMA_WDL;
    class LM_OPCAN_ARV_CMA_WDL_OCimport_01 : LM_OPCAN_ARV_CMA_WDL { scope = 0; class EventHandlers; class Turrets; };
    class LM_OPCAN_ARV_CMA_WDL_OCimport_02 : LM_OPCAN_ARV_CMA_WDL_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class CommanderTurret;
        };
    };

    class LM_OPCAN_CMA_Crewman;
    class LM_OPCAN_CMA_Crewman_OCimport_01 : LM_OPCAN_CMA_Crewman { scope = 0; class EventHandlers; };
    class LM_OPCAN_CMA_Crewman_OCimport_02 : LM_OPCAN_CMA_Crewman_OCimport_01 { class EventHandlers; };

    class LM_OPCAN_ARV_CMA_HMG_WDL;
    class LM_OPCAN_ARV_CMA_HMG_WDL_OCimport_01 : LM_OPCAN_ARV_CMA_HMG_WDL { scope = 0; class EventHandlers; class Turrets; };
    class LM_OPCAN_ARV_CMA_HMG_WDL_OCimport_02 : LM_OPCAN_ARV_CMA_HMG_WDL_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class MainTurret;
            class CommanderTurret;
        };
    };

    class I_Plane_Fighter_03_dynamicLoadout_F;
    class I_Plane_Fighter_03_dynamicLoadout_F_OCimport_01 : I_Plane_Fighter_03_dynamicLoadout_F { scope = 0; class EventHandlers; };
    class I_Plane_Fighter_03_dynamicLoadout_F_OCimport_02 : I_Plane_Fighter_03_dynamicLoadout_F_OCimport_01 { scope = 0; class EventHandlers; };

    class I_Heli_light_03_dynamicLoadout_F;
    class I_Heli_light_03_dynamicLoadout_F_OCimport_01 : I_Heli_light_03_dynamicLoadout_F { scope = 0; class EventHandlers; class Turrets; };
    class I_Heli_light_03_dynamicLoadout_F_OCimport_02 : I_Heli_light_03_dynamicLoadout_F_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class MainTurret;
            class CargoTurret_01;
            class CargoTurret_02;
        };
    };

    class I_Heli_light_03_unarmed_F;
    class I_Heli_light_03_unarmed_F_OCimport_01 : I_Heli_light_03_unarmed_F { scope = 0; class EventHandlers; class Turrets; };
    class I_Heli_light_03_unarmed_F_OCimport_02 : I_Heli_light_03_unarmed_F_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class MainTurret;
        };
    };

    class I_E_APC_tracked_03_cannon_F;
    class I_E_APC_tracked_03_cannon_F_OCimport_01 : I_E_APC_tracked_03_cannon_F { scope = 0; class EventHandlers; class Turrets; };
    class I_E_APC_tracked_03_cannon_F_OCimport_02 : I_E_APC_tracked_03_cannon_F_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class MainTurret;
        };
    };

    class I_E_Truck_02_MRL_F;
    class I_E_Truck_02_MRL_F_OCimport_01 : I_E_Truck_02_MRL_F { scope = 0; class EventHandlers; class Turrets; };
    class I_E_Truck_02_MRL_F_OCimport_02 : I_E_Truck_02_MRL_F_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class MainTurret;
        };
    };

    class I_LT_01_AA_F;
    class I_LT_01_AA_F_OCimport_01 : I_LT_01_AA_F { scope = 0; class EventHandlers; class Turrets; };
    class I_LT_01_AA_F_OCimport_02 : I_LT_01_AA_F_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class MainTurret;
        };
    };

    class I_LT_01_AT_F;
    class I_LT_01_AT_F_OCimport_01 : I_LT_01_AT_F { scope = 0; class EventHandlers; class Turrets; };
    class I_LT_01_AT_F_OCimport_02 : I_LT_01_AT_F_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class MainTurret;
        };
    };

    class I_LT_01_scout_F;
    class I_LT_01_scout_F_OCimport_01 : I_LT_01_scout_F { scope = 0; class EventHandlers; class Turrets; };
    class I_LT_01_scout_F_OCimport_02 : I_LT_01_scout_F_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class MainTurret;
        };
    };

    class I_LT_01_cannon_F;
    class I_LT_01_cannon_F_OCimport_01 : I_LT_01_cannon_F { scope = 0; class EventHandlers; class Turrets; };
    class I_LT_01_cannon_F_OCimport_02 : I_LT_01_cannon_F_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class MainTurret;
        };
    };

    class I_Plane_Fighter_04_F;
    class I_Plane_Fighter_04_F_OCimport_01 : I_Plane_Fighter_04_F { scope = 0; class EventHandlers; };
    class I_Plane_Fighter_04_F_OCimport_02 : I_Plane_Fighter_04_F_OCimport_01 { scope = 0; class EventHandlers; };

    class LM_OPCAN_ARV_CMA_GMG_WDL;
    class LM_OPCAN_ARV_CMA_GMG_WDL_OCimport_01 : LM_OPCAN_ARV_CMA_GMG_WDL { scope = 0; class EventHandlers; class Turrets; };
    class LM_OPCAN_ARV_CMA_GMG_WDL_OCimport_02 : LM_OPCAN_ARV_CMA_GMG_WDL_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class MainTurret;
            class CommanderTurret;
        };
    };


    class I_ColMA_Officer_ALiVE_OPTRE_01 : LM_OPCAN_CMA_Officer_OCimport_02 {
        author = "Capt. Houlston, L";
        scope = 2;
        scopeCurator = 2;
        displayName = "Officer [ALiVE]";
        side = 2;
        faction = "I_ColMA_OPTRE";

        identityTypes[] = {"Head_NATO","LanguageENG_F","NoGlassesÃ¯Â»Â¿"};

        uniformClass = "LM_OPCAN_CMA_uni_Base";

        linkedItems[] = {"LM_OPCAN_IHTV_VEST","H_Beret_blk","ItemMap","ItemRadio","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"LM_OPCAN_IHTV_VEST","H_Beret_blk","ItemMap","ItemRadio","ItemCompass","ItemWatch"};

        weapons[] = {"OPTRE_MA32","OPTRE_M6G_SF"};
        respawnWeapons[] = {"OPTRE_MA32","OPTRE_M6G_SF"};

        magazines[] = {"OPTRE_32Rnd_762x51_Mag","OPTRE_8Rnd_127x40_Mag","OPTRE_32Rnd_762x51_Mag","OPTRE_8Rnd_127x40_Mag"};
        respawnMagazines[] = {"OPTRE_32Rnd_762x51_Mag","OPTRE_8Rnd_127x40_Mag","OPTRE_32Rnd_762x51_Mag","OPTRE_8Rnd_127x40_Mag"};

        ALiVE_orbatCreator_loadout[] = {{"OPTRE_MA32","","","",{"OPTRE_32Rnd_762x51_Mag",32},{},""},{},{"OPTRE_M6G_SF","","OPTRE_M6G_Flashlight","OPTRE_M6G_Scope",{"OPTRE_8Rnd_127x40_Mag",8},{},""},{"LM_OPCAN_CMA_uni_Base",{{"FirstAidKit",1},{"ACE_EarPlugs",1},{"OPTRE_32Rnd_762x51_Mag",2,32},{"Chemlight_green",2,1}}},{"LM_OPCAN_IHTV_VEST",{{"OPTRE_32Rnd_762x51_Mag",7,32},{"OPTRE_8Rnd_127x40_Mag",2,8},{"HandGrenade",2,1}}},{},"H_Beret_blk","LM_OPCAN_Shemagh",{},{"ItemMap","","ItemRadio","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class I_ColMA_Squad_Leader_ALiVE_OPTRE_01 : LM_OPCAN_CMA_SL_OCimport_02 {
        author = "Capt. Houlston, L";
        scope = 2;
        scopeCurator = 2;
        displayName = "Squad Leader [ALiVE]";
        side = 2;
        faction = "I_ColMA_OPTRE";

        identityTypes[] = {"Head_NATO","LanguageENG_F","NoGlassesÃ¯Â»Â¿"};

        uniformClass = "LM_OPCAN_CMA_uni_Base";

        linkedItems[] = {"LM_OPCAN_IHTV_VEST","LM_OPCAN_CMA_CH250","ItemMap","ItemRadio","ItemCompass","ItemWatch","NVGoggles_INDEP"};
        respawnlinkedItems[] = {"LM_OPCAN_IHTV_VEST","LM_OPCAN_CMA_CH250","ItemMap","ItemRadio","ItemCompass","ItemWatch","NVGoggles_INDEP"};

        weapons[] = {"OPTRE_MA32","OPTRE_M6G_SF"};
        respawnWeapons[] = {"OPTRE_MA32","OPTRE_M6G_SF"};

        magazines[] = {"OPTRE_32Rnd_762x51_Mag","OPTRE_8Rnd_127x40_Mag","OPTRE_32Rnd_762x51_Mag","OPTRE_8Rnd_127x40_Mag"};
        respawnMagazines[] = {"OPTRE_32Rnd_762x51_Mag","OPTRE_8Rnd_127x40_Mag","OPTRE_32Rnd_762x51_Mag","OPTRE_8Rnd_127x40_Mag"};

        backpack = "OPTRE_UNSC_Rucksack_Heavy";

        ALiVE_orbatCreator_loadout[] = {{"OPTRE_MA32","","","OPTRE_M7_Sight",{"OPTRE_32Rnd_762x51_Mag",32},{},""},{},{"OPTRE_M6G_SF","","OPTRE_M6G_Flashlight","OPTRE_M6G_Scope",{"OPTRE_8Rnd_127x40_Mag",8},{},""},{"LM_OPCAN_CMA_uni_Base",{{"FirstAidKit",1},{"ACE_EarPlugs",1},{"OPTRE_32Rnd_762x51_Mag",2,32},{"Chemlight_green",2,1}}},{"LM_OPCAN_IHTV_VEST",{{"OPTRE_32Rnd_762x51_Mag",7,32},{"OPTRE_8Rnd_127x40_Mag",2,8},{"HandGrenade",2,1}}},{"OPTRE_UNSC_Rucksack_Heavy",{}},"LM_OPCAN_CMA_CH250","LM_OPCAN_UP_Shemagh",{},{"ItemMap","","ItemRadio","ItemCompass","ItemWatch","NVGoggles_INDEP"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class I_ColMA_Team_Leader_ALiVE_OPTRE_01 : LM_OPCAN_CMA_TL_OCimport_02 {
        author = "Capt. Houlston, L";
        scope = 2;
        scopeCurator = 2;
        displayName = "Team Leader [ALiVE]";
        side = 2;
        faction = "I_ColMA_OPTRE";

        identityTypes[] = {"Head_NATO","LanguageENG_F","NoGlassesÃ¯Â»Â¿"};

        uniformClass = "LM_OPCAN_CMA_uni_Base";

        linkedItems[] = {"LM_OPCAN_IHTV_VEST","LM_OPCAN_CMA_CH250","ItemMap","ItemRadio","ItemCompass","ItemWatch","NVGoggles_INDEP"};
        respawnlinkedItems[] = {"LM_OPCAN_IHTV_VEST","LM_OPCAN_CMA_CH250","ItemMap","ItemRadio","ItemCompass","ItemWatch","NVGoggles_INDEP"};

        weapons[] = {"OPTRE_MA32GL"};
        respawnWeapons[] = {"OPTRE_MA32GL"};

        magazines[] = {"OPTRE_32Rnd_762x51_Mag","1Rnd_HE_Grenade_shell","OPTRE_32Rnd_762x51_Mag","1Rnd_HE_Grenade_shell"};
        respawnMagazines[] = {"OPTRE_32Rnd_762x51_Mag","1Rnd_HE_Grenade_shell","OPTRE_32Rnd_762x51_Mag","1Rnd_HE_Grenade_shell"};

        backpack = "OPTRE_UNSC_Rucksack";

        ALiVE_orbatCreator_loadout[] = {{"OPTRE_MA32GL","","","",{"OPTRE_32Rnd_762x51_Mag",32},{"1Rnd_HE_Grenade_shell",1},""},{},{},{"LM_OPCAN_CMA_uni_Base",{{"FirstAidKit",1},{"ACE_EarPlugs",1},{"OPTRE_32Rnd_762x51_Mag",2,32},{"Chemlight_green",1,1}}},{"LM_OPCAN_IHTV_VEST",{{"OPTRE_32Rnd_762x51_Mag",7,32},{"1Rnd_HE_Grenade_shell",4,1},{"Chemlight_green",1,1},{"HandGrenade",2,1}}},{"OPTRE_UNSC_Rucksack",{}},"LM_OPCAN_CMA_CH250","LM_OPCAN_Shemagh",{},{"ItemMap","","ItemRadio","ItemCompass","ItemWatch","NVGoggles_INDEP"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class I_ColMA_Rifleman_ALiVE_OPTRE_01 : LM_OPCAN_CMA_Rifleman_OCimport_02 {
        author = "Capt. Houlston, L";
        scope = 2;
        scopeCurator = 2;
        displayName = "Rifleman [ALiVE]";
        side = 2;
        faction = "I_ColMA_OPTRE";

        identityTypes[] = {"Head_NATO","LanguageENG_F","NoGlassesÃ¯Â»Â¿"};

        uniformClass = "LM_OPCAN_CMA_uni_Base";

        linkedItems[] = {"LM_OPCAN_IHTV_VEST","LM_OPCAN_CMA_CH250","ItemMap","ItemRadio","ItemCompass","ItemWatch","NVGoggles_INDEP"};
        respawnlinkedItems[] = {"LM_OPCAN_IHTV_VEST","LM_OPCAN_CMA_CH250","ItemMap","ItemRadio","ItemCompass","ItemWatch","NVGoggles_INDEP"};

        weapons[] = {"OPTRE_MA32","OPTRE_M6G_SF"};
        respawnWeapons[] = {"OPTRE_MA32","OPTRE_M6G_SF"};

        magazines[] = {"OPTRE_32Rnd_762x51_Mag","OPTRE_8Rnd_127x40_Mag","OPTRE_32Rnd_762x51_Mag","OPTRE_8Rnd_127x40_Mag"};
        respawnMagazines[] = {"OPTRE_32Rnd_762x51_Mag","OPTRE_8Rnd_127x40_Mag","OPTRE_32Rnd_762x51_Mag","OPTRE_8Rnd_127x40_Mag"};

        ALiVE_orbatCreator_loadout[] = {{"OPTRE_MA32","","","",{"OPTRE_32Rnd_762x51_Mag",32},{},""},{},{"OPTRE_M6G_SF","","OPTRE_M6G_Flashlight","OPTRE_M6G_Scope",{"OPTRE_8Rnd_127x40_Mag",8},{},""},{"LM_OPCAN_CMA_uni_Base",{{"FirstAidKit",1},{"ACE_EarPlugs",1},{"OPTRE_32Rnd_762x51_Mag",2,32},{"Chemlight_green",2,1}}},{"LM_OPCAN_IHTV_VEST",{{"OPTRE_32Rnd_762x51_Mag",7,32},{"OPTRE_8Rnd_127x40_Mag",2,8},{"HandGrenade",2,1}}},{},"LM_OPCAN_CMA_CH250","LM_OPCAN_Shemagh",{},{"ItemMap","","ItemRadio","ItemCompass","ItemWatch","NVGoggles_INDEP"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class I_ColMA_Grenadier_ALiVE_OPTRE_01 : LM_OPCAN_CMA_GL_OCimport_02 {
        author = "Capt. Houlston, L";
        scope = 2;
        scopeCurator = 2;
        displayName = "Grenadier [ALiVE]";
        side = 2;
        faction = "I_ColMA_OPTRE";

        identityTypes[] = {"Head_NATO","LanguageENG_F","NoGlassesÃ¯Â»Â¿"};

        uniformClass = "LM_OPCAN_CMA_uni_Base";

        linkedItems[] = {"LM_OPCAN_IHTV_VEST","LM_OPCAN_CMA_CH250","ItemMap","ItemRadio","ItemCompass","ItemWatch","NVGoggles_INDEP"};
        respawnlinkedItems[] = {"LM_OPCAN_IHTV_VEST","LM_OPCAN_CMA_CH250","ItemMap","ItemRadio","ItemCompass","ItemWatch","NVGoggles_INDEP"};

        weapons[] = {"OPTRE_MA32GL"};
        respawnWeapons[] = {"OPTRE_MA32GL"};

        magazines[] = {"OPTRE_32Rnd_762x51_Mag","1Rnd_HE_Grenade_shell","OPTRE_32Rnd_762x51_Mag","1Rnd_HE_Grenade_shell"};
        respawnMagazines[] = {"OPTRE_32Rnd_762x51_Mag","1Rnd_HE_Grenade_shell","OPTRE_32Rnd_762x51_Mag","1Rnd_HE_Grenade_shell"};

        ALiVE_orbatCreator_loadout[] = {{"OPTRE_MA32GL","","","",{"OPTRE_32Rnd_762x51_Mag",32},{"1Rnd_HE_Grenade_shell",1},""},{},{},{"LM_OPCAN_CMA_uni_Base",{{"FirstAidKit",1},{"ACE_EarPlugs",1},{"OPTRE_32Rnd_762x51_Mag",2,32},{"Chemlight_green",1,1}}},{"LM_OPCAN_IHTV_VEST",{{"OPTRE_32Rnd_762x51_Mag",7,32},{"1Rnd_HE_Grenade_shell",4,1},{"Chemlight_green",1,1},{"HandGrenade",2,1}}},{},"LM_OPCAN_CMA_CH250","LM_OPCAN_UP_Shemagh",{},{"ItemMap","","ItemRadio","ItemCompass","ItemWatch","NVGoggles_INDEP"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class I_ColMA_Medic_ALiVE_OPTRE_01 : LM_OPCAN_CMA_Medic_OCimport_02 {
        author = "Capt. Houlston, L";
        scope = 2;
        scopeCurator = 2;
        displayName = "Medic [ALiVE]";
        side = 2;
        faction = "I_ColMA_OPTRE";

        identityTypes[] = {"Head_NATO","LanguageENG_F","NoGlassesÃ¯Â»Â¿"};

        uniformClass = "LM_OPCAN_CMA_uni_Base";

        linkedItems[] = {"LM_OPCAN_IHTV_VEST","LM_OPCAN_CMA_CH250","ItemMap","ItemRadio","ItemCompass","ItemWatch","NVGoggles_INDEP"};
        respawnlinkedItems[] = {"LM_OPCAN_IHTV_VEST","LM_OPCAN_CMA_CH250","ItemMap","ItemRadio","ItemCompass","ItemWatch","NVGoggles_INDEP"};

        weapons[] = {"OPTRE_M7","OPTRE_M6G_SF"};
        respawnWeapons[] = {"OPTRE_M7","OPTRE_M6G_SF"};

        magazines[] = {"OPTRE_48Rnd_5x23mm_FMJ_Mag","OPTRE_8Rnd_127x40_Mag","OPTRE_48Rnd_5x23mm_FMJ_Mag","OPTRE_8Rnd_127x40_Mag"};
        respawnMagazines[] = {"OPTRE_48Rnd_5x23mm_FMJ_Mag","OPTRE_8Rnd_127x40_Mag","OPTRE_48Rnd_5x23mm_FMJ_Mag","OPTRE_8Rnd_127x40_Mag"};

        backpack = "OPTRE_UNSC_Rucksack_Medic_Filled";

        ALiVE_orbatCreator_loadout[] = {{"OPTRE_M7","","","",{"OPTRE_48Rnd_5x23mm_FMJ_Mag",48},{},""},{},{"OPTRE_M6G_SF","","OPTRE_M6G_Flashlight","OPTRE_M6G_Scope",{"OPTRE_8Rnd_127x40_Mag",8},{},""},{"LM_OPCAN_CMA_uni_Base",{{"FirstAidKit",1},{"OPTRE_48Rnd_5x23mm_FMJ_Mag",5,48}}},{"LM_OPCAN_IHTV_VEST",{{"OPTRE_48Rnd_5x23mm_FMJ_Mag",4,48},{"OPTRE_8Rnd_127x40_Mag",2,8},{"Chemlight_green",2,1},{"HandGrenade",2,1}}},{"OPTRE_UNSC_Rucksack_Medic_Filled",{{"OPTRE_Biofoam",12},{"OPTRE_MedKit",2},{"ACE_splint",10},{"ACE_tourniquet",4}}},"LM_OPCAN_CMA_CH250","LM_OPCAN_UP_Shemagh",{},{"ItemMap","","ItemRadio","ItemCompass","ItemWatch","NVGoggles_INDEP"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class I_ColMA_Marksman_ALiVE_OPTRE_01 : LM_OPCAN_CMA_Marksman_OCimport_02 {
        author = "Capt. Houlston, L";
        scope = 2;
        scopeCurator = 2;
        displayName = "Marksman [ALiVE]";
        side = 2;
        faction = "I_ColMA_OPTRE";

        identityTypes[] = {"Head_NATO","LanguageENG_F","NoGlassesÃ¯Â»Â¿"};

        uniformClass = "LM_OPCAN_CMA_uni_Base";

        linkedItems[] = {"LM_OPCAN_IHTV_VEST","LM_OPCAN_CMA_CH250","ItemMap","ItemRadio","ItemCompass","ItemWatch","NVGoggles_INDEP"};
        respawnlinkedItems[] = {"LM_OPCAN_IHTV_VEST","LM_OPCAN_CMA_CH250","ItemMap","ItemRadio","ItemCompass","ItemWatch","NVGoggles_INDEP"};

        weapons[] = {"OPTRE_M295_BMR","OPTRE_M6G"};
        respawnWeapons[] = {"OPTRE_M295_BMR","OPTRE_M6G"};

        magazines[] = {"OPTRE_15Rnd_762x51_Mag","OPTRE_8Rnd_127x40_Mag","OPTRE_15Rnd_762x51_Mag","OPTRE_8Rnd_127x40_Mag"};
        respawnMagazines[] = {"OPTRE_15Rnd_762x51_Mag","OPTRE_8Rnd_127x40_Mag","OPTRE_15Rnd_762x51_Mag","OPTRE_8Rnd_127x40_Mag"};

        ALiVE_orbatCreator_loadout[] = {{"OPTRE_M295_BMR","","","",{"OPTRE_15Rnd_762x51_Mag",15},{},""},{},{"OPTRE_M6G","","","",{"OPTRE_8Rnd_127x40_Mag",8},{},""},{"LM_OPCAN_CMA_uni_Base",{{"FirstAidKit",1},{"ACE_EarPlugs",1},{"OPTRE_15Rnd_762x51_Mag",2,15},{"Chemlight_green",2,1}}},{"LM_OPCAN_IHTV_VEST",{{"OPTRE_15Rnd_762x51_Mag",7,15},{"OPTRE_8Rnd_127x40_Mag",2,8}}},{},"LM_OPCAN_CMA_CH250","LM_OPCAN_UP_Shemagh",{},{"ItemMap","","ItemRadio","ItemCompass","ItemWatch","NVGoggles_INDEP"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class I_ColMA_RTO_ALiVE_OPTRE_01 : LM_OPCAN_CMA_RTO_OCimport_02 {
        author = "Capt. Houlston, L";
        scope = 2;
        scopeCurator = 2;
        displayName = "RTO [ALiVE]";
        side = 2;
        faction = "I_ColMA_OPTRE";

        identityTypes[] = {"Head_NATO","LanguageENG_F","NoGlassesÃ¯Â»Â¿"};

        uniformClass = "LM_OPCAN_CMA_uni_Base";

        linkedItems[] = {"LM_OPCAN_IHTV_VEST","LM_OPCAN_CMA_CH250","ItemMap","ItemRadio","ItemCompass","ItemWatch","NVGoggles_INDEP"};
        respawnlinkedItems[] = {"LM_OPCAN_IHTV_VEST","LM_OPCAN_CMA_CH250","ItemMap","ItemRadio","ItemCompass","ItemWatch","NVGoggles_INDEP"};

        weapons[] = {"OPTRE_M7","OPTRE_M6G_SF"};
        respawnWeapons[] = {"OPTRE_M7","OPTRE_M6G_SF"};

        magazines[] = {"OPTRE_48Rnd_5x23mm_FMJ_Mag","OPTRE_8Rnd_127x40_Mag","OPTRE_48Rnd_5x23mm_FMJ_Mag","OPTRE_8Rnd_127x40_Mag"};
        respawnMagazines[] = {"OPTRE_48Rnd_5x23mm_FMJ_Mag","OPTRE_8Rnd_127x40_Mag","OPTRE_48Rnd_5x23mm_FMJ_Mag","OPTRE_8Rnd_127x40_Mag"};

        backpack = "OPTRE_ANPRC_521_Green";

        ALiVE_orbatCreator_loadout[] = {{"OPTRE_M7","","","",{"OPTRE_48Rnd_5x23mm_FMJ_Mag",48},{},""},{},{"OPTRE_M6G_SF","","OPTRE_M6G_Flashlight","OPTRE_M6G_Scope",{"OPTRE_8Rnd_127x40_Mag",8},{},""},{"LM_OPCAN_CMA_uni_Base",{{"FirstAidKit",1},{"OPTRE_48Rnd_5x23mm_FMJ_Mag",5,48}}},{"LM_OPCAN_IHTV_VEST",{{"OPTRE_48Rnd_5x23mm_FMJ_Mag",4,48},{"OPTRE_8Rnd_127x40_Mag",2,8},{"Chemlight_green",2,1},{"HandGrenade",2,1}}},{"OPTRE_ANPRC_521_Green",{}},"LM_OPCAN_CMA_CH250","LM_OPCAN_Shemagh",{},{"ItemMap","","ItemRadio","ItemCompass","ItemWatch","NVGoggles_INDEP"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class I_ColMA_Sniper_ALiVE_OPTRE_01 : LM_OPCAN_CMA_Sniper_OCimport_02 {
        author = "Capt. Houlston, L";
        scope = 2;
        scopeCurator = 2;
        displayName = "Sniper [ALiVE]";
        side = 2;
        faction = "I_ColMA_OPTRE";

        identityTypes[] = {"Head_NATO","LanguageENG_F","NoGlassesÃ¯Â»Â¿"};

        uniformClass = "LM_OPCAN_CMA_uni_Base";

        linkedItems[] = {"LM_OPCAN_IHTV_VEST","LM_OPCAN_CMA_CH250","ItemMap","ItemRadio","ItemCompass","ItemWatch","NVGoggles_INDEP"};
        respawnlinkedItems[] = {"LM_OPCAN_IHTV_VEST","LM_OPCAN_CMA_CH250","ItemMap","ItemRadio","ItemCompass","ItemWatch","NVGoggles_INDEP"};

        weapons[] = {"OPTRE_SRS99C_SC_LS","OPTRE_M6G_SF"};
        respawnWeapons[] = {"OPTRE_SRS99C_SC_LS","OPTRE_M6G_SF"};

        magazines[] = {"OPTRE_4Rnd_145x114_APFSDS_Mag","OPTRE_8Rnd_127x40_Mag","OPTRE_4Rnd_145x114_APFSDS_Mag","OPTRE_8Rnd_127x40_Mag"};
        respawnMagazines[] = {"OPTRE_4Rnd_145x114_APFSDS_Mag","OPTRE_8Rnd_127x40_Mag","OPTRE_4Rnd_145x114_APFSDS_Mag","OPTRE_8Rnd_127x40_Mag"};

        ALiVE_orbatCreator_loadout[] = {{"OPTRE_SRS99C_SC_LS","","","OPTRE_SRS99C_Scope",{"OPTRE_4Rnd_145x114_APFSDS_Mag",4},{},""},{},{"OPTRE_M6G_SF","","OPTRE_M6G_Flashlight","OPTRE_M6G_Scope",{"OPTRE_8Rnd_127x40_Mag",8},{},""},{"LM_OPCAN_CMA_uni_Base",{{"FirstAidKit",1},{"ACE_EarPlugs",1},{"OPTRE_4Rnd_145x114_APFSDS_Mag",1,4},{"Chemlight_green",2,1}}},{"LM_OPCAN_IHTV_VEST",{{"OPTRE_4Rnd_145x114_APFSDS_Mag",8,4},{"OPTRE_8Rnd_127x40_Mag",2,8},{"HandGrenade",2,1}}},{},"LM_OPCAN_CMA_CH250","LM_OPCAN_UP_Shemagheye",{},{"ItemMap","","ItemRadio","ItemCompass","ItemWatch","NVGoggles_INDEP"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class I_ColMA_Autorifleman_ALiVE_OPTRE_01 : LM_OPCAN_CMA_AutoRifleman_OCimport_02 {
        author = "Capt. Houlston, L";
        scope = 2;
        scopeCurator = 2;
        displayName = "Autorifleman [ALiVE]";
        side = 2;
        faction = "I_ColMA_OPTRE";

        identityTypes[] = {"Head_NATO","LanguageENG_F","NoGlassesÃ¯Â»Â¿"};

        uniformClass = "LM_OPCAN_CMA_uni_Base";

        linkedItems[] = {"LM_OPCAN_IHTV_VEST","LM_OPCAN_CMA_CH250","ItemMap","ItemRadio","ItemCompass","ItemWatch","NVGoggles_INDEP"};
        respawnlinkedItems[] = {"LM_OPCAN_IHTV_VEST","LM_OPCAN_CMA_CH250","ItemMap","ItemRadio","ItemCompass","ItemWatch","NVGoggles_INDEP"};

        weapons[] = {"OPTRE_M73_AC","OPTRE_M6G_SF"};
        respawnWeapons[] = {"OPTRE_M73_AC","OPTRE_M6G_SF"};

        magazines[] = {"OPTRE_200Rnd_95x40_Box","OPTRE_8Rnd_127x40_Mag","OPTRE_200Rnd_95x40_Box","OPTRE_8Rnd_127x40_Mag"};
        respawnMagazines[] = {"OPTRE_200Rnd_95x40_Box","OPTRE_8Rnd_127x40_Mag","OPTRE_200Rnd_95x40_Box","OPTRE_8Rnd_127x40_Mag"};

        backpack = "OPTRE_UNSC_Rucksack_Heavy";

        ALiVE_orbatCreator_loadout[] = {{"OPTRE_M73_AC","","","OPTRE_M73_SmartLink",{"OPTRE_200Rnd_95x40_Box",200},{},"bipod_01_F_blk"},{},{"OPTRE_M6G_SF","","OPTRE_M6G_Flashlight","OPTRE_M6G_Scope",{"OPTRE_8Rnd_127x40_Mag",8},{},""},{"LM_OPCAN_CMA_uni_Base",{{"FirstAidKit",1},{"ACE_EarPlugs",1},{"OPTRE_8Rnd_127x40_Mag",2,8},{"Chemlight_green",2,1}}},{"LM_OPCAN_IHTV_VEST",{{"OPTRE_200Rnd_95x40_Box",2,200},{"HandGrenade",2,1}}},{"OPTRE_UNSC_Rucksack_Heavy",{}},"LM_OPCAN_CMA_CH250","LM_OPCAN_UP_Shemagh",{},{"ItemMap","","ItemRadio","ItemCompass","ItemWatch","NVGoggles_INDEP"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class I_IColMAOPTRE_Rifleman_AT_ALiVE_01 : LM_OPCAN_CMA_Rifleman_AT_OCimport_02 {
        author = "Capt. Houlston, L";
        scope = 2;
        scopeCurator = 2;
        displayName = "Rifleman [AT] [ALiVE]";
        side = 2;
        faction = "I_ColMA_OPTRE";

        identityTypes[] = {"Head_NATO","LanguageENG_F","NoGlassesÃ¯Â»Â¿"};

        uniformClass = "LM_OPCAN_CMA_uni_Base";

        linkedItems[] = {"LM_OPCAN_IHTV_VEST","LM_OPCAN_CMA_CH250","ItemMap","ItemRadio","ItemCompass","ItemWatch","NVGoggles_INDEP"};
        respawnlinkedItems[] = {"LM_OPCAN_IHTV_VEST","LM_OPCAN_CMA_CH250","ItemMap","ItemRadio","ItemCompass","ItemWatch","NVGoggles_INDEP"};

        weapons[] = {"OPTRE_MA32","OPTRE_M41_SSR"};
        respawnWeapons[] = {"OPTRE_MA32","OPTRE_M41_SSR"};

        magazines[] = {"OPTRE_32Rnd_762x51_Mag","OPTRE_M41_Twin_HEAT","OPTRE_32Rnd_762x51_Mag"};
        respawnMagazines[] = {"OPTRE_32Rnd_762x51_Mag","OPTRE_M41_Twin_HEAT","OPTRE_32Rnd_762x51_Mag"};

        backpack = "OPTRE_UNSC_Rucksack_M41";

        ALiVE_orbatCreator_loadout[] = {{"OPTRE_MA32","","","",{"OPTRE_32Rnd_762x51_Mag",32},{},""},{"OPTRE_M41_SSR","","","",{"OPTRE_M41_Twin_HEAT",2},{},""},{},{"LM_OPCAN_CMA_uni_Base",{{"FirstAidKit",1},{"ACE_EarPlugs",1},{"OPTRE_32Rnd_762x51_Mag",2,32},{"Chemlight_green",2,1}}},{"LM_OPCAN_IHTV_VEST",{{"OPTRE_32Rnd_762x51_Mag",7,32},{"OPTRE_8Rnd_127x40_Mag",3,8},{"HandGrenade",2,1}}},{"OPTRE_UNSC_Rucksack_M41",{{"OPTRE_M41_Twin_HEAT_SACLOS",2,2}}},"LM_OPCAN_CMA_CH250","LM_OPCAN_Shemagh",{},{"ItemMap","","ItemRadio","ItemCompass","ItemWatch","NVGoggles_INDEP"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class I_IColMAOPTRE_Breacher_ALiVE_01 : LM_OPCAN_CMA_Breacher_OCimport_02 {
        author = "Capt. Houlston, L";
        scope = 2;
        scopeCurator = 2;
        displayName = "Breacher [ALiVE]";
        side = 2;
        faction = "I_ColMA_OPTRE";

        identityTypes[] = {"Head_NATO","LanguageENG_F","NoGlassesÃ¯Â»Â¿"};

        uniformClass = "LM_OPCAN_CMA_uni_Base";

        linkedItems[] = {"LM_OPCAN_IHTV_VEST","LM_OPCAN_CMA_CH250","ItemMap","ItemRadio","ItemCompass","ItemWatch","NVGoggles_INDEP"};
        respawnlinkedItems[] = {"LM_OPCAN_IHTV_VEST","LM_OPCAN_CMA_CH250","ItemMap","ItemRadio","ItemCompass","ItemWatch","NVGoggles_INDEP"};

        weapons[] = {"OPTRE_M45","OPTRE_M6G_SF"};
        respawnWeapons[] = {"OPTRE_M45","OPTRE_M6G_SF"};

        magazines[] = {"OPTRE_6Rnd_8Gauge_Pellets","OPTRE_8Rnd_127x40_Mag_Tracer","OPTRE_6Rnd_8Gauge_Pellets","OPTRE_8Rnd_127x40_Mag_Tracer"};
        respawnMagazines[] = {"OPTRE_6Rnd_8Gauge_Pellets","OPTRE_8Rnd_127x40_Mag_Tracer","OPTRE_6Rnd_8Gauge_Pellets","OPTRE_8Rnd_127x40_Mag_Tracer"};

        ALiVE_orbatCreator_loadout[] = {{"OPTRE_M45","","","",{"OPTRE_6Rnd_8Gauge_Pellets",6},{},""},{},{"OPTRE_M6G_SF","","OPTRE_M6G_Flashlight","OPTRE_M6G_Scope",{"OPTRE_8Rnd_127x40_Mag_Tracer",8},{},""},{"LM_OPCAN_CMA_uni_Base",{{"FirstAidKit",1},{"OPTRE_8Rnd_127x40_Mag_Tracer",2,8}}},{"LM_OPCAN_IHTV_VEST",{{"OPTRE_6Rnd_8Gauge_Slugs",6,6},{"OPTRE_6Rnd_8Gauge_Pellets",5,6}}},{},"LM_OPCAN_CMA_CH250","LM_OPCAN_Shemagh",{},{"ItemMap","","ItemRadio","ItemCompass","ItemWatch","NVGoggles_INDEP"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class I_IColMAOPTRE_Engineer_ALiVE_01 : LM_OPCAN_CMA_Engineer_OCimport_02 {
        author = "Capt. Houlston, L";
        scope = 2;
        scopeCurator = 2;
        displayName = "Engineer [ALiVE]";
        side = 2;
        faction = "I_ColMA_OPTRE";

        identityTypes[] = {"Head_NATO","LanguageENG_F","NoGlassesÃ¯Â»Â¿"};

        uniformClass = "LM_OPCAN_CMA_uni_Base";

        linkedItems[] = {"LM_OPCAN_IHTV_VEST","LM_OPCAN_CMA_CH250","ItemMap","ItemRadio","ItemCompass","ItemWatch","NVGoggles_INDEP"};
        respawnlinkedItems[] = {"LM_OPCAN_IHTV_VEST","LM_OPCAN_CMA_CH250","ItemMap","ItemRadio","ItemCompass","ItemWatch","NVGoggles_INDEP"};

        weapons[] = {"OPTRE_M45","OPTRE_M6G_SF"};
        respawnWeapons[] = {"OPTRE_M45","OPTRE_M6G_SF"};

        magazines[] = {"OPTRE_6Rnd_8Gauge_Pellets","OPTRE_8Rnd_127x40_Mag_Tracer","OPTRE_6Rnd_8Gauge_Pellets","OPTRE_8Rnd_127x40_Mag_Tracer"};
        respawnMagazines[] = {"OPTRE_6Rnd_8Gauge_Pellets","OPTRE_8Rnd_127x40_Mag_Tracer","OPTRE_6Rnd_8Gauge_Pellets","OPTRE_8Rnd_127x40_Mag_Tracer"};

        backpack = "OPTRE_UNSC_Rucksack_Heavy_Demo";

        ALiVE_orbatCreator_loadout[] = {{"OPTRE_M45","","","",{"OPTRE_6Rnd_8Gauge_Pellets",6},{},""},{},{"OPTRE_M6G_SF","","OPTRE_M6G_Flashlight","OPTRE_M6G_Scope",{"OPTRE_8Rnd_127x40_Mag_Tracer",8},{},""},{"LM_OPCAN_CMA_uni_Base",{{"FirstAidKit",1},{"OPTRE_8Rnd_127x40_Mag_Tracer",2,8}}},{"LM_OPCAN_IHTV_VEST",{{"OPTRE_6Rnd_8Gauge_Slugs",6,6},{"OPTRE_6Rnd_8Gauge_Pellets",5,6}}},{"OPTRE_UNSC_Rucksack_Heavy_Demo",{{"ToolKit",1},{"MineDetector",1},{"UNSCMine_Range_Mag",2,1},{"C12_Remote_Mag",2,1}}},"LM_OPCAN_CMA_CH250","LM_OPCAN_UP_Shemagh",{},{"ItemMap","","ItemRadio","ItemCompass","ItemWatch","NVGoggles_INDEP"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class I_IColMAOPTRE_ARV_13_Ferret_ALiVE_01 : LM_OPCAN_ARV_CMA_WDL_OCimport_02 {
        author = "Capt. Houlston, L";
        scope = 2;
        scopeCurator = 2;
        displayName = "ARV-13 Ferret [ALiVE]";
        side = 2;
        faction = "I_ColMA_OPTRE";
        crew = "I_IColMAOPTRE_Crewman_ALiVE_01";

        class Turrets : Turrets {
            class CommanderTurret : CommanderTurret { gunnerType = "I_IColMAOPTRE_Crewman_ALiVE_01"; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class I_IColMAOPTRE_Crewman_ALiVE_01 : LM_OPCAN_CMA_Crewman_OCimport_02 {
        author = "Capt. Houlston, L";
        scope = 2;
        scopeCurator = 2;
        displayName = "Crewman [ALiVE]";
        side = 2;
        faction = "I_ColMA_OPTRE";

        identityTypes[] = {"Head_NATO","LanguageENG_F","NoGlassesÃ¯Â»Â¿"};

        uniformClass = "LM_OPCAN_CMA_uni_Base";

        linkedItems[] = {"LM_OPCAN_IHTV_VEST","OPTRE_UNSC_VX16_Helmet","ItemMap","ItemRadio","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"LM_OPCAN_IHTV_VEST","OPTRE_UNSC_VX16_Helmet","ItemMap","ItemRadio","ItemCompass","ItemWatch"};

        weapons[] = {"OPTRE_M7","OPTRE_M6G_SF"};
        respawnWeapons[] = {"OPTRE_M7","OPTRE_M6G_SF"};

        magazines[] = {"OPTRE_48Rnd_5x23mm_FMJ_Mag","OPTRE_8Rnd_127x40_Mag","OPTRE_48Rnd_5x23mm_FMJ_Mag","OPTRE_8Rnd_127x40_Mag"};
        respawnMagazines[] = {"OPTRE_48Rnd_5x23mm_FMJ_Mag","OPTRE_8Rnd_127x40_Mag","OPTRE_48Rnd_5x23mm_FMJ_Mag","OPTRE_8Rnd_127x40_Mag"};

        ALiVE_orbatCreator_loadout[] = {{"OPTRE_M7","","","",{"OPTRE_48Rnd_5x23mm_FMJ_Mag",48},{},""},{},{"OPTRE_M6G_SF","","OPTRE_M6G_Flashlight","OPTRE_M6G_Scope",{"OPTRE_8Rnd_127x40_Mag",8},{},""},{"LM_OPCAN_CMA_uni_Base",{{"FirstAidKit",1},{"OPTRE_48Rnd_5x23mm_FMJ_Mag",5,48}}},{"LM_OPCAN_IHTV_VEST",{{"OPTRE_48Rnd_5x23mm_FMJ_Mag",4,48},{"OPTRE_8Rnd_127x40_Mag",2,8},{"Chemlight_green",2,1},{"HandGrenade",2,1}}},{},"OPTRE_UNSC_VX16_Helmet","",{},{"ItemMap","","ItemRadio","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class I_IColMAOPTRE_ARV_13_Ferret_M247H_ALiVE_01 : LM_OPCAN_ARV_CMA_HMG_WDL_OCimport_02 {
        author = "Capt. Houlston, L";
        scope = 2;
        scopeCurator = 2;
        displayName = "ARV-13 Ferret [M247H] [ALiVE]";
        side = 2;
        faction = "I_ColMA_OPTRE";
        crew = "I_ColMA_Squad_Leader_ALiVE_OPTRE_01";

        class Turrets : Turrets {
            class MainTurret : MainTurret { gunnerType = "I_ColMA_Rifleman_ALiVE_OPTRE_01"; };
            class CommanderTurret : CommanderTurret { gunnerType = "I_ColMA_Rifleman_ALiVE_OPTRE_01"; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class I_IColMAOPTRE_L159_ALCA_ALiVE_01 : I_Plane_Fighter_03_dynamicLoadout_F_OCimport_02 {
        author = "Capt. Houlston, L";
        scope = 2;
        scopeCurator = 2;
        displayName = "L-159 ALCA [ALiVE]";
        side = 2;
        faction = "I_ColMA_OPTRE";
        crew = "I_IColMAOPTRE_Crewman_ALiVE_01";


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;_unit setObjectTextureGlobal [0,'\a3\Air_F_Gamma\Plane_Fighter_03\Data\Plane_Fighter_03_body_1_brownhex_CO.paa'];_unit setObjectTextureGlobal [1,'\a3\Air_F_Gamma\Plane_Fighter_03\Data\Plane_Fighter_03_body_2_brownhex_CO.paa'];};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_texture = "Hex";

    };

    class I_IColMAOPTRE_AW159_Wildcat_ALiVE_01 : I_Heli_light_03_dynamicLoadout_F_OCimport_02 {
        author = "Capt. Houlston, L";
        scope = 2;
        scopeCurator = 2;
        displayName = "AW159 Wildcat [ALiVE]";
        side = 2;
        faction = "I_ColMA_OPTRE";
        crew = "I_IColMAOPTRE_Crewman_ALiVE_01";

        class Turrets : Turrets {
            class MainTurret : MainTurret { gunnerType = "I_IColMAOPTRE_Crewman_ALiVE_01"; };
            class CargoTurret_01 : CargoTurret_01 { gunnerType = "I_ColMA_Autorifleman_ALiVE_OPTRE_01"; };
            class CargoTurret_02 : CargoTurret_02 { gunnerType = "I_ColMA_Autorifleman_ALiVE_OPTRE_01"; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;_unit setObjectTextureGlobal [0,'\A3\Air_F_Enoch\Heli_Light_03\data\Heli_Light_03_base_EAF_CO.paa'];_unit setObjectTextureGlobal [1,'\a3\Supplies_F_Enoch\Ammoboxes\Data\AmmoBox_EAF_CO.paa'];_unit setObjectTextureGlobal [2,'\a3\Supplies_F_Enoch\Ammoboxes\Data\AmmoBox_signs_EAF_CA.paa'];};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_texture = "EAF";

    };

    class I_IColMAOPTRE_AW159_Wildcat_Unarmed_ALiVE_01 : I_Heli_light_03_unarmed_F_OCimport_02 {
        author = "Capt. Houlston, L";
        scope = 2;
        scopeCurator = 2;
        displayName = "AW159 Wildcat [Unarmed] [ALiVE]";
        side = 2;
        faction = "I_ColMA_OPTRE";
        crew = "I_IColMAOPTRE_Crewman_ALiVE_01";

        class Turrets : Turrets {
            class MainTurret : MainTurret { gunnerType = "I_IColMAOPTRE_Crewman_ALiVE_01"; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;_unit setObjectTextureGlobal [0,'\A3\Air_F_Enoch\Heli_Light_03\data\Heli_Light_03_base_EAF_CO.paa'];_unit setObjectTextureGlobal [1,'\a3\Supplies_F_Enoch\Ammoboxes\Data\AmmoBox_EAF_CO.paa'];_unit setObjectTextureGlobal [2,'\a3\Supplies_F_Enoch\Ammoboxes\Data\AmmoBox_signs_EAF_CA.paa'];};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_texture = "EAF";

    };

    class I_IColMAOPTRE_FV_720_Odyniec_ALiVE_01 : I_E_APC_tracked_03_cannon_F_OCimport_02 {
        author = "Capt. Houlston, L";
        scope = 2;
        scopeCurator = 2;
        displayName = "FV-720 Odyniec [ALiVE]";
        side = 2;
        faction = "I_ColMA_OPTRE";
        crew = "I_IColMAOPTRE_Crewman_ALiVE_01";

        class Turrets : Turrets {
            class MainTurret : MainTurret { gunnerType = "I_IColMAOPTRE_Crewman_ALiVE_01"; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;_unit setObjectTextureGlobal [0,'A3\Armor_F_Enoch\apc_tracked_03\data\apc_tracked_03_ext_eaf_co.paa'];_unit setObjectTextureGlobal [1,'A3\Armor_F_Enoch\apc_tracked_03\data\apc_tracked_03_ext2_eaf_co.paa'];_unit setObjectTextureGlobal [2,'A3\Armor_F_Enoch\apc_tracked_03\Data\camonet_EAF_green_CO.paa'];_unit setObjectTextureGlobal [3,'A3\Armor_F_Enoch\apc_tracked_03\data\cage_EAF_CO.paa'];};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_texture = "EAF_01";

    };

    class I_IColMAOPTRE_Zamak_MRL_ALiVE_01 : I_E_Truck_02_MRL_F_OCimport_02 {
        author = "Capt. Houlston, L";
        scope = 2;
        scopeCurator = 2;
        displayName = "Zamak MRL [ALiVE]";
        side = 2;
        faction = "I_ColMA_OPTRE";
        crew = "I_IColMAOPTRE_Crewman_ALiVE_01";

        class Turrets : Turrets {
            class MainTurret : MainTurret { gunnerType = "I_IColMAOPTRE_Crewman_ALiVE_01"; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class I_IColMAOPTRE_Wiesel_2AA_ALiVE_01 : I_LT_01_AA_F_OCimport_02 {
        author = "Capt. Houlston, L";
        scope = 2;
        scopeCurator = 2;
        displayName = "Wiesel 2 [AA] [ALiVE]";
        side = 2;
        faction = "I_ColMA_OPTRE";
        crew = "I_IColMAOPTRE_Crewman_ALiVE_01";

        class Turrets : Turrets {
            class MainTurret : MainTurret { gunnerType = "I_IColMAOPTRE_Crewman_ALiVE_01"; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;_unit setObjectTextureGlobal [0,'A3\armor_f_tank\lt_01\data\lt_01_main_olive_co.paa'];_unit setObjectTextureGlobal [1,'A3\armor_f_tank\lt_01\data\lt_01_at_olive_co.paa'];_unit setObjectTextureGlobal [2,'A3\Armor_F\Data\camonet_AAF_Digi_Green_CO.paa'];_unit setObjectTextureGlobal [3,'A3\armor_f\data\cage_olive_co.paa'];};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_texture = "Indep_Olive";

    };

    class I_IColMAOPTRE_Wiesel_2ATGM_ALiVE_01 : I_LT_01_AT_F_OCimport_02 {
        author = "Capt. Houlston, L";
        scope = 2;
        scopeCurator = 2;
        displayName = "Wiesel 2 [ATGM] [ALiVE]";
        side = 2;
        faction = "I_ColMA_OPTRE";
        crew = "I_IColMAOPTRE_Crewman_ALiVE_01";

        class Turrets : Turrets {
            class MainTurret : MainTurret { gunnerType = "I_IColMAOPTRE_Crewman_ALiVE_01"; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;_unit setObjectTextureGlobal [0,'A3\armor_f_tank\lt_01\data\lt_01_main_olive_co.paa'];_unit setObjectTextureGlobal [1,'A3\armor_f_tank\lt_01\data\lt_01_at_olive_co.paa'];_unit setObjectTextureGlobal [2,'A3\Armor_F\Data\camonet_AAF_Digi_Green_CO.paa'];_unit setObjectTextureGlobal [3,'A3\armor_f\data\cage_olive_co.paa'];};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_texture = "Indep_Olive";

    };

    class I_IColMAOPTRE_Wiesel_2RFCV_ALiVE_01 : I_LT_01_scout_F_OCimport_02 {
        author = "Capt. Houlston, L";
        scope = 2;
        scopeCurator = 2;
        displayName = "Wiesel 2 RFCV [ALiVE]";
        side = 2;
        faction = "I_ColMA_OPTRE";
        crew = "I_IColMAOPTRE_Crewman_ALiVE_01";

        class Turrets : Turrets {
            class MainTurret : MainTurret { gunnerType = "I_IColMAOPTRE_Crewman_ALiVE_01"; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;_unit setObjectTextureGlobal [0,'A3\armor_f_tank\lt_01\data\lt_01_main_olive_co.paa'];_unit setObjectTextureGlobal [1,'A3\armor_f_tank\lt_01\data\lt_01_radar_olive_co.paa'];_unit setObjectTextureGlobal [2,'A3\Armor_F\Data\camonet_AAF_Digi_Green_CO.paa'];_unit setObjectTextureGlobal [3,'A3\armor_f\data\cage_olive_co.paa'];};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_texture = "Indep_Olive";

    };

    class I_IColMAOPTRE_Wiesel_2MK20_ALiVE_01 : I_LT_01_cannon_F_OCimport_02 {
        author = "Capt. Houlston, L";
        scope = 2;
        scopeCurator = 2;
        displayName = "Wiesel 2 [MK20] [ALiVE]";
        side = 2;
        faction = "I_ColMA_OPTRE";
        crew = "I_IColMAOPTRE_Crewman_ALiVE_01";

        class Turrets : Turrets {
            class MainTurret : MainTurret { gunnerType = "I_IColMAOPTRE_Crewman_ALiVE_01"; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;_unit setObjectTextureGlobal [0,'A3\armor_f_tank\lt_01\data\lt_01_main_olive_co.paa'];_unit setObjectTextureGlobal [1,'A3\armor_f_tank\lt_01\data\lt_01_cannon_olive_co.paa'];_unit setObjectTextureGlobal [2,'A3\Armor_F\Data\camonet_AAF_Digi_Green_CO.paa'];_unit setObjectTextureGlobal [3,'A3\armor_f\data\cage_olive_co.paa'];};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_texture = "Indep_Olive";

    };

    class I_IColMAOPTRE_JAS_39_Griphen_ALiVE_01 : I_Plane_Fighter_04_F_OCimport_02 {
        author = "Capt. Houlston, L";
        scope = 2;
        scopeCurator = 2;
        displayName = "JAS 39 Griphen [ALiVE]";
        side = 2;
        faction = "I_ColMA_OPTRE";
        crew = "I_IColMAOPTRE_Crewman_ALiVE_01";


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;_unit setObjectTextureGlobal [0,'a3\air_f_jets\plane_fighter_04\data\Fighter_04_fuselage_01_co.paa'];_unit setObjectTextureGlobal [1,'a3\air_f_jets\plane_fighter_04\data\Fighter_04_fuselage_02_co.paa'];_unit setObjectTextureGlobal [2,'a3\air_f_jets\plane_fighter_04\data\fighter_04_misc_01_co.paa'];_unit setObjectTextureGlobal [3,'a3\air_f_jets\plane_fighter_04\data\Numbers\Fighter_04_number_04_ca.paa'];_unit setObjectTextureGlobal [4,'a3\air_f_jets\plane_fighter_04\data\Numbers\Fighter_04_number_04_ca.paa'];_unit setObjectTextureGlobal [5,'a3\air_f_jets\plane_fighter_04\data\Numbers\Fighter_04_number_08_ca.paa'];};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_texture = "CamoGrey";

    };

    class I_IColMAOPTRE_ARV_13_Ferret_MG460_AGL_ALiVE_01 : LM_OPCAN_ARV_CMA_GMG_WDL_OCimport_02 {
        author = "Capt. Houlston, L";
        scope = 2;
        scopeCurator = 2;
        displayName = "ARV-13 Ferret [MG460 AGL] [ALiVE]";
        side = 2;
        faction = "I_ColMA_OPTRE";
        crew = "LM_OPCAN_CMA_Rifleman";

        class Turrets : Turrets {
            class MainTurret : MainTurret { gunnerType = ""; };
            class CommanderTurret : CommanderTurret { gunnerType = ""; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

};