class CfgPatches {
    class C_ColCiv_OPTRE {
        units[] = {
            "O_ColCiv_Civilian_ALiVE_OPTRE_01",
            "O_ColCiv_Civilian_2ALiVE_OPTRE_01",
            "O_ColCiv_Civilian_3ALiVE_OPTRE_01",
            "O_ColCiv_Civilian_Pilot_ALiVE_OPTRE_01",
            "O_ColCiv_Civilian_Journalist_ALiVE_OPTRE_01",
            "O_ColCiv_Civilian_Construction_ALiVE_OPTRE_01",
            "O_ColCiv_Paramedic_ALiVE_OPTRE_01",
            "O_ColCiv_Civilian_Utilities_ALiVE_OPTRE_01",
            "O_ColCiv_Civilian_Fisherman_ALiVE_OPTRE_01",
            "O_ColCiv_Messenger_ALiVE_OPTRE_01",
            "C_ColCiv_Civilian_Formal_ALiVE_OPTRE_01",
            "C_ColCiv_Motorboat_ALiVE_OPTRE_01",
            "C_ColCiv_S2_Cargo_Transporter_ALiVE_OPTRE_01",
            "C_ColCiv_HuCiv_Genet_ALiVE_OPTRE_01",
            "C_ColCiv_AMG_Hog_ALiVE_OPTRE_01",
            "C_ColCiv_Racing_Hog_ALiVE_OPTRE_01",
            "C_ColCiv_MD_500_ALiVE_OPTRE_01",
            "C_ColCiv_Cessna_TTx_ALiVE_OPTRE_01",
            "C_ColCiv_Civilian_4ALiVE_OPTRE_01",
            "C_ColCiv_Civilian_5ALiVE_OPTRE_01"
        };
        weapons[] = {};
        requiredVersion = 1.62;
        requiredAddons[] = {
            "A3_Characters_F",
            "A3_Characters_F_Exp_Civil",
            "A3_Sounds_F",
            "A3_Sounds_F_Exp",
            "ace_gforces",
            "ace_goggles",
            "ace_interaction",
            "ace_movement",
            "ace_medical_feedback",
            "A3_Data_F",
            "A3_Data_F_Curator",
            "A3_Air_F_Heli",
            "ace_thermals",
            "ace_refuel",
            "cba_xeh",
            "A3_Characters_F_Orange",
            "A3_Characters_F_Kart",
            "A3_Characters_F_AoW",
            "A3_Boat_F_Gamma_Boat_Civil_01",
            "ace_cargo",
            "A3_Boat_F",
            "OPTRE_Vehicles_Cart",
            "A3_Soft_F",
            "A3_Soft_F_Gamma_Hatchback_01",
            "A3_Soft_F_Exp_Offroad_02",
            "A3_Data_F_ParticleEffects",
            "A3_Armor_F_Beta",
            "OPTRE_Vehicles_genet",
            "OPTRE_ACE_Compat",
            "OPTRE_Vehicles_Warthog",
            "A3_Air_F_Heli_Light_01",
            "ace_realisticnames",
            "A3_Air_F_Heli_Heli_Light_01",
            "ace_aircraft",
            "A3_Air_F",
            "A3_Air_F_Heli_Light_02",
            "A3_Air_F_Beta_Heli_Transport_01",
            "OPTRE_Vehicles_Falcon",
            "OPTRE_Vehicles_Hornet",
            "OPTRE_Vehicles_Pelican",
            "OPTRE_Vehicles_Sparrowhawk",
            "ace_logistics_uavbattery",
            "A3_Air_F_Exp_Plane_Civil_01",
            "A3_Air_F_Beta",
            "A3_Air_F_Gamma_Plane_Fighter_03",
            "A3_Air_F_EPC_Plane_CAS_01",
            "A3_Air_F_EPC_Plane_CAS_02",
            "A3_Air_F_Jets_Plane_Fighter_01",
            "A3_Air_F_Jets_Plane_Fighter_02",
            "A3_Air_F_Jets_Plane_Fighter_04",
            "A3_Air_F_Jets_UAV_05",
            "OPTRE_Vehicles_Pod"
        };
        author = "Capt. Houlston, L";
        authors[] = {"Capt. Houlston, L"};
    };
};
