//////////////////////////////////////////////////////////////////////////////////
// Config Automatically Generated by ALiVE ORBAT Creator
// Generated with Arma 3 version 208.149102 on Stable branch
// Generated with ALiVE version 1.15.1.2207121
//////////////////////////////////////////////////////////////////////////////////

class CfgFactionClasses {
    class O_ColSTEALTH_OPTRE {
        displayName = "402nd Stealth AI (Beta)";
        side = 0;
        flag = "\OPTRE_Core\Data\flag_Ins_ca.paa";
        icon = "\OPTRE_Core\Data\flag_Ins_ca.paa";
        priority = 0;
    };
};

class CfgGroups {
    class EAST {

        class O_ColSTEALTH_OPTRE {
            name = "402nd Stealth AI (Beta)";

            class Infantry {
                name = "Infantry";

                class o_colstealth_infantry_ins_sentry_optre {
                    name = "Ins Sentry [H/S]";
                    side = 0;
                    faction = "O_ColSTEALTH_OPTRE";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_ColSTEALTH_Ins_Hunter_OPTRE_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_ColSTEALTH_Ins_Signaler_OPTRE_01";
                    };
                };

                class o_colstealth_infantry_ins_sentry_rs_optre {
                    name = "Ins Sentry [R/S]";
                    side = 0;
                    faction = "O_ColSTEALTH_OPTRE";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_ColSTEALTH_Ins_Farmer_OPTRE_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_ColSTEALTH_Ins_Signaler_OPTRE_01";
                    };
                };

                class o_colstealth_infantry_ins_sentry_dt_optre {
                    name = "Ins Sentry [D/T]";
                    side = 0;
                    faction = "O_ColSTEALTH_OPTRE";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_ColSTEALTH_Ins_Deserter_GL_OPTRE_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_ColSTEALTH_Ins_Terrorist_OPTRE_01";
                    };
                };

                class o_colstealth_infantry_ins_fireteam_fd_aat_optre {
                    name = "Ins Fireteam [F/D/A/AT]";
                    side = 0;
                    faction = "O_ColSTEALTH_OPTRE";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_ColSTEALTH_Ins_Farmer_OPTRE_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_ColSTEALTH_Ins_Deserter_GL_OPTRE_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_ColSTEALTH_Ins_Autorifleman_OPTRE_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_ColSTEALTH_Ins_Rebel_AT_OPTRE_01";
                    };
                };

                class o_colstealth_infantry_ins_fireteam_fs_ta_optre {
                    name = "Ins Fireteam [F/S/T/A]";
                    side = 0;
                    faction = "O_ColSTEALTH_OPTRE";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_ColSTEALTH_Ins_Farmer_OPTRE_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_ColSTEALTH_Ins_Signaler_OPTRE_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_ColSTEALTH_Ins_Terrorist_OPTRE_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_ColSTEALTH_Ins_Autorifleman_OPTRE_01";
                    };
                };

                class o_colstealth_infantry_ins_squad_optre {
                    name = "Ins Squad";
                    side = 0;
                    faction = "O_ColSTEALTH_OPTRE";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_ColSTEALTH_Ins_Farmer_OPTRE_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_ColSTEALTH_Ins_Hacker_OPTRE_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_ColSTEALTH_Ins_Hunter_OPTRE_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_ColSTEALTH_Ins_Deserter_GL_OPTRE_01";
                    };
                    class Unit4 {
                        position[] = {-10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_ColSTEALTH_Ins_Autorifleman_OPTRE_01";
                    };
                    class Unit5 {
                        position[] = {15,-15,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_ColSTEALTH_Ins_Rebel_AT_OPTRE_01";
                    };
                    class Unit6 {
                        position[] = {-15,-15,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_ColSTEALTH_Ins_Signaler_OPTRE_01";
                    };
                    class Unit7 {
                        position[] = {20,-20,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_ColSTEALTH_Ins_Terrorist_OPTRE_01";
                    };
                };

                class o_colstealth_infantry_urf_sentry_rm_optre {
                    name = "URF Sentry [R/M]";
                    side = 0;
                    faction = "O_ColSTEALTH_OPTRE";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_ColSTEALTH_URF_Rifleman_OPTRE_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_ColSTEALTH_URF_Marksman_OPTRE_01";
                    };
                };

                class o_colstealth_infantry_urf_sentry_ce_gl_optre {
                    name = "URF Sentry [CE/GL]";
                    side = 0;
                    faction = "O_ColSTEALTH_OPTRE";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_ColSTEALTH_URF_Combat_Engineer_OPTRE_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_ColSTEALTH_URF_Grenadier_OPTRE_01";
                    };
                };

                class o_colstealth_infantry_urf_fireteam_tl_rat_optre {
                    name = "URF Fireteam [TL/R/AT/A]";
                    side = 0;
                    faction = "O_ColSTEALTH_OPTRE";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_ColSTEALTH_URF_Team_Leader_OPTRE_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_ColSTEALTH_URF_Rifleman_OPTRE_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_ColSTEALTH_URF_Rifleman_AT_OPTRE_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_ColSTEALTH_URF_Autorifleman_OPTRE_01";
                    };
                };

                class o_colstealth_infantry_urf_fireteam_tl_raa_optre {
                    name = "URF Fireteam [TL/R/AA/M]";
                    side = 0;
                    faction = "O_ColSTEALTH_OPTRE";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_ColSTEALTH_URF_Team_Leader_OPTRE_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_ColSTEALTH_URF_Rifleman_OPTRE_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_ColSTEALTH_URF_Rifleman_AA_OPTRE_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_ColSTEALTH_URF_Marksman_OPTRE_01";
                    };
                };

                class o_colstealth_infantry_urf_rifle_squad_optre {
                    name = "URF Rifle Squad";
                    side = 0;
                    faction = "O_ColSTEALTH_OPTRE";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_ColSTEALTH_URF_Squad_Lead_OPTRE_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_ColSTEALTH_URF_RTO_OPTRE_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_ColSTEALTH_URF_Team_Leader_OPTRE_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_ColSTEALTH_URF_Team_Leader_OPTRE_01";
                    };
                    class Unit4 {
                        position[] = {-10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_ColSTEALTH_URF_Grenadier_OPTRE_01";
                    };
                    class Unit5 {
                        position[] = {15,-15,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_ColSTEALTH_URF_Marksman_OPTRE_01";
                    };
                    class Unit6 {
                        position[] = {-15,-15,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_ColSTEALTH_URF_Medic_OPTRE_01";
                    };
                    class Unit7 {
                        position[] = {20,-20,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_ColSTEALTH_URF_Autorifleman_OPTRE_01";
                    };
                    class Unit8 {
                        position[] = {-20,-20,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_ColSTEALTH_URF_Rifleman_AT_OPTRE_01";
                    };
                    class Unit9 {
                        position[] = {25,-25,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_ColSTEALTH_URF_Rifleman_OPTRE_01";
                    };
                };

            };

            class SpecOps {
                name = "Special Forces";

                class o_colstealth_specops_ins_strike_team_optre {
                    name = "Ins Strike Team";
                    side = 0;
                    faction = "O_ColSTEALTH_OPTRE";
                    icon = "\A3\ui_f\data\map\markers\nato\o_recon.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_ColSTEALTH_Ins_Terrorist_OPTRE_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_ColSTEALTH_Ins_Deserter_GL_OPTRE_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_ColSTEALTH_Ins_Terrorist_OPTRE_01";
                    };
                };

                class o_colstealth_specops_ins_sniper_team_optre {
                    name = "Ins Sniper Team";
                    side = 0;
                    faction = "O_ColSTEALTH_OPTRE";
                    icon = "\A3\ui_f\data\map\markers\nato\o_recon.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_ColSTEALTH_Ins_Assassin_OPTRE_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_ColSTEALTH_Ins_Hunter_OPTRE_01";
                    };
                };

                class o_colstealth_specops_ins_fo_team_optre {
                    name = "Ins FO Team";
                    side = 0;
                    faction = "O_ColSTEALTH_OPTRE";
                    icon = "\A3\ui_f\data\map\markers\nato\o_recon.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_ColSTEALTH_Ins_Signaler_OPTRE_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_ColSTEALTH_Ins_Hacker_OPTRE_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_ColSTEALTH_Ins_Hunter_OPTRE_01";
                    };
                };

                class o_colstealth_specops_urf_strike_optre {
                    name = "URF Strike";
                    side = 0;
                    faction = "O_ColSTEALTH_OPTRE";
                    icon = "\A3\ui_f\data\map\markers\nato\o_recon.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_ColSTEALTH_URF_Team_Leader_OPTRE_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_ColSTEALTH_URF_Combat_Engineer_OPTRE_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_ColSTEALTH_URF_Combat_Engineer_OPTRE_01";
                    };
                };

                class o_colstealth_specops_urf_aa_optre {
                    name = "URF AA";
                    side = 0;
                    faction = "O_ColSTEALTH_OPTRE";
                    icon = "\A3\ui_f\data\map\markers\nato\o_recon.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_ColSTEALTH_URF_Team_Leader_OPTRE_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_ColSTEALTH_URF_Rifleman_AA_OPTRE_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_ColSTEALTH_URF_Rifleman_AA_OPTRE_01";
                    };
                };

                class o_colstealth_specops_urf_mg_optre {
                    name = "URF MG";
                    side = 0;
                    faction = "O_ColSTEALTH_OPTRE";
                    icon = "\A3\ui_f\data\map\markers\nato\o_recon.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_ColSTEALTH_URF_Team_Leader_OPTRE_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_ColSTEALTH_URF_Machinegunner_OPTRE_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_ColSTEALTH_URF_Machinegunner_OPTRE_01";
                    };
                };

                class o_colstealth_specops_urf_fo_optre {
                    name = "URF FO";
                    side = 0;
                    faction = "O_ColSTEALTH_OPTRE";
                    icon = "\A3\ui_f\data\map\markers\nato\o_recon.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_ColSTEALTH_URF_Team_Leader_OPTRE_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_ColSTEALTH_URF_RTO_OPTRE_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_ColSTEALTH_URF_Marksman_OPTRE_01";
                    };
                };

            };

            class Motorized {
                name = "Motorized Infantry";

            };

            class Motorized_MTP {
                name = "Motorized Infantry (MTP)";

            };

            class Support {
                name = "Support Infantry";

            };

            class Mechanized {
                name = "Mechanized Infantry";

            };

            class Armored {
                name = "Armor";

            };

            class Artillery {
                name = "Artillery";

            };

            class Naval {
                name = "Naval";

            };

            class Air {
                name = "Air";

            };


        };

    };
};


class CBA_Extended_EventHandlers_base;

class CfgVehicles {

    class O_soldier_STEALTH;
    class O_soldier_STEALTH_OCimport_01 : O_soldier_STEALTH { scope = 0; class EventHandlers; };
    class O_soldier_STEALTH_OCimport_02 : O_soldier_STEALTH_OCimport_01 { class EventHandlers; };


    class O_ColSTEALTH_Ins_Warlord_OPTRE_01 : O_soldier_STEALTH_OCimport_02 {
        author = "Capt. Houlston, L";
        scope = 2;
        scopeCurator = 2;
        displayName = "Ins Warlord";
        side = 0;
        faction = "O_ColSTEALTH_OPTRE";

        identityTypes[] = {"Head_NATO","LanguageENG_F","G_NATO_default"};

        uniformClass = "OPTRE_Ins_ER_jacket_od_surplus";

        linkedItems[] = {"H_Beret_blk","ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"H_Beret_blk","ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch"};

        weapons[] = {"optre_hgun_comet_F","OPTRE_Binoculars"};
        respawnWeapons[] = {"optre_hgun_comet_F","OPTRE_Binoculars"};

        magazines[] = {"4Rnd_454Casull","4Rnd_454Casull"};
        respawnMagazines[] = {"4Rnd_454Casull","4Rnd_454Casull"};

        ALiVE_orbatCreator_loadout[] = {{},{},{"optre_hgun_comet_F","","acc_flashlight_pistol","",{"4Rnd_454Casull",4},{},""},{"OPTRE_Ins_ER_jacket_od_surplus",{{"OPTRE_Biofoam",1},{"ACE_MapTools",1},{"ACE_EarPlugs",1},{"ACE_Cellphone",1},{"ACE_Banana",5},{"4Rnd_454Casull",2,4}}},{},{},"H_Beret_blk","",{"OPTRE_Binoculars","","","",{},{},""},{"ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_ColSTEALTH_Ins_Terrorist_OPTRE_01 : O_ColSTEALTH_Ins_Warlord_OPTRE_01 {
        author = "Capt. Houlston, L";
        scope = 2;
        scopeCurator = 2;
        displayName = "Ins Terrorist";
        side = 0;
        faction = "O_ColSTEALTH_OPTRE";

        identityTypes[] = {"Head_NATO","LanguageENG_F","G_NATO_default"};

        uniformClass = "OPTRE_Ins_ER_jacket_surplus_redshirt";

        linkedItems[] = {"V_ALiVE_Suicide_Vest","ItemMap","ItemRadio","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"V_ALiVE_Suicide_Vest","ItemMap","ItemRadio","ItemCompass","ItemWatch"};

        weapons[] = {"OPTRE_M45"};
        respawnWeapons[] = {"OPTRE_M45"};

        magazines[] = {"OPTRE_6Rnd_8Gauge_Pellets","OPTRE_6Rnd_8Gauge_Pellets"};
        respawnMagazines[] = {"OPTRE_6Rnd_8Gauge_Pellets","OPTRE_6Rnd_8Gauge_Pellets"};

        backpack = "B_Carryall_oli";

        ALiVE_orbatCreator_loadout[] = {{"OPTRE_M45","","acc_flashlight","",{"OPTRE_6Rnd_8Gauge_Pellets",6},{},""},{},{},{"OPTRE_Ins_ER_jacket_surplus_redshirt",{{"OPTRE_Biofoam",1},{"ACE_splint",2},{"ACE_tourniquet",1},{"OPTRE_6Rnd_8Gauge_Slugs",1,6},{"OPTRE_M9_Frag",1,1},{"OPTRE_6Rnd_8Gauge_HEDP",1,6}}},{"V_ALiVE_Suicide_Vest",{{"OPTRE_6Rnd_8Gauge_Slugs",2,6},{"OPTRE_6Rnd_8Gauge_HEDP",1,6},{"OPTRE_6Rnd_8Gauge_Pellets",1,6}}},{"B_Carryall_oli",{{"ACE_EarPlugs",1},{"M41_IED_Remote_Mag",4,1}}},"","G_Tactical_Black",{},{"ItemMap","","ItemRadio","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_ColSTEALTH_Ins_Farmer_OPTRE_01 : O_ColSTEALTH_Ins_Warlord_OPTRE_01 {
        author = "Capt. Houlston, L";
        scope = 2;
        scopeCurator = 2;
        displayName = "Ins Farmer";
        side = 0;
        faction = "O_ColSTEALTH_OPTRE";

        identityTypes[] = {"Head_NATO","LanguageENG_F","G_NATO_default"};

        uniformClass = "OPTRE_Ins_ER_jacket_brown_surplus";

        linkedItems[] = {"V_BandollierB_blk","H_Watchcap_khk","ItemMap","ItemRadio","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"V_BandollierB_blk","H_Watchcap_khk","ItemMap","ItemRadio","ItemCompass","ItemWatch"};

        weapons[] = {"OPTRE_MA37"};
        respawnWeapons[] = {"OPTRE_MA37"};

        magazines[] = {"OPTRE_32Rnd_762x51_Mag","OPTRE_32Rnd_762x51_Mag"};
        respawnMagazines[] = {"OPTRE_32Rnd_762x51_Mag","OPTRE_32Rnd_762x51_Mag"};

        ALiVE_orbatCreator_loadout[] = {{"OPTRE_MA37","","","",{"OPTRE_32Rnd_762x51_Mag",32},{},""},{},{},{"OPTRE_Ins_ER_jacket_brown_surplus",{{"OPTRE_Biofoam",1},{"ACE_tourniquet",2},{"ACE_splint",4},{"ACE_morphine",1},{"ACE_Flashlight_MX991",1}}},{"V_BandollierB_blk",{{"ACE_Banana",1},{"ACE_packingBandage",5},{"ACE_quikclot",5},{"ACE_elasticBandage",5},{"ACE_EarPlugs",1},{"ACE_MapTools",1},{"ACE_tourniquet",2},{"OPTRE_32Rnd_762x51_Mag",6,32}}},{},"H_Watchcap_khk","",{},{"ItemMap","","ItemRadio","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_ColSTEALTH_Ins_Hacker_OPTRE_01 : O_ColSTEALTH_Ins_Warlord_OPTRE_01 {
        author = "Capt. Houlston, L";
        scope = 2;
        scopeCurator = 2;
        displayName = "Ins Hacker";
        side = 0;
        faction = "O_ColSTEALTH_OPTRE";

        identityTypes[] = {"Head_NATO","LanguageENG_F","G_NATO_default"};

        uniformClass = "OPTRE_Ins_ER_rolled_jean_orca";

        linkedItems[] = {"V_BandollierB_blk","OPTRE_h_PatrolCap_Green","ItemMap","ItemRadio","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"V_BandollierB_blk","OPTRE_h_PatrolCap_Green","ItemMap","ItemRadio","ItemCompass","ItemWatch"};

        weapons[] = {"OPTRE_M7","OPTRE_M6G"};
        respawnWeapons[] = {"OPTRE_M7","OPTRE_M6G"};

        magazines[] = {"OPTRE_60Rnd_5x23mm_Mag_tracer_yellow","OPTRE_60Rnd_5x23mm_Mag_tracer_yellow"};
        respawnMagazines[] = {"OPTRE_60Rnd_5x23mm_Mag_tracer_yellow","OPTRE_60Rnd_5x23mm_Mag_tracer_yellow"};

        backpack = "OPTRE_ANPRC_521_URF";

        ALiVE_orbatCreator_loadout[] = {{"OPTRE_M7","","","",{"OPTRE_60Rnd_5x23mm_Mag_tracer_yellow",60},{},""},{},{"OPTRE_M6G","","OPTRE_M6G_Flashlight","OPTRE_M6G_Scope",{},{},""},{"OPTRE_Ins_ER_rolled_jean_orca",{{"OPTRE_Biofoam",1},{"ACE_splint",2},{"ACE_EarPlugs",1},{"ACE_MapTools",1},{"ACE_Flashlight_XL50",1}}},{"V_BandollierB_blk",{{"ACE_EarPlugs",1},{"ACE_tourniquet",4},{"ACE_splint",3},{"OPTRE_M9_Frag",1,1},{"OPTRE_48Rnd_5x23mm_JHP_Mag",4,48},{"OPTRE_48Rnd_5x23mm_FMJ_Mag",4,48},{"ACE_M84",1,1},{"SmokeShell",2,1}}},{"OPTRE_ANPRC_521_URF",{{"ACE_fieldDressing",6},{"ACE_elasticBandage",7},{"ACE_packingBandage",8},{"ACE_quikclot",8},{"ACE_Banana",12},{"ACE_UAVBattery",1},{"ACE_tourniquet",1}}},"OPTRE_h_PatrolCap_Green","",{},{"ItemMap","","ItemRadio","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_ColSTEALTH_Ins_Hunter_OPTRE_01 : O_ColSTEALTH_Ins_Warlord_OPTRE_01 {
        author = "Capt. Houlston, L";
        scope = 2;
        scopeCurator = 2;
        displayName = "Ins Hunter";
        side = 0;
        faction = "O_ColSTEALTH_OPTRE";

        identityTypes[] = {"Head_NATO","LanguageENG_F","G_NATO_default"};

        uniformClass = "OPTRE_Ins_ER_uniform_GGgrey";

        linkedItems[] = {"OPTRE_UNSC_M52A_Armor_Soft","H_Booniehat_oli","ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"OPTRE_UNSC_M52A_Armor_Soft","H_Booniehat_oli","ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch"};

        weapons[] = {"OPTRE_M392_DMR","OPTRE_Binoculars"};
        respawnWeapons[] = {"OPTRE_M392_DMR","OPTRE_Binoculars"};

        magazines[] = {"OPTRE_15Rnd_762x51_Mag","OPTRE_15Rnd_762x51_Mag"};
        respawnMagazines[] = {"OPTRE_15Rnd_762x51_Mag","OPTRE_15Rnd_762x51_Mag"};

        backpack = "B_AssaultPack_blk";

        ALiVE_orbatCreator_loadout[] = {{"OPTRE_M392_DMR","","OPTRE_BMR_Laser","OPTRE_BR55HB_Scope",{"OPTRE_15Rnd_762x51_Mag",15},{},"bipod_02_F_blk"},{},{},{"OPTRE_Ins_ER_uniform_GGgrey",{{"OPTRE_Biofoam",1},{"ACE_tourniquet",4},{"ACE_splint",4},{"ACE_EarPlugs",1},{"ACE_quikclot",3},{"ACE_elasticBandage",3},{"ACE_packingBandage",3},{"ACE_Banana",1},{"OPTRE_M2_Smoke",1,1}}},{"OPTRE_UNSC_M52A_Armor_Soft",{{"OPTRE_M9_Frag",2,1},{"OPTRE_M2_Smoke_Green",1,1},{"OPTRE_15Rnd_762x51_Mag",4,15}}},{"B_AssaultPack_blk",{{"ACE_SpottingScope",1},{"ACE_Tripod",1},{"ACE_EntrenchingTool",1}}},"H_Booniehat_oli","",{"OPTRE_Binoculars","","","",{},{},""},{"ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_ColSTEALTH_Ins_Deserter_GL_OPTRE_01 : O_ColSTEALTH_Ins_Warlord_OPTRE_01 {
        author = "Capt. Houlston, L";
        scope = 2;
        scopeCurator = 2;
        displayName = "Ins Deserter [GL]";
        side = 0;
        faction = "O_ColSTEALTH_OPTRE";

        identityTypes[] = {"Head_NATO","LanguageENG_F","G_NATO_default"};

        uniformClass = "OPTRE_Ins_ER_rolled_surplus_crimson";

        linkedItems[] = {"OPTRE_UNSC_M52A_Armor_Soft","LM_OPCAN_CH252_AR_W","ItemMap","ItemRadio","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"OPTRE_UNSC_M52A_Armor_Soft","LM_OPCAN_CH252_AR_W","ItemMap","ItemRadio","ItemCompass","ItemWatch"};

        weapons[] = {"OPTRE_MA37GL"};
        respawnWeapons[] = {"OPTRE_MA37GL"};

        magazines[] = {"OPTRE_32Rnd_762x51_Mag","OPTRE_32Rnd_762x51_Mag"};
        respawnMagazines[] = {"OPTRE_32Rnd_762x51_Mag","OPTRE_32Rnd_762x51_Mag"};

        backpack = "B_AssaultPack_rgr";

        ALiVE_orbatCreator_loadout[] = {{"OPTRE_MA37GL","","","",{"OPTRE_32Rnd_762x51_Mag",32},{},""},{},{},{"OPTRE_Ins_ER_rolled_surplus_crimson",{{"OPTRE_Biofoam",1},{"ACE_Banana",2},{"ACE_packingBandage",6},{"ACE_quikclot",5},{"ACE_elasticBandage",5},{"ACE_EarPlugs",1},{"ACE_Flashlight_MX991",1},{"ACE_MapTools",1},{"ACE_Flashlight_XL50",1},{"ACE_splint",2},{"ACE_tourniquet",2}}},{"OPTRE_UNSC_M52A_Armor_Soft",{{"OPTRE_32Rnd_762x51_Mag",6,32},{"1Rnd_HE_Grenade_shell",3,1},{"UGL_FlareYellow_F",2,1}}},{"B_AssaultPack_rgr",{{"ACE_HuntIR_monitor",1},{"ACE_EarPlugs",1},{"OPTRE_M9_Frag",2,1},{"SmokeShell",2,1},{"ACE_HandFlare_Green",2,1},{"1Rnd_HE_Grenade_shell",10,1},{"UGL_FlareWhite_F",1,1},{"UGL_FlareGreen_F",2,1},{"UGL_FlareRed_F",2,1},{"UGL_FlareYellow_F",2,1},{"OPTRE_3Rnd_Smoke_Grenade_shell",2,3},{"ACE_HuntIR_M203",1,1},{"ACE_40mm_Flare_white",2,1}}},"LM_OPCAN_CH252_AR_W","",{},{"ItemMap","","ItemRadio","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_ColSTEALTH_Ins_Autorifleman_OPTRE_01 : O_ColSTEALTH_Ins_Warlord_OPTRE_01 {
        author = "Capt. Houlston, L";
        scope = 2;
        scopeCurator = 2;
        displayName = "Ins Autorifleman";
        side = 0;
        faction = "O_ColSTEALTH_OPTRE";

        identityTypes[] = {"Head_NATO","LanguageENG_F","G_NATO_default"};

        uniformClass = "OPTRE_Ins_ER_rolled_OD_blknblu";

        linkedItems[] = {"LM_OPCAN_CPD_Vest_UP","H_Watchcap_cbr","ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"LM_OPCAN_CPD_Vest_UP","H_Watchcap_cbr","ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch"};

        weapons[] = {"OPTRE_M73","OPTRE_Binoculars"};
        respawnWeapons[] = {"OPTRE_M73","OPTRE_Binoculars"};

        magazines[] = {"OPTRE_100Rnd_95x40_Box_Tracer_Yellow","OPTRE_100Rnd_95x40_Box_Tracer_Yellow"};
        respawnMagazines[] = {"OPTRE_100Rnd_95x40_Box_Tracer_Yellow","OPTRE_100Rnd_95x40_Box_Tracer_Yellow"};

        ALiVE_orbatCreator_loadout[] = {{"OPTRE_M73","","","OPTRE_BR55HB_Scope",{"OPTRE_100Rnd_95x40_Box_Tracer_Yellow",100},{},"bipod_01_F_blk"},{},{},{"OPTRE_Ins_ER_rolled_OD_blknblu",{{"OPTRE_Biofoam",1},{"OPTRE_M9_Frag",2,1},{"OPTRE_M2_Smoke",1,1},{"OPTRE_M2_Smoke_Green",1,1}}},{"LM_OPCAN_CPD_Vest_UP",{{"ACE_quikclot",2},{"ACE_packingBandage",2},{"ACE_elasticBandage",2},{"ACE_fieldDressing",2},{"ACE_Banana",5},{"ACE_EarPlugs",1},{"ACE_MapTools",1},{"ACE_Flashlight_MX991",1},{"ACE_splint",5},{"ACE_tourniquet",4},{"OPTRE_100Rnd_95x40_Box_Tracer_Yellow",3,100}}},{},"H_Watchcap_cbr","",{"OPTRE_Binoculars","","","",{},{},""},{"ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_ColSTEALTH_Ins_Assassin_OPTRE_01 : O_ColSTEALTH_Ins_Warlord_OPTRE_01 {
        author = "Capt. Houlston, L";
        scope = 2;
        scopeCurator = 2;
        displayName = "Ins Assassin";
        side = 0;
        faction = "O_ColSTEALTH_OPTRE";

        identityTypes[] = {"Head_NATO","LanguageENG_F","G_NATO_default"};

        uniformClass = "OPTRE_Ins_ER_rolled_surplus_black";

        linkedItems[] = {"OPTRE_UNSC_M52A_Armor_Sniper_WDL","H_Watchcap_cbr","ItemMap","ItemRadio","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"OPTRE_UNSC_M52A_Armor_Sniper_WDL","H_Watchcap_cbr","ItemMap","ItemRadio","ItemCompass","ItemWatch"};

        weapons[] = {"OPTRE_SRM77_S1"};
        respawnWeapons[] = {"OPTRE_SRM77_S1"};

        magazines[] = {"OPTRE_10Rnd_127x99","OPTRE_10Rnd_127x99"};
        respawnMagazines[] = {"OPTRE_10Rnd_127x99","OPTRE_10Rnd_127x99"};

        ALiVE_orbatCreator_loadout[] = {{"OPTRE_SRM77_S1","","acc_flashlight","OPTRE_SRM_Sight",{"OPTRE_10Rnd_127x99",10},{},"bipod_02_F_blk"},{},{},{"OPTRE_Ins_ER_rolled_surplus_black",{{"OPTRE_Biofoam",1},{"OPTRE_M2_Smoke",1,1}}},{"OPTRE_UNSC_M52A_Armor_Sniper_WDL",{{"ACE_EarPlugs",1},{"ACE_Flashlight_MX991",1},{"ACE_MapTools",1},{"ACE_splint",5},{"ACE_tourniquet",4},{"ACE_packingBandage",2},{"ACE_quikclot",2},{"ACE_elasticBandage",2},{"ACE_DAGR",1},{"ACE_RangeCard",1},{"OPTRE_M2_Smoke_Green",1,1},{"OPTRE_10Rnd_127x99",6,10}}},{},"H_Watchcap_cbr","LM_OPCAN_UP_Shemagh",{},{"ItemMap","","ItemRadio","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_ColSTEALTH_Ins_Rebel_AT_OPTRE_01 : O_ColSTEALTH_Ins_Warlord_OPTRE_01 {
        author = "Capt. Houlston, L";
        scope = 2;
        scopeCurator = 2;
        displayName = "Ins Rebel [AT]";
        side = 0;
        faction = "O_ColSTEALTH_OPTRE";

        identityTypes[] = {"Head_NATO","LanguageENG_F","G_NATO_default"};

        uniformClass = "OPTRE_Ins_ER_rolled_surplus_black";

        linkedItems[] = {"V_TacVestIR_blk","H_Bandanna_gry","ItemMap","ItemRadio","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"V_TacVestIR_blk","H_Bandanna_gry","ItemMap","ItemRadio","ItemCompass","ItemWatch"};

        weapons[] = {"OPTRE_M7","OPTRE_M41_SSR","OPTRE_Binoculars"};
        respawnWeapons[] = {"OPTRE_M7","OPTRE_M41_SSR","OPTRE_Binoculars"};

        magazines[] = {"OPTRE_60Rnd_5x23mm_Mag","OPTRE_M41_Twin_HEAT","OPTRE_60Rnd_5x23mm_Mag"};
        respawnMagazines[] = {"OPTRE_60Rnd_5x23mm_Mag","OPTRE_M41_Twin_HEAT","OPTRE_60Rnd_5x23mm_Mag"};

        backpack = "OPTRE_B_TacticalPack_blk_M41";

        ALiVE_orbatCreator_loadout[] = {{"OPTRE_M7","","","",{"OPTRE_60Rnd_5x23mm_Mag",60},{},""},{"OPTRE_M41_SSR","","","",{"OPTRE_M41_Twin_HEAT",2},{},""},{},{"OPTRE_Ins_ER_rolled_surplus_black",{{"OPTRE_Biofoam",1}}},{"V_TacVestIR_blk",{{"ACE_tourniquet",4},{"ACE_Banana",1},{"ACE_EarPlugs",1},{"ACE_Flashlight_MX991",1},{"ACE_MapTools",1},{"ACE_morphine",1},{"ACE_splint",5},{"OPTRE_M9_Frag",2,1},{"OPTRE_M2_Smoke",1,1},{"OPTRE_M2_Smoke_Green",1,1},{"OPTRE_48Rnd_5x23mm_FMJ_Mag",3,48},{"OPTRE_48Rnd_5x23mm_JHP_Mag",5,48},{"SmokeShell",1,1}}},{"OPTRE_B_TacticalPack_blk_M41",{{"OPTRE_M41_Twin_HEAT",1,2},{"OPTRE_M41_Twin_HEAP",1,2}}},"H_Bandanna_gry","G_Tactical_Clear",{"OPTRE_Binoculars","","","",{},{},""},{"ItemMap","","ItemRadio","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_ColSTEALTH_Ins_Signaler_OPTRE_01 : O_ColSTEALTH_Ins_Warlord_OPTRE_01 {
        author = "Capt. Houlston, L";
        scope = 2;
        scopeCurator = 2;
        displayName = "Ins Signaler";
        side = 0;
        faction = "O_ColSTEALTH_OPTRE";

        identityTypes[] = {"Head_NATO","LanguageENG_F","G_NATO_default"};

        uniformClass = "OPTRE_Ins_ER_rolled_surplus_black";

        linkedItems[] = {"LM_OPCAN_CPD_Rig","OPTRE_Ins_URF_Helmet3","ItemMap","ItemRadio","ItemCompass","ItemWatch","ACE_NVG_Gen1"};
        respawnlinkedItems[] = {"LM_OPCAN_CPD_Rig","OPTRE_Ins_URF_Helmet3","ItemMap","ItemRadio","ItemCompass","ItemWatch","ACE_NVG_Gen1"};

        weapons[] = {"OPTRE_BR55HB","OPTRE_M319s"};
        respawnWeapons[] = {"OPTRE_BR55HB","OPTRE_M319s"};

        magazines[] = {"OPTRE_36Rnd_95x40_Mag","1Rnd_HE_Grenade_shell","OPTRE_36Rnd_95x40_Mag","1Rnd_HE_Grenade_shell"};
        respawnMagazines[] = {"OPTRE_36Rnd_95x40_Mag","1Rnd_HE_Grenade_shell","OPTRE_36Rnd_95x40_Mag","1Rnd_HE_Grenade_shell"};

        ALiVE_orbatCreator_loadout[] = {{"OPTRE_BR55HB","","acc_flashlight","OPTRE_BR45_Scope",{"OPTRE_36Rnd_95x40_Mag",36},{},""},{},{"OPTRE_M319s","","","",{"1Rnd_HE_Grenade_shell",1},{},""},{"OPTRE_Ins_ER_rolled_surplus_black",{{"OPTRE_Biofoam",1},{"ACE_EarPlugs",1},{"ACE_fieldDressing",4},{"ACE_elasticBandage",4},{"ACE_packingBandage",4},{"ACE_Banana",1},{"ACE_tourniquet",4},{"OPTRE_M9_Frag",2,1}}},{"LM_OPCAN_CPD_Rig",{{"OPTRE_M2_Smoke",1,1},{"OPTRE_M2_Smoke_Green",1,1},{"OPTRE_36Rnd_95x40_Mag",6,36},{"UGL_FlareYellow_F",4,1},{"UGL_FlareRed_F",4,1},{"UGL_FlareGreen_F",4,1},{"UGL_FlareWhite_F",4,1}}},{},"OPTRE_Ins_URF_Helmet3","",{},{"ItemMap","","ItemRadio","ItemCompass","ItemWatch","ACE_NVG_Gen1"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_ColSTEALTH_URF_Rifleman_AA_OPTRE_01 : O_ColSTEALTH_Ins_Warlord_OPTRE_01 {
        author = "Capt. Houlston, L";
        scope = 2;
        scopeCurator = 2;
        displayName = "URF Rifleman [AA]";
        side = 0;
        faction = "O_ColSTEALTH_OPTRE";

        identityTypes[] = {"Head_NATO","LanguageENG_F","G_NATO_default"};

        uniformClass = "LM_OPCAN_URA_Uni";

        linkedItems[] = {"LM_OPCAN_MTMV_VEST","LM_OPCAN_ACH43","ItemMap","ItemRadio","ItemCompass","ItemWatch","O_NVGoggles_grn_F"};
        respawnlinkedItems[] = {"LM_OPCAN_MTMV_VEST","LM_OPCAN_ACH43","ItemMap","ItemRadio","ItemCompass","ItemWatch","O_NVGoggles_grn_F"};

        weapons[] = {"OPTRE_MA32","OPTRE_M41_SSR"};
        respawnWeapons[] = {"OPTRE_MA32","OPTRE_M41_SSR"};

        magazines[] = {"OPTRE_32Rnd_762x51_Mag","OPTRE_M41_Twin_HEAT","OPTRE_32Rnd_762x51_Mag"};
        respawnMagazines[] = {"OPTRE_32Rnd_762x51_Mag","OPTRE_M41_Twin_HEAT","OPTRE_32Rnd_762x51_Mag"};

        backpack = "OPTRE_UNSC_Rucksack_M41";

        ALiVE_orbatCreator_loadout[] = {{"OPTRE_MA32","","","OPTRE_M7_Sight",{"OPTRE_32Rnd_762x51_Mag",32},{},""},{"OPTRE_M41_SSR","","","",{"OPTRE_M41_Twin_HEAT",2},{},""},{},{"LM_OPCAN_URA_Uni",{{"FirstAidKit",1},{"ACE_EarPlugs",1},{"OPTRE_32Rnd_762x51_Mag",2,32},{"Chemlight_green",2,1}}},{"LM_OPCAN_MTMV_VEST",{{"OPTRE_32Rnd_762x51_Mag",7,32},{"OPTRE_8Rnd_127x40_Mag",3,8},{"HandGrenade",2,1}}},{"OPTRE_UNSC_Rucksack_M41",{{"OPTRE_M41_Twin_HEAT_Thermal",3,2}}},"LM_OPCAN_ACH43","LM_OPCAN_Shemagh",{},{"ItemMap","","ItemRadio","ItemCompass","ItemWatch","O_NVGoggles_grn_F"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_ColSTEALTH_URF_Rifleman_AT_OPTRE_01 : O_ColSTEALTH_Ins_Warlord_OPTRE_01 {
        author = "Capt. Houlston, L";
        scope = 2;
        scopeCurator = 2;
        displayName = "URF Rifleman [AT]";
        side = 0;
        faction = "O_ColSTEALTH_OPTRE";

        identityTypes[] = {"Head_NATO","LanguageENG_F","G_NATO_default"};

        uniformClass = "LM_OPCAN_URA_Uni";

        linkedItems[] = {"LM_OPCAN_MTMV_VEST","LM_OPCAN_ACH43","ItemMap","ItemRadio","ItemCompass","ItemWatch","O_NVGoggles_grn_F"};
        respawnlinkedItems[] = {"LM_OPCAN_MTMV_VEST","LM_OPCAN_ACH43","ItemMap","ItemRadio","ItemCompass","ItemWatch","O_NVGoggles_grn_F"};

        weapons[] = {"OPTRE_MA32","OPTRE_M41_SSR"};
        respawnWeapons[] = {"OPTRE_MA32","OPTRE_M41_SSR"};

        magazines[] = {"OPTRE_32Rnd_762x51_Mag","OPTRE_M41_Twin_HEAT","OPTRE_32Rnd_762x51_Mag"};
        respawnMagazines[] = {"OPTRE_32Rnd_762x51_Mag","OPTRE_M41_Twin_HEAT","OPTRE_32Rnd_762x51_Mag"};

        backpack = "OPTRE_UNSC_Rucksack_M41";

        ALiVE_orbatCreator_loadout[] = {{"OPTRE_MA32","","","OPTRE_M393_EOTECH",{"OPTRE_32Rnd_762x51_Mag",32},{},""},{"OPTRE_M41_SSR","","","",{"OPTRE_M41_Twin_HEAT",2},{},""},{},{"LM_OPCAN_URA_Uni",{{"FirstAidKit",1},{"ACE_EarPlugs",1},{"OPTRE_32Rnd_762x51_Mag",2,32},{"Chemlight_green",2,1}}},{"LM_OPCAN_MTMV_VEST",{{"OPTRE_32Rnd_762x51_Mag",6,32},{"OPTRE_8Rnd_127x40_Mag",3,8},{"HandGrenade",2,1}}},{"OPTRE_UNSC_Rucksack_M41",{{"OPTRE_M41_Twin_HEAT_SACLOS",2,2}}},"LM_OPCAN_ACH43","LM_OPCAN_Shemagh",{},{"ItemMap","","ItemRadio","ItemCompass","ItemWatch","O_NVGoggles_grn_F"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_ColSTEALTH_URF_Autorifleman_OPTRE_01 : O_ColSTEALTH_Ins_Warlord_OPTRE_01 {
        author = "Capt. Houlston, L";
        scope = 2;
        scopeCurator = 2;
        displayName = "URF Autorifleman";
        side = 0;
        faction = "O_ColSTEALTH_OPTRE";

        identityTypes[] = {"Head_NATO","LanguageENG_F","G_NATO_default"};

        uniformClass = "LM_OPCAN_URA_Uni";

        linkedItems[] = {"LM_OPCAN_MTMV_VEST","LM_OPCAN_ACH43","ItemMap","ItemRadio","ItemCompass","ItemWatch","O_NVGoggles_grn_F"};
        respawnlinkedItems[] = {"LM_OPCAN_MTMV_VEST","LM_OPCAN_ACH43","ItemMap","ItemRadio","ItemCompass","ItemWatch","O_NVGoggles_grn_F"};

        weapons[] = {"OPTRE_M73","OPTRE_M6G"};
        respawnWeapons[] = {"OPTRE_M73","OPTRE_M6G"};

        magazines[] = {"OPTRE_200Rnd_95x40_Box","OPTRE_8Rnd_127x40_Mag","OPTRE_200Rnd_95x40_Box","OPTRE_8Rnd_127x40_Mag"};
        respawnMagazines[] = {"OPTRE_200Rnd_95x40_Box","OPTRE_8Rnd_127x40_Mag","OPTRE_200Rnd_95x40_Box","OPTRE_8Rnd_127x40_Mag"};

        backpack = "OPTRE_UNSC_Rucksack_Heavy";

        ALiVE_orbatCreator_loadout[] = {{"OPTRE_M73","","","OPTRE_M73_SmartLink",{"OPTRE_200Rnd_95x40_Box",200},{},"bipod_01_F_blk"},{},{"OPTRE_M6G","","OPTRE_M6G_Flashlight","OPTRE_M6G_Scope",{"OPTRE_8Rnd_127x40_Mag",8},{},""},{"LM_OPCAN_URA_Uni",{{"FirstAidKit",1},{"ACE_EarPlugs",1},{"OPTRE_8Rnd_127x40_Mag",2,8},{"Chemlight_green",2,1}}},{"LM_OPCAN_MTMV_VEST",{{"HandGrenade",2,1}}},{"OPTRE_UNSC_Rucksack_Heavy",{{"OPTRE_100Rnd_95x40_Box",3,100}}},"LM_OPCAN_ACH43","LM_OPCAN_UP_Shemagh",{},{"ItemMap","","ItemRadio","ItemCompass","ItemWatch","O_NVGoggles_grn_F"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_ColSTEALTH_URF_Combat_Engineer_OPTRE_01 : O_ColSTEALTH_Ins_Warlord_OPTRE_01 {
        author = "Capt. Houlston, L";
        scope = 2;
        scopeCurator = 2;
        displayName = "URF Combat Engineer";
        side = 0;
        faction = "O_ColSTEALTH_OPTRE";

        identityTypes[] = {"Head_NATO","LanguageENG_F","G_NATO_default"};

        uniformClass = "LM_OPCAN_URA_Uni";

        linkedItems[] = {"LM_OPCAN_MTMV_VEST","LM_OPCAN_ACH43","ItemMap","ItemRadio","ItemCompass","ItemWatch","O_NVGoggles_grn_F"};
        respawnlinkedItems[] = {"LM_OPCAN_MTMV_VEST","LM_OPCAN_ACH43","ItemMap","ItemRadio","ItemCompass","ItemWatch","O_NVGoggles_grn_F"};

        weapons[] = {"OPTRE_M45","OPTRE_M6G"};
        respawnWeapons[] = {"OPTRE_M45","OPTRE_M6G"};

        magazines[] = {"OPTRE_6Rnd_8Gauge_Pellets","OPTRE_8Rnd_127x40_Mag_Tracer","OPTRE_6Rnd_8Gauge_Pellets","OPTRE_8Rnd_127x40_Mag_Tracer"};
        respawnMagazines[] = {"OPTRE_6Rnd_8Gauge_Pellets","OPTRE_8Rnd_127x40_Mag_Tracer","OPTRE_6Rnd_8Gauge_Pellets","OPTRE_8Rnd_127x40_Mag_Tracer"};

        backpack = "OPTRE_UNSC_Rucksack_Heavy_Demo";

        ALiVE_orbatCreator_loadout[] = {{"OPTRE_M45","","","OPTRE_M7_Sight",{"OPTRE_6Rnd_8Gauge_Pellets",6},{},""},{},{"OPTRE_M6G","","OPTRE_M6G_Flashlight","OPTRE_M6G_Scope",{"OPTRE_8Rnd_127x40_Mag_Tracer",8},{},""},{"LM_OPCAN_URA_Uni",{{"FirstAidKit",1},{"OPTRE_8Rnd_127x40_Mag_Tracer",2,8}}},{"LM_OPCAN_MTMV_VEST",{{"OPTRE_6Rnd_8Gauge_Slugs",6,6},{"OPTRE_6Rnd_8Gauge_Pellets",5,6}}},{"OPTRE_UNSC_Rucksack_Heavy_Demo",{{"ToolKit",1},{"MineDetector",1},{"UNSCMine_Range_Mag",2,1},{"C7_Remote_Mag",4,1}}},"LM_OPCAN_ACH43","LM_OPCAN_UP_Shemagh",{},{"ItemMap","","ItemRadio","ItemCompass","ItemWatch","O_NVGoggles_grn_F"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_ColSTEALTH_URF_Crewman_OPTRE_01 : O_ColSTEALTH_Ins_Warlord_OPTRE_01 {
        author = "Capt. Houlston, L";
        scope = 2;
        scopeCurator = 2;
        displayName = "URF Crewman";
        side = 0;
        faction = "O_ColSTEALTH_OPTRE";

        identityTypes[] = {"Head_NATO","LanguageENG_F","G_NATO_default"};

        uniformClass = "LM_OPCAN_URA_Uni";

        linkedItems[] = {"LM_OPCAN_MTMV_VEST","LM_OPCAN_ACH43","ItemMap","ItemRadio","ItemCompass","ItemWatch","O_NVGoggles_grn_F"};
        respawnlinkedItems[] = {"LM_OPCAN_MTMV_VEST","LM_OPCAN_ACH43","ItemMap","ItemRadio","ItemCompass","ItemWatch","O_NVGoggles_grn_F"};

        weapons[] = {"OPTRE_M7","OPTRE_M6G"};
        respawnWeapons[] = {"OPTRE_M7","OPTRE_M6G"};

        magazines[] = {"OPTRE_48Rnd_5x23mm_FMJ_Mag","OPTRE_8Rnd_127x40_Mag","OPTRE_48Rnd_5x23mm_FMJ_Mag","OPTRE_8Rnd_127x40_Mag"};
        respawnMagazines[] = {"OPTRE_48Rnd_5x23mm_FMJ_Mag","OPTRE_8Rnd_127x40_Mag","OPTRE_48Rnd_5x23mm_FMJ_Mag","OPTRE_8Rnd_127x40_Mag"};

        ALiVE_orbatCreator_loadout[] = {{"OPTRE_M7","","","OPTRE_M12_Optic",{"OPTRE_48Rnd_5x23mm_FMJ_Mag",48},{},""},{},{"OPTRE_M6G","","OPTRE_M6G_Flashlight","OPTRE_M6G_Scope",{"OPTRE_8Rnd_127x40_Mag",8},{},""},{"LM_OPCAN_URA_Uni",{{"FirstAidKit",1},{"OPTRE_48Rnd_5x23mm_FMJ_Mag",5,48}}},{"LM_OPCAN_MTMV_VEST",{{"OPTRE_48Rnd_5x23mm_FMJ_Mag",4,48},{"OPTRE_8Rnd_127x40_Mag",2,8},{"Chemlight_green",2,1},{"HandGrenade",2,1}}},{},"LM_OPCAN_ACH43","",{},{"ItemMap","","ItemRadio","ItemCompass","ItemWatch","O_NVGoggles_grn_F"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_ColSTEALTH_URF_Grenadier_OPTRE_01 : O_ColSTEALTH_Ins_Warlord_OPTRE_01 {
        author = "Capt. Houlston, L";
        scope = 2;
        scopeCurator = 2;
        displayName = "URF Grenadier";
        side = 0;
        faction = "O_ColSTEALTH_OPTRE";

        identityTypes[] = {"Head_NATO","LanguageENG_F","G_NATO_default"};

        uniformClass = "LM_OPCAN_URA_Uni";

        linkedItems[] = {"LM_OPCAN_MTMV_VEST","LM_OPCAN_ACH43","ItemMap","ItemRadio","ItemCompass","ItemWatch","O_NVGoggles_grn_F"};
        respawnlinkedItems[] = {"LM_OPCAN_MTMV_VEST","LM_OPCAN_ACH43","ItemMap","ItemRadio","ItemCompass","ItemWatch","O_NVGoggles_grn_F"};

        weapons[] = {"OPTRE_MA32GL"};
        respawnWeapons[] = {"OPTRE_MA32GL"};

        magazines[] = {"OPTRE_32Rnd_762x51_Mag","OPTRE_32Rnd_762x51_Mag"};
        respawnMagazines[] = {"OPTRE_32Rnd_762x51_Mag","OPTRE_32Rnd_762x51_Mag"};

        ALiVE_orbatCreator_loadout[] = {{"OPTRE_MA32GL","","","OPTRE_M393_EOTECH",{"OPTRE_32Rnd_762x51_Mag",32},{},""},{},{},{"LM_OPCAN_URA_Uni",{{"FirstAidKit",1},{"ACE_EarPlugs",1},{"OPTRE_32Rnd_762x51_Mag",2,32},{"Chemlight_green",1,1}}},{"LM_OPCAN_MTMV_VEST",{{"OPTRE_32Rnd_762x51_Mag",7,32},{"1Rnd_HE_Grenade_shell",4,1},{"Chemlight_green",1,1},{"HandGrenade",2,1}}},{},"LM_OPCAN_ACH43","LM_OPCAN_UP_Shemagh",{},{"ItemMap","","ItemRadio","ItemCompass","ItemWatch","O_NVGoggles_grn_F"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_ColSTEALTH_URF_Machinegunner_OPTRE_01 : O_ColSTEALTH_Ins_Warlord_OPTRE_01 {
        author = "Capt. Houlston, L";
        scope = 2;
        scopeCurator = 2;
        displayName = "URF Machinegunner";
        side = 0;
        faction = "O_ColSTEALTH_OPTRE";

        identityTypes[] = {"Head_NATO","LanguageENG_F","G_NATO_default"};

        uniformClass = "LM_OPCAN_URA_Uni";

        linkedItems[] = {"LM_OPCAN_MTMV_VEST","LM_OPCAN_ACH43","ItemMap","ItemRadio","ItemCompass","ItemWatch","O_NVGoggles_grn_F"};
        respawnlinkedItems[] = {"LM_OPCAN_MTMV_VEST","LM_OPCAN_ACH43","ItemMap","ItemRadio","ItemCompass","ItemWatch","O_NVGoggles_grn_F"};

        weapons[] = {"OPTRE_M247","OPTRE_M6G"};
        respawnWeapons[] = {"OPTRE_M247","OPTRE_M6G"};

        magazines[] = {"OPTRE_100Rnd_762x51_Box","OPTRE_8Rnd_127x40_Mag","OPTRE_100Rnd_762x51_Box","OPTRE_8Rnd_127x40_Mag"};
        respawnMagazines[] = {"OPTRE_100Rnd_762x51_Box","OPTRE_8Rnd_127x40_Mag","OPTRE_100Rnd_762x51_Box","OPTRE_8Rnd_127x40_Mag"};

        backpack = "OPTRE_UNSC_Rucksack_Heavy";

        ALiVE_orbatCreator_loadout[] = {{"OPTRE_M247","","","OPTRE_M7_Sight",{"OPTRE_100Rnd_762x51_Box",100},{},"bipod_02_F_blk"},{},{"OPTRE_M6G","","OPTRE_M6G_Flashlight","OPTRE_M6G_Scope",{"OPTRE_8Rnd_127x40_Mag",8},{},""},{"LM_OPCAN_URA_Uni",{{"FirstAidKit",1},{"ACE_EarPlugs",1},{"OPTRE_8Rnd_127x40_Mag",2,8},{"Chemlight_green",2,1}}},{"LM_OPCAN_MTMV_VEST",{{"HandGrenade",2,1}}},{"OPTRE_UNSC_Rucksack_Heavy",{{"OPTRE_400Rnd_762x51_Box_Tracer",3,400}}},"LM_OPCAN_ACH43","LM_OPCAN_UP_Shemagh",{},{"ItemMap","","ItemRadio","ItemCompass","ItemWatch","O_NVGoggles_grn_F"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_ColSTEALTH_URF_Marksman_OPTRE_01 : O_ColSTEALTH_Ins_Warlord_OPTRE_01 {
        author = "Capt. Houlston, L";
        scope = 2;
        scopeCurator = 2;
        displayName = "URF Marksman";
        side = 0;
        faction = "O_ColSTEALTH_OPTRE";

        identityTypes[] = {"Head_NATO","LanguageENG_F","G_NATO_default"};

        uniformClass = "LM_OPCAN_URA_Uni";

        linkedItems[] = {"LM_OPCAN_MTMV_VEST","LM_OPCAN_ACH43","ItemMap","ItemRadio","ItemCompass","ItemWatch","O_NVGoggles_grn_F"};
        respawnlinkedItems[] = {"LM_OPCAN_MTMV_VEST","LM_OPCAN_ACH43","ItemMap","ItemRadio","ItemCompass","ItemWatch","O_NVGoggles_grn_F"};

        weapons[] = {"OPTRE_M392_DMR","OPTRE_M6G"};
        respawnWeapons[] = {"OPTRE_M392_DMR","OPTRE_M6G"};

        magazines[] = {"OPTRE_15Rnd_762x51_Mag","OPTRE_8Rnd_127x40_Mag","OPTRE_15Rnd_762x51_Mag","OPTRE_8Rnd_127x40_Mag"};
        respawnMagazines[] = {"OPTRE_15Rnd_762x51_Mag","OPTRE_8Rnd_127x40_Mag","OPTRE_15Rnd_762x51_Mag","OPTRE_8Rnd_127x40_Mag"};

        ALiVE_orbatCreator_loadout[] = {{"OPTRE_M392_DMR","OPTRE_MA5Suppressor","OPTRE_BMR_Laser","OPTRE_M392_Scope",{"OPTRE_15Rnd_762x51_Mag",15},{},"bipod_02_F_blk"},{},{"OPTRE_M6G","","","",{"OPTRE_8Rnd_127x40_Mag",8},{},""},{"LM_OPCAN_URA_Uni",{{"FirstAidKit",1},{"ACE_EarPlugs",1},{"Chemlight_green",2,1},{"OPTRE_15Rnd_762x51_Mag",3,15}}},{"LM_OPCAN_MTMV_VEST",{{"OPTRE_8Rnd_127x40_Mag",2,8},{"OPTRE_15Rnd_762x51_Mag",7,15}}},{},"LM_OPCAN_ACH43","LM_OPCAN_UP_Shemagh",{},{"ItemMap","","ItemRadio","ItemCompass","ItemWatch","O_NVGoggles_grn_F"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_ColSTEALTH_URF_Medic_OPTRE_01 : O_ColSTEALTH_Ins_Warlord_OPTRE_01 {
        author = "Capt. Houlston, L";
        scope = 2;
        scopeCurator = 2;
        displayName = "URF Medic";
        side = 0;
        faction = "O_ColSTEALTH_OPTRE";

        identityTypes[] = {"Head_NATO","LanguageENG_F","G_NATO_default"};

        uniformClass = "LM_OPCAN_URA_Uni";

        linkedItems[] = {"LM_OPCAN_MTMV_VEST","LM_OPCAN_ACH43","ItemMap","ItemRadio","ItemCompass","ItemWatch","O_NVGoggles_grn_F"};
        respawnlinkedItems[] = {"LM_OPCAN_MTMV_VEST","LM_OPCAN_ACH43","ItemMap","ItemRadio","ItemCompass","ItemWatch","O_NVGoggles_grn_F"};

        weapons[] = {"OPTRE_M7","OPTRE_M6G"};
        respawnWeapons[] = {"OPTRE_M7","OPTRE_M6G"};

        magazines[] = {"OPTRE_48Rnd_5x23mm_FMJ_Mag","OPTRE_8Rnd_127x40_Mag","OPTRE_48Rnd_5x23mm_FMJ_Mag","OPTRE_8Rnd_127x40_Mag"};
        respawnMagazines[] = {"OPTRE_48Rnd_5x23mm_FMJ_Mag","OPTRE_8Rnd_127x40_Mag","OPTRE_48Rnd_5x23mm_FMJ_Mag","OPTRE_8Rnd_127x40_Mag"};

        backpack = "OPTRE_UNSC_Rucksack_Medic_Filled";

        ALiVE_orbatCreator_loadout[] = {{"OPTRE_M7","","","OPTRE_M393_EOTECH",{"OPTRE_48Rnd_5x23mm_FMJ_Mag",48},{},""},{},{"OPTRE_M6G","","OPTRE_M6G_Flashlight","OPTRE_M6G_Scope",{"OPTRE_8Rnd_127x40_Mag",8},{},""},{"LM_OPCAN_URA_Uni",{{"FirstAidKit",1},{"OPTRE_48Rnd_5x23mm_FMJ_Mag",5,48}}},{"LM_OPCAN_MTMV_VEST",{{"OPTRE_48Rnd_5x23mm_FMJ_Mag",4,48},{"OPTRE_8Rnd_127x40_Mag",2,8},{"Chemlight_green",2,1},{"HandGrenade",2,1}}},{"OPTRE_UNSC_Rucksack_Medic_Filled",{{"OPTRE_Biofoam",12},{"OPTRE_MedKit",2}}},"LM_OPCAN_ACH43","LM_OPCAN_UP_Shemagh",{},{"ItemMap","","ItemRadio","ItemCompass","ItemWatch","O_NVGoggles_grn_F"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_ColSTEALTH_URF_Officer_OPTRE_01 : O_ColSTEALTH_Ins_Warlord_OPTRE_01 {
        author = "Capt. Houlston, L";
        scope = 2;
        scopeCurator = 2;
        displayName = "URF Officer";
        side = 0;
        faction = "O_ColSTEALTH_OPTRE";

        identityTypes[] = {"Head_NATO","LanguageENG_F","G_NATO_default"};

        uniformClass = "LM_OPCAN_URA_Uni";

        linkedItems[] = {"LM_OPCAN_MTMV_VEST","H_Beret_blk","ItemMap","ItemRadio","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"LM_OPCAN_MTMV_VEST","H_Beret_blk","ItemMap","ItemRadio","ItemCompass","ItemWatch"};

        weapons[] = {"OPTRE_M7","OPTRE_M6G"};
        respawnWeapons[] = {"OPTRE_M7","OPTRE_M6G"};

        magazines[] = {"OPTRE_60Rnd_5x23mm_Mag","OPTRE_8Rnd_127x40_Mag","OPTRE_60Rnd_5x23mm_Mag","OPTRE_8Rnd_127x40_Mag"};
        respawnMagazines[] = {"OPTRE_60Rnd_5x23mm_Mag","OPTRE_8Rnd_127x40_Mag","OPTRE_60Rnd_5x23mm_Mag","OPTRE_8Rnd_127x40_Mag"};

        ALiVE_orbatCreator_loadout[] = {{"OPTRE_M7","","","",{"OPTRE_60Rnd_5x23mm_Mag",60},{},""},{},{"OPTRE_M6G","","OPTRE_M6G_Flashlight","OPTRE_M6G_Scope",{"OPTRE_8Rnd_127x40_Mag",8},{},""},{"LM_OPCAN_URA_Uni",{{"FirstAidKit",1},{"ACE_EarPlugs",1},{"Chemlight_green",2,1},{"OPTRE_60Rnd_5x23mm_Mag",3,60}}},{"LM_OPCAN_MTMV_VEST",{{"OPTRE_8Rnd_127x40_Mag",2,8},{"HandGrenade",2,1}}},{},"H_Beret_blk","LM_OPCAN_Shemagh",{},{"ItemMap","","ItemRadio","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_ColSTEALTH_URF_Rifleman_OPTRE_01 : O_ColSTEALTH_Ins_Warlord_OPTRE_01 {
        author = "Capt. Houlston, L";
        scope = 2;
        scopeCurator = 2;
        displayName = "URF Rifleman";
        side = 0;
        faction = "O_ColSTEALTH_OPTRE";

        identityTypes[] = {"Head_NATO","LanguageENG_F","G_NATO_default"};

        uniformClass = "LM_OPCAN_URA_Uni";

        linkedItems[] = {"LM_OPCAN_MTMV_VEST","LM_OPCAN_ACH43","ItemMap","ItemRadio","ItemCompass","ItemWatch","O_NVGoggles_grn_F"};
        respawnlinkedItems[] = {"LM_OPCAN_MTMV_VEST","LM_OPCAN_ACH43","ItemMap","ItemRadio","ItemCompass","ItemWatch","O_NVGoggles_grn_F"};

        weapons[] = {"OPTRE_MA32","OPTRE_M6G"};
        respawnWeapons[] = {"OPTRE_MA32","OPTRE_M6G"};

        magazines[] = {"OPTRE_32Rnd_762x51_Mag","OPTRE_8Rnd_127x40_Mag","OPTRE_32Rnd_762x51_Mag","OPTRE_8Rnd_127x40_Mag"};
        respawnMagazines[] = {"OPTRE_32Rnd_762x51_Mag","OPTRE_8Rnd_127x40_Mag","OPTRE_32Rnd_762x51_Mag","OPTRE_8Rnd_127x40_Mag"};

        ALiVE_orbatCreator_loadout[] = {{"OPTRE_MA32","","","optic_Hamr",{"OPTRE_32Rnd_762x51_Mag",32},{},""},{},{"OPTRE_M6G","","OPTRE_M6G_Flashlight","OPTRE_M6G_Scope",{"OPTRE_8Rnd_127x40_Mag",8},{},""},{"LM_OPCAN_URA_Uni",{{"FirstAidKit",1},{"ACE_EarPlugs",1},{"OPTRE_32Rnd_762x51_Mag",2,32},{"Chemlight_green",2,1}}},{"LM_OPCAN_MTMV_VEST",{{"OPTRE_32Rnd_762x51_Mag",7,32},{"OPTRE_8Rnd_127x40_Mag",2,8},{"HandGrenade",2,1}}},{},"LM_OPCAN_ACH43","LM_OPCAN_Shemagh",{},{"ItemMap","","ItemRadio","ItemCompass","ItemWatch","O_NVGoggles_grn_F"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_ColSTEALTH_URF_RTO_OPTRE_01 : O_ColSTEALTH_Ins_Warlord_OPTRE_01 {
        author = "Capt. Houlston, L";
        scope = 2;
        scopeCurator = 2;
        displayName = "URF RTO";
        side = 0;
        faction = "O_ColSTEALTH_OPTRE";

        identityTypes[] = {"Head_NATO","LanguageENG_F","G_NATO_default"};

        uniformClass = "LM_OPCAN_URA_Uni";

        linkedItems[] = {"LM_OPCAN_MTMV_VEST","LM_OPCAN_ACH43","ItemMap","ItemRadio","ItemCompass","ItemWatch","O_NVGoggles_grn_F"};
        respawnlinkedItems[] = {"LM_OPCAN_MTMV_VEST","LM_OPCAN_ACH43","ItemMap","ItemRadio","ItemCompass","ItemWatch","O_NVGoggles_grn_F"};

        weapons[] = {"OPTRE_M7","OPTRE_M6G"};
        respawnWeapons[] = {"OPTRE_M7","OPTRE_M6G"};

        magazines[] = {"OPTRE_48Rnd_5x23mm_FMJ_Mag","OPTRE_8Rnd_127x40_Mag","OPTRE_48Rnd_5x23mm_FMJ_Mag","OPTRE_8Rnd_127x40_Mag"};
        respawnMagazines[] = {"OPTRE_48Rnd_5x23mm_FMJ_Mag","OPTRE_8Rnd_127x40_Mag","OPTRE_48Rnd_5x23mm_FMJ_Mag","OPTRE_8Rnd_127x40_Mag"};

        backpack = "OPTRE_ANPRC_521_URF";

        ALiVE_orbatCreator_loadout[] = {{"OPTRE_M7","","","optic_ACO_grn_smg",{"OPTRE_48Rnd_5x23mm_FMJ_Mag",48},{},""},{},{"OPTRE_M6G","","OPTRE_M6G_Flashlight","OPTRE_M6G_Scope",{"OPTRE_8Rnd_127x40_Mag",8},{},""},{"LM_OPCAN_URA_Uni",{{"FirstAidKit",1},{"OPTRE_48Rnd_5x23mm_FMJ_Mag",5,48}}},{"LM_OPCAN_MTMV_VEST",{{"OPTRE_48Rnd_5x23mm_FMJ_Mag",4,48},{"OPTRE_8Rnd_127x40_Mag",2,8},{"Chemlight_green",2,1},{"HandGrenade",2,1}}},{"OPTRE_ANPRC_521_URF",{}},"LM_OPCAN_ACH43","LM_OPCAN_Shemagh",{},{"ItemMap","","ItemRadio","ItemCompass","ItemWatch","O_NVGoggles_grn_F"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_ColSTEALTH_URF_Squad_Lead_OPTRE_01 : O_ColSTEALTH_Ins_Warlord_OPTRE_01 {
        author = "Capt. Houlston, L";
        scope = 2;
        scopeCurator = 2;
        displayName = "URF Squad Lead";
        side = 0;
        faction = "O_ColSTEALTH_OPTRE";

        identityTypes[] = {"Head_NATO","LanguageENG_F","G_NATO_default"};

        uniformClass = "LM_OPCAN_URA_Uni";

        linkedItems[] = {"LM_OPCAN_MTMV_VEST","LM_OPCAN_ACH43","ItemMap","ItemRadio","ItemCompass","ItemWatch","O_NVGoggles_grn_F"};
        respawnlinkedItems[] = {"LM_OPCAN_MTMV_VEST","LM_OPCAN_ACH43","ItemMap","ItemRadio","ItemCompass","ItemWatch","O_NVGoggles_grn_F"};

        weapons[] = {"OPTRE_MA32","OPTRE_M6G"};
        respawnWeapons[] = {"OPTRE_MA32","OPTRE_M6G"};

        magazines[] = {"OPTRE_32Rnd_762x51_Mag","OPTRE_8Rnd_127x40_Mag","OPTRE_32Rnd_762x51_Mag","OPTRE_8Rnd_127x40_Mag"};
        respawnMagazines[] = {"OPTRE_32Rnd_762x51_Mag","OPTRE_8Rnd_127x40_Mag","OPTRE_32Rnd_762x51_Mag","OPTRE_8Rnd_127x40_Mag"};

        backpack = "OPTRE_UNSC_Rucksack_Heavy";

        ALiVE_orbatCreator_loadout[] = {{"OPTRE_MA32","","","OPTRE_M7_Sight",{"OPTRE_32Rnd_762x51_Mag",32},{},""},{},{"OPTRE_M6G","","OPTRE_M6G_Flashlight","OPTRE_M6G_Scope",{"OPTRE_8Rnd_127x40_Mag",8},{},""},{"LM_OPCAN_URA_Uni",{{"FirstAidKit",1},{"ACE_EarPlugs",1},{"OPTRE_32Rnd_762x51_Mag",2,32},{"Chemlight_green",2,1}}},{"LM_OPCAN_MTMV_VEST",{{"OPTRE_32Rnd_762x51_Mag",7,32},{"OPTRE_8Rnd_127x40_Mag",2,8},{"HandGrenade",2,1}}},{"OPTRE_UNSC_Rucksack_Heavy",{}},"LM_OPCAN_ACH43","LM_OPCAN_UP_Shemagh",{},{"ItemMap","","ItemRadio","ItemCompass","ItemWatch","O_NVGoggles_grn_F"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_ColSTEALTH_URF_Sniper_OPTRE_01 : O_ColSTEALTH_Ins_Warlord_OPTRE_01 {
        author = "Capt. Houlston, L";
        scope = 2;
        scopeCurator = 2;
        displayName = "URF Sniper";
        side = 0;
        faction = "O_ColSTEALTH_OPTRE";

        identityTypes[] = {"Head_NATO","LanguageENG_F","G_NATO_default"};

        uniformClass = "LM_OPCAN_URA_Uni";

        linkedItems[] = {"LM_OPCAN_MTMV_VEST","LM_OPCAN_ACH43","ItemMap","ItemRadio","ItemCompass","ItemWatch","O_NVGoggles_grn_F"};
        respawnlinkedItems[] = {"LM_OPCAN_MTMV_VEST","LM_OPCAN_ACH43","ItemMap","ItemRadio","ItemCompass","ItemWatch","O_NVGoggles_grn_F"};

        weapons[] = {"OPTRE_SRS99C","OPTRE_M6G"};
        respawnWeapons[] = {"OPTRE_SRS99C","OPTRE_M6G"};

        magazines[] = {"OPTRE_4Rnd_145x114_APFSDS_Mag","OPTRE_8Rnd_127x40_Mag","OPTRE_4Rnd_145x114_APFSDS_Mag","OPTRE_8Rnd_127x40_Mag"};
        respawnMagazines[] = {"OPTRE_4Rnd_145x114_APFSDS_Mag","OPTRE_8Rnd_127x40_Mag","OPTRE_4Rnd_145x114_APFSDS_Mag","OPTRE_8Rnd_127x40_Mag"};

        ALiVE_orbatCreator_loadout[] = {{"OPTRE_SRS99C","","","OPTRE_SRS99C_Scope",{"OPTRE_4Rnd_145x114_APFSDS_Mag",4},{},""},{},{"OPTRE_M6G","","OPTRE_M6G_Flashlight","OPTRE_M6G_Scope",{"OPTRE_8Rnd_127x40_Mag",8},{},""},{"LM_OPCAN_URA_Uni",{{"FirstAidKit",1},{"ACE_EarPlugs",1},{"OPTRE_4Rnd_145x114_APFSDS_Mag",1,4},{"Chemlight_green",2,1}}},{"LM_OPCAN_MTMV_VEST",{{"OPTRE_4Rnd_145x114_APFSDS_Mag",8,4},{"OPTRE_8Rnd_127x40_Mag",2,8},{"HandGrenade",2,1}}},{},"LM_OPCAN_ACH43","LM_OPCAN_UP_Shemagh",{},{"ItemMap","","ItemRadio","ItemCompass","ItemWatch","O_NVGoggles_grn_F"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_ColSTEALTH_URF_Team_Leader_OPTRE_01 : O_ColSTEALTH_Ins_Warlord_OPTRE_01 {
        author = "Capt. Houlston, L";
        scope = 2;
        scopeCurator = 2;
        displayName = "URF Team Leader";
        side = 0;
        faction = "O_ColSTEALTH_OPTRE";

        identityTypes[] = {"Head_NATO","LanguageENG_F","G_NATO_default"};

        uniformClass = "LM_OPCAN_URA_Uni";

        linkedItems[] = {"LM_OPCAN_MTMV_VEST","LM_OPCAN_ACH43","ItemMap","ItemRadio","ItemCompass","ItemWatch","O_NVGoggles_grn_F"};
        respawnlinkedItems[] = {"LM_OPCAN_MTMV_VEST","LM_OPCAN_ACH43","ItemMap","ItemRadio","ItemCompass","ItemWatch","O_NVGoggles_grn_F"};

        weapons[] = {"OPTRE_MA32GL"};
        respawnWeapons[] = {"OPTRE_MA32GL"};

        magazines[] = {"OPTRE_32Rnd_762x51_Mag","OPTRE_32Rnd_762x51_Mag"};
        respawnMagazines[] = {"OPTRE_32Rnd_762x51_Mag","OPTRE_32Rnd_762x51_Mag"};

        backpack = "OPTRE_UNSC_Rucksack";

        ALiVE_orbatCreator_loadout[] = {{"OPTRE_MA32GL","","","OPTRE_M7_Sight",{"OPTRE_32Rnd_762x51_Mag",32},{},""},{},{},{"LM_OPCAN_URA_Uni",{{"FirstAidKit",1},{"ACE_EarPlugs",1},{"OPTRE_32Rnd_762x51_Mag",2,32},{"Chemlight_green",1,1}}},{"LM_OPCAN_MTMV_VEST",{{"OPTRE_32Rnd_762x51_Mag",7,32},{"1Rnd_HE_Grenade_shell",4,1},{"Chemlight_green",1,1},{"HandGrenade",2,1}}},{"OPTRE_UNSC_Rucksack",{}},"LM_OPCAN_ACH43","LM_OPCAN_Shemagh",{},{"ItemMap","","ItemRadio","ItemCompass","ItemWatch","O_NVGoggles_grn_F"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

};