//////////////////////////////////////////////////////////////////////////////////
// Config Automatically Generated by ALiVE ORBAT Creator
// Generated with Arma 3 version 204.147540 on Stable branch
// Generated with ALiVE version 1.14.1.2105061
//////////////////////////////////////////////////////////////////////////////////

class CfgFactionClasses {
    class O_ColIns_OPTRE {
        displayName = "Insurrection [ALiVE]";
        side = 0;
        flag = "\OPTRE_Core\Data\flag_Ins_ca.paa";
        icon = "\OPTRE_Core\Data\flag_Ins_ca.paa";
        priority = 0;
    };
};

class CfgGroups {
    class EAST {

        class O_ColIns_OPTRE {
            name = "Insurrection [ALiVE]";

            class Infantry {
                name = "Infantry";

                class o_colins_infantry_militia_patrol_optre {
                    name = "Militia Patrol";
                    side = 0;
                    faction = "O_ColIns_OPTRE";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_ColIns_Hunter_ALiVE_OPTRE_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_ColIns_Signaler_MA37_OPTRE_01";
                    };
                };

                class o_colins_infantry_militia_group_optre {
                    name = "Militia Group";
                    side = 0;
                    faction = "O_ColIns_OPTRE";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_ColIns_Deserter_GL_ALiVE_OPTRE_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_ColIns_Farmer_MA37_ALiVE_OPTRE_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_ColIns_Rebel_AT_ALiVE_OPTRE_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_ColIns_Militia_MG_ALiVE_OPTRE_01";
                    };
                };

                class o_colins_infantry_militia_squad_optre {
                    name = "Militia Squad";
                    side = 0;
                    faction = "O_ColIns_OPTRE";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_ColIns_Deserter_GL_ALiVE_OPTRE_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_ColIns_Farmer_MA37_ALiVE_OPTRE_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_ColIns_Rebel_AT_ALiVE_OPTRE_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_ColIns_Militia_MG_ALiVE_OPTRE_01";
                    };
                    class Unit4 {
                        position[] = {-10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_ColIns_Hunter_ALiVE_OPTRE_01";
                    };
                    class Unit5 {
                        position[] = {15,-15,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_ColIns_Surgeon_ALiVE_OPTRE_01";
                    };
                    class Unit6 {
                        position[] = {-15,-15,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_ColIns_Hacker_ALiVE_OPTRE_01";
                    };
                    class Unit7 {
                        position[] = {20,-20,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_ColIns_Signaler_MA37_OPTRE_01";
                    };
                };

            };

            class SpecOps {
                name = "Special Forces";

                class o_colins_specops_militia_sniper_optre {
                    name = "Militia Sniper";
                    side = 0;
                    faction = "O_ColIns_OPTRE";
                    icon = "\A3\ui_f\data\map\markers\nato\o_recon.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_ColIns_Hunter_ALiVE_OPTRE_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_ColIns_Assassin_ALiVE_OPTRE_01";
                    };
                };

                class o_colins_specops_militia_fo_optre {
                    name = "Militia FO";
                    side = 0;
                    faction = "O_ColIns_OPTRE";
                    icon = "\A3\ui_f\data\map\markers\nato\o_recon.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_ColIns_Hacker_ALiVE_OPTRE_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_ColIns_Deserter_GL_ALiVE_OPTRE_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_ColIns_Signaler_MA37_OPTRE_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_ColIns_Hunter_ALiVE_OPTRE_01";
                    };
                };

            };

            class Motorized {
                name = "Motorized Infantry";

                class o_colins_motorized_light_convoy_optre {
                    name = "Light Convoy";
                    side = 0;
                    faction = "O_ColIns_OPTRE";
                    icon = "\A3\ui_f\data\map\markers\nato\o_motor_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_ColIns_M12_LRV_MG_Ins_ALiVE_OPTRE_01";
                    };
                    class Unit1 {
                        position[] = {6,-12,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_ColIns_M12_APC_Ins_ALiVE_OPTRE_01";
                    };
                    class Unit2 {
                        position[] = {-6,-12,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_ColIns_M12_FAV_Ins_ALiVE_OPTRE_01";
                    };
                };

                class o_colins_motorized_heavy_convoy_optre {
                    name = "Heavy Convoy";
                    side = 0;
                    faction = "O_ColIns_OPTRE";
                    icon = "\A3\ui_f\data\map\markers\nato\o_motor_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_ColIns_M12_LRV_MG_Ins_ALiVE_OPTRE_01";
                    };
                    class Unit1 {
                        position[] = {6,-11,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_ColIns_M12A1_LRV_ATGM_Ins_ALiVE_OPTRE_01";
                    };
                    class Unit2 {
                        position[] = {-6,-11,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_ColIns_M12_LRV_MG_Ins_ALiVE_OPTRE_01";
                    };
                    class Unit3 {
                        position[] = {12,-17,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_ColIns_M12_FAV_Ins_ALiVE_OPTRE_01";
                    };
                };

                class o_colins_motorized_qrf_convoy_optre {
                    name = "QRF Convoy";
                    side = 0;
                    faction = "O_ColIns_OPTRE";
                    icon = "\A3\ui_f\data\map\markers\nato\o_motor_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_ColIns_M12_FAV_Ins_ALiVE_OPTRE_01";
                    };
                    class Unit1 {
                        position[] = {6,-11,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_ColIns_M12_LRV_MG_Ins_ALiVE_OPTRE_01";
                    };
                    class Unit2 {
                        position[] = {-6,-11,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_ColIns_M12_APC_Ins_ALiVE_OPTRE_01";
                    };
                    class Unit3 {
                        position[] = {12,-18,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_ColIns_M12_Medical_APC_Ins_ALiVE_OPTRE_01";
                    };
                };

                class o_colins_motorized_aa_convoy_optre {
                    name = "AA Convoy";
                    side = 0;
                    faction = "O_ColIns_OPTRE";
                    icon = "\A3\ui_f\data\map\markers\nato\o_motor_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_ColIns_M12_LRV_MG_Ins_ALiVE_OPTRE_01";
                    };
                    class Unit1 {
                        position[] = {6,-11,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_ColIns_M12R_AA_Ins_ALiVE_OPTRE_01";
                    };
                };

                class o_colins_motorized_heavy_qrf_convoy_optre {
                    name = "Heavy QRF Convoy";
                    side = 0;
                    faction = "O_ColIns_OPTRE";
                    icon = "\A3\ui_f\data\map\markers\nato\o_motor_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_ColIns_M1015_Mule_Ins_ALiVE_OPTRE_01";
                    };
                    class Unit1 {
                        position[] = {6,-24,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_ColIns_M1015_Mule_Ins_ALiVE_OPTRE_01";
                    };
                };

            };

            class Motorized_MTP {
                name = "Motorized Infantry (MTP)";

            };

            class Support {
                name = "Support Infantry";

            };

            class Mechanized {
                name = "Mechanized Infantry";

            };

            class Armored {
                name = "Armor";

            };

            class Artillery {
                name = "Artillery";

                class o_colins_artillery_mortar_team_optre {
                    name = "Mortar Team";
                    side = 0;
                    faction = "O_ColIns_OPTRE";
                    icon = "\A3\ui_f\data\map\markers\nato\o_art.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_ColIns_Hacker_ALiVE_OPTRE_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_ColIns_Mk6_Mortar_Ins_ALiVE_OPTRE_01";
                    };
                };

            };

            class Naval {
                name = "Naval";

            };

            class Air {
                name = "Air";

                class o_colins_air_light_rotary_cas_optre {
                    name = "Light Rotary CAS";
                    side = 0;
                    faction = "O_ColIns_OPTRE";
                    icon = "\A3\ui_f\data\map\markers\nato\o_air.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_ColIns_AV_14_Hornet_Ins_ALiVE_OPTRE_01";
                    };
                };

                class o_colins_air_heavy_rotary_cas_optre {
                    name = "Heavy Rotary CAS";
                    side = 0;
                    faction = "O_ColIns_OPTRE";
                    icon = "\A3\ui_f\data\map\markers\nato\o_air.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_ColIns_D77H_TCI_AV_Pelican_Ins_ALiVE_OPTRE_01";
                    };
                    class Unit1 {
                        position[] = {11,-14,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_ColIns_AV_14_Hornet_Ins_ALiVE_OPTRE_01";
                    };
                    class Unit2 {
                        position[] = {-11,-14,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_ColIns_AV_14_Hornet_Ins_ALiVE_OPTRE_01";
                    };
                };

                class o_colins_air_light_rotary_cap_optre {
                    name = "Light Rotary CAP";
                    side = 0;
                    faction = "O_ColIns_OPTRE";
                    icon = "\A3\ui_f\data\map\markers\nato\o_air.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_ColIns_AV_14_Hornet_Ins_ALiVE_OPTRE_01";
                    };
                };

                class o_colins_air_heavy_rotary_cap_optre {
                    name = "Heavy Rotary CAP";
                    side = 0;
                    faction = "O_ColIns_OPTRE";
                    icon = "\A3\ui_f\data\map\markers\nato\o_air.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_ColIns_AV_14_Hornet_Ins_ALiVE_OPTRE_01";
                    };
                    class Unit1 {
                        position[] = {11,-14,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_ColIns_AV_14_Hornet_Ins_ALiVE_OPTRE_01";
                    };
                    class Unit2 {
                        position[] = {-11,-14,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_ColIns_AV_14_Hornet_Ins_ALiVE_OPTRE_01";
                    };
                };

                class o_colins_air_fixed_cas_optre {
                    name = "Fixed CAS";
                    side = 0;
                    faction = "O_ColIns_OPTRE";
                    icon = "\A3\ui_f\data\map\markers\nato\o_air.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_ColIns_MAKO_Drone_ALiVE_OPTRE_01";
                    };
                };

            };


        };

    };
};


class CBA_Extended_EventHandlers_base;

class CfgVehicles {

    class OPTRE_Ins_ER_Warlord;
    class OPTRE_Ins_ER_Warlord_OCimport_01 : OPTRE_Ins_ER_Warlord { scope = 0; class EventHandlers; };
    class OPTRE_Ins_ER_Warlord_OCimport_02 : OPTRE_Ins_ER_Warlord_OCimport_01 { class EventHandlers; };

    class OPTRE_Ins_ER_Hacker;
    class OPTRE_Ins_ER_Hacker_OCimport_01 : OPTRE_Ins_ER_Hacker { scope = 0; class EventHandlers; };
    class OPTRE_Ins_ER_Hacker_OCimport_02 : OPTRE_Ins_ER_Hacker_OCimport_01 { class EventHandlers; };

    class OPTRE_Ins_ER_Terrorist;
    class OPTRE_Ins_ER_Terrorist_OCimport_01 : OPTRE_Ins_ER_Terrorist { scope = 0; class EventHandlers; };
    class OPTRE_Ins_ER_Terrorist_OCimport_02 : OPTRE_Ins_ER_Terrorist_OCimport_01 { class EventHandlers; };

    class OPTRE_Ins_ER_Assassin;
    class OPTRE_Ins_ER_Assassin_OCimport_01 : OPTRE_Ins_ER_Assassin { scope = 0; class EventHandlers; };
    class OPTRE_Ins_ER_Assassin_OCimport_02 : OPTRE_Ins_ER_Assassin_OCimport_01 { class EventHandlers; };

    class OPTRE_Ins_ER_Militia_MG;
    class OPTRE_Ins_ER_Militia_MG_OCimport_01 : OPTRE_Ins_ER_Militia_MG { scope = 0; class EventHandlers; };
    class OPTRE_Ins_ER_Militia_MG_OCimport_02 : OPTRE_Ins_ER_Militia_MG_OCimport_01 { class EventHandlers; };

    class OPTRE_Ins_ER_Deserter_GL;
    class OPTRE_Ins_ER_Deserter_GL_OCimport_01 : OPTRE_Ins_ER_Deserter_GL { scope = 0; class EventHandlers; };
    class OPTRE_Ins_ER_Deserter_GL_OCimport_02 : OPTRE_Ins_ER_Deserter_GL_OCimport_01 { class EventHandlers; };

    class OPTRE_Ins_ER_Farmer;
    class OPTRE_Ins_ER_Farmer_OCimport_01 : OPTRE_Ins_ER_Farmer { scope = 0; class EventHandlers; };
    class OPTRE_Ins_ER_Farmer_OCimport_02 : OPTRE_Ins_ER_Farmer_OCimport_01 { class EventHandlers; };

    class OPTRE_Ins_ER_Rebel_AT;
    class OPTRE_Ins_ER_Rebel_AT_OCimport_01 : OPTRE_Ins_ER_Rebel_AT { scope = 0; class EventHandlers; };
    class OPTRE_Ins_ER_Rebel_AT_OCimport_02 : OPTRE_Ins_ER_Rebel_AT_OCimport_01 { class EventHandlers; };

    class OPTRE_Ins_ER_Insurgent_BR;
    class OPTRE_Ins_ER_Insurgent_BR_OCimport_01 : OPTRE_Ins_ER_Insurgent_BR { scope = 0; class EventHandlers; };
    class OPTRE_Ins_ER_Insurgent_BR_OCimport_02 : OPTRE_Ins_ER_Insurgent_BR_OCimport_01 { class EventHandlers; };

    class OPTRE_Ins_ER_Guerilla_AR;
    class OPTRE_Ins_ER_Guerilla_AR_OCimport_01 : OPTRE_Ins_ER_Guerilla_AR { scope = 0; class EventHandlers; };
    class OPTRE_Ins_ER_Guerilla_AR_OCimport_02 : OPTRE_Ins_ER_Guerilla_AR_OCimport_01 { class EventHandlers; };

    class OPTRE_Ins_ER_Surgeon;
    class OPTRE_Ins_ER_Surgeon_OCimport_01 : OPTRE_Ins_ER_Surgeon { scope = 0; class EventHandlers; };
    class OPTRE_Ins_ER_Surgeon_OCimport_02 : OPTRE_Ins_ER_Surgeon_OCimport_01 { class EventHandlers; };

    class OPTRE_M274_ATV_Ins;
    class OPTRE_M274_ATV_Ins_OCimport_01 : OPTRE_M274_ATV_Ins { scope = 0; class EventHandlers; };
    class OPTRE_M274_ATV_Ins_OCimport_02 : OPTRE_M274_ATV_Ins_OCimport_01 { scope = 0; class EventHandlers; };

    class OPTRE_M12_FAV_ins;
    class OPTRE_M12_FAV_ins_OCimport_01 : OPTRE_M12_FAV_ins { scope = 0; class EventHandlers; class Turrets; };
    class OPTRE_M12_FAV_ins_OCimport_02 : OPTRE_M12_FAV_ins_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class CargoGunner_1;
            class CargoTurret_02;
            class CargoTurret_03;
        };
    };

    class OPTRE_m1015_mule_ins;
    class OPTRE_m1015_mule_ins_OCimport_01 : OPTRE_m1015_mule_ins { scope = 0; class EventHandlers; class Turrets; };
    class OPTRE_m1015_mule_ins_OCimport_02 : OPTRE_m1015_mule_ins_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class CargoTurret_01;
            class CargoTurret_02;
        };
    };

    class OPTRE_M12_LRV_ins;
    class OPTRE_M12_LRV_ins_OCimport_01 : OPTRE_M12_LRV_ins { scope = 0; class EventHandlers; class Turrets; };
    class OPTRE_M12_LRV_ins_OCimport_02 : OPTRE_M12_LRV_ins_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class CargoGunner_1;
            class MainTurret;
        };
    };

    class OPTRE_M12A1_LRV_ins;
    class OPTRE_M12A1_LRV_ins_OCimport_01 : OPTRE_M12A1_LRV_ins { scope = 0; class EventHandlers; class Turrets; };
    class OPTRE_M12A1_LRV_ins_OCimport_02 : OPTRE_M12A1_LRV_ins_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class CargoGunner_1;
            class MainTurret;
        };
    };

    class OPTRE_M12R_AA_ins;
    class OPTRE_M12R_AA_ins_OCimport_01 : OPTRE_M12R_AA_ins { scope = 0; class EventHandlers; class Turrets; };
    class OPTRE_M12R_AA_ins_OCimport_02 : OPTRE_M12R_AA_ins_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class CargoGunner_1;
            class MainTurret;
        };
    };

    class OPTRE_M914_RV_ins;
    class OPTRE_M914_RV_ins_OCimport_01 : OPTRE_M914_RV_ins { scope = 0; class EventHandlers; class Turrets; };
    class OPTRE_M914_RV_ins_OCimport_02 : OPTRE_M914_RV_ins_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class CargoGunner_1;
        };
    };

    class OPTRE_M12_ins_APC;
    class OPTRE_M12_ins_APC_OCimport_01 : OPTRE_M12_ins_APC { scope = 0; class EventHandlers; class Turrets; };
    class OPTRE_M12_ins_APC_OCimport_02 : OPTRE_M12_ins_APC_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class CargoGunner_1;
            class CargoTurret_02;
        };
    };

    class OPTRE_M12_ins_MED;
    class OPTRE_M12_ins_MED_OCimport_01 : OPTRE_M12_ins_MED { scope = 0; class EventHandlers; class Turrets; };
    class OPTRE_M12_ins_MED_OCimport_02 : OPTRE_M12_ins_MED_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class CargoGunner_1;
            class CargoTurret_02;
        };
    };

    class OPTRE_mako_drone_CAS_ins;
    class OPTRE_mako_drone_CAS_ins_OCimport_01 : OPTRE_mako_drone_CAS_ins { scope = 0; class EventHandlers; class Turrets; };
    class OPTRE_mako_drone_CAS_ins_OCimport_02 : OPTRE_mako_drone_CAS_ins_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class MainTurret;
        };
    };

    class OPTRE_UNSC_hornet_ins;
    class OPTRE_UNSC_hornet_ins_OCimport_01 : OPTRE_UNSC_hornet_ins { scope = 0; class EventHandlers; class Turrets; };
    class OPTRE_UNSC_hornet_ins_OCimport_02 : OPTRE_UNSC_hornet_ins_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class CargoTurret_01;
            class CargoTurret_02;
            class CargoTurret_03;
            class CargoTurret_04;
            class CargoTurret_05;
            class CargoTurret_06;
        };
    };

    class OPTRE_Pelican_unarmed_ins;
    class OPTRE_Pelican_unarmed_ins_OCimport_01 : OPTRE_Pelican_unarmed_ins { scope = 0; class EventHandlers; class Turrets; };
    class OPTRE_Pelican_unarmed_ins_OCimport_02 : OPTRE_Pelican_unarmed_ins_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class CopilotTurret;
            class CargoTurret_01;
            class CargoTurret_02;
        };
    };

    class OPTRE_Pelican_armed_ins;
    class OPTRE_Pelican_armed_ins_OCimport_01 : OPTRE_Pelican_armed_ins { scope = 0; class EventHandlers; class Turrets; };
    class OPTRE_Pelican_armed_ins_OCimport_02 : OPTRE_Pelican_armed_ins_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class CopilotTurret;
            class CargoTurret_01;
            class CargoTurret_02;
        };
    };

    class OPTRE_Static_M41_Ins;
    class OPTRE_Static_M41_Ins_OCimport_01 : OPTRE_Static_M41_Ins { scope = 0; class EventHandlers; class Turrets; };
    class OPTRE_Static_M41_Ins_OCimport_02 : OPTRE_Static_M41_Ins_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class MainTurret;
        };
    };

    class OPTRE_Static_AA_Ins;
    class OPTRE_Static_AA_Ins_OCimport_01 : OPTRE_Static_AA_Ins { scope = 0; class EventHandlers; class Turrets; };
    class OPTRE_Static_AA_Ins_OCimport_02 : OPTRE_Static_AA_Ins_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class MainTurret;
        };
    };

    class OPTRE_Static_FG75;
    class OPTRE_Static_FG75_OCimport_01 : OPTRE_Static_FG75 { scope = 0; class EventHandlers; class Turrets; };
    class OPTRE_Static_FG75_OCimport_02 : OPTRE_Static_FG75_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class MainTurret;
        };
    };

    class O_Mortar_01_F;
    class O_Mortar_01_F_OCimport_01 : O_Mortar_01_F { scope = 0; class EventHandlers; class Turrets; };
    class O_Mortar_01_F_OCimport_02 : O_Mortar_01_F_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class MainTurret;
        };
    };


    class O_ColIns_Warlord_ALiVE_OPTRE_01 : OPTRE_Ins_ER_Warlord_OCimport_02 {
        author = "Capt. Houlston, L";
        scope = 2;
        scopeCurator = 2;
        displayName = "Warlord [ALiVE]";
        side = 0;
        faction = "O_ColIns_OPTRE";

        identityTypes[] = {"Head_NATO","LanguageGRE_F","Miller","Kerry","EPA_B_Northgate","EPA_B_Hardy","EPA_B_James","EPA_B_McKay","G_IRAN_default"};

        uniformClass = "OPTRE_Ins_ER_jacket_od_surplus";

        linkedItems[] = {"H_Beret_blk","ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch","OPTRE_NVG"};
        respawnlinkedItems[] = {"H_Beret_blk","ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch","OPTRE_NVG"};

        weapons[] = {"optre_hgun_comet_F","OPTRE_Binoculars"};
        respawnWeapons[] = {"optre_hgun_comet_F","OPTRE_Binoculars"};

        magazines[] = {"4Rnd_454Casull","4Rnd_454Casull"};
        respawnMagazines[] = {"4Rnd_454Casull","4Rnd_454Casull"};

        ALiVE_orbatCreator_loadout[] = {{},{},{"optre_hgun_comet_F","","acc_flashlight_pistol","",{"4Rnd_454Casull",4},{},""},{"OPTRE_Ins_ER_jacket_od_surplus",{{"OPTRE_Biofoam",1},{"ACE_MapTools",1},{"ACE_EarPlugs",1},{"ACE_Cellphone",1},{"ACE_Banana",5},{"4Rnd_454Casull",2,4}}},{},{},"H_Beret_blk","",{"OPTRE_Binoculars","","","",{},{},""},{"ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch","OPTRE_NVG"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_ColIns_Hacker_ALiVE_OPTRE_01 : OPTRE_Ins_ER_Hacker_OCimport_02 {
        author = "Capt. Houlston, L";
        scope = 2;
        scopeCurator = 2;
        displayName = "Hacker [ALiVE]";
        side = 0;
        faction = "O_ColIns_OPTRE";

        identityTypes[] = {"Head_NATO","LanguageGRE_F","Miller","Kerry","EPA_B_Northgate","EPA_B_Hardy","EPA_B_James","EPA_B_McKay","G_IRAN_default"};

        uniformClass = "OPTRE_Ins_ER_rolled_jean_orca";

        linkedItems[] = {"V_BandollierB_blk","OPTRE_h_PatrolCap_Green","ItemMap","ItemRadio","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"V_BandollierB_blk","OPTRE_h_PatrolCap_Green","ItemMap","ItemRadio","ItemCompass","ItemWatch"};

        weapons[] = {"OPTRE_M7","OPTRE_M6G_SF"};
        respawnWeapons[] = {"OPTRE_M7","OPTRE_M6G_SF"};

        magazines[] = {"OPTRE_60Rnd_5x23mm_Mag_tracer_yellow","OPTRE_60Rnd_5x23mm_Mag_tracer_yellow"};
        respawnMagazines[] = {"OPTRE_60Rnd_5x23mm_Mag_tracer_yellow","OPTRE_60Rnd_5x23mm_Mag_tracer_yellow"};

        backpack = "OPTRE_ANPRC_521_URF";

        ALiVE_orbatCreator_loadout[] = {{"OPTRE_M7","","","",{"OPTRE_60Rnd_5x23mm_Mag_tracer_yellow",60},{},""},{},{"OPTRE_M6G_SF","","OPTRE_M6G_Flashlight","OPTRE_M6G_Scope",{},{},""},{"OPTRE_Ins_ER_rolled_jean_orca",{{"OPTRE_Biofoam",1},{"ACE_splint",2},{"ACE_EarPlugs",1},{"ACE_MapTools",1},{"ACE_Flashlight_XL50",1}}},{"V_BandollierB_blk",{{"ACE_EarPlugs",1},{"ACE_tourniquet",4},{"ACE_splint",3},{"OPTRE_M9_Frag",1,1},{"OPTRE_48Rnd_5x23mm_JHP_Mag",4,48},{"OPTRE_48Rnd_5x23mm_FMJ_Mag",4,48},{"ACE_M84",1,1},{"SmokeShell",2,1}}},{"OPTRE_ANPRC_521_URF",{{"ACE_fieldDressing",6},{"ACE_elasticBandage",7},{"ACE_packingBandage",8},{"ACE_quikclot",8},{"ACE_Banana",12},{"ACE_UAVBattery",1},{"ACE_tourniquet",1}}},"OPTRE_h_PatrolCap_Green","",{},{"ItemMap","","ItemRadio","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_ColIns_Terroist_ALiVE_OPTRE_01 : OPTRE_Ins_ER_Terrorist_OCimport_02 {
        author = "Capt. Houlston, L";
        scope = 2;
        scopeCurator = 2;
        displayName = "Terroist [ALiVE]";
        side = 0;
        faction = "O_ColIns_OPTRE";

        identityTypes[] = {"Head_NATO","LanguageGRE_F","Miller","Kerry","EPA_B_Northgate","EPA_B_Hardy","EPA_B_James","EPA_B_McKay","G_IRAN_default"};

        uniformClass = "OPTRE_Ins_ER_jacket_surplus_redshirt";

        linkedItems[] = {"V_ALiVE_Suicide_Vest","ItemMap","ItemRadio","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"V_ALiVE_Suicide_Vest","ItemMap","ItemRadio","ItemCompass","ItemWatch"};

        weapons[] = {"OPTRE_M45"};
        respawnWeapons[] = {"OPTRE_M45"};

        magazines[] = {"OPTRE_6Rnd_8Gauge_Pellets","OPTRE_6Rnd_8Gauge_Pellets"};
        respawnMagazines[] = {"OPTRE_6Rnd_8Gauge_Pellets","OPTRE_6Rnd_8Gauge_Pellets"};

        backpack = "B_Carryall_oli";

        ALiVE_orbatCreator_loadout[] = {{"OPTRE_M45","","acc_flashlight","",{"OPTRE_6Rnd_8Gauge_Pellets",6},{},""},{},{},{"OPTRE_Ins_ER_jacket_surplus_redshirt",{{"OPTRE_Biofoam",1},{"ACE_splint",2},{"ACE_tourniquet",1},{"OPTRE_6Rnd_8Gauge_Slugs",1,6},{"OPTRE_M9_Frag",1,1},{"OPTRE_6Rnd_8Gauge_HEDP",1,6}}},{"V_ALiVE_Suicide_Vest",{{"OPTRE_6Rnd_8Gauge_Slugs",2,6},{"OPTRE_6Rnd_8Gauge_HEDP",1,6},{"OPTRE_6Rnd_8Gauge_Pellets",1,6}}},{"B_Carryall_oli",{{"ACE_EarPlugs",1},{"M41_IED_Remote_Mag",4,1}}},"","",{},{"ItemMap","","ItemRadio","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_ColIns_Assassin_ALiVE_OPTRE_01 : OPTRE_Ins_ER_Assassin_OCimport_02 {
        author = "Capt. Houlston, L";
        scope = 2;
        scopeCurator = 2;
        displayName = "Assassin [ALiVE]";
        side = 0;
        faction = "O_ColIns_OPTRE";

        identityTypes[] = {"Head_NATO","LanguageGRE_F","Miller","Kerry","EPA_B_Northgate","EPA_B_Hardy","EPA_B_James","EPA_B_McKay","G_IRAN_default"};

        uniformClass = "OPTRE_Ins_ER_rolled_surplus_black";

        linkedItems[] = {"OPTRE_UNSC_M52A_Armor_Sniper_WDL","H_Watchcap_cbr","ItemMap","ItemRadio","ItemCompass","ItemWatch","ACE_NVG_Gen2"};
        respawnlinkedItems[] = {"OPTRE_UNSC_M52A_Armor_Sniper_WDL","H_Watchcap_cbr","ItemMap","ItemRadio","ItemCompass","ItemWatch","ACE_NVG_Gen2"};

        weapons[] = {"OPTRE_SRM77_S1"};
        respawnWeapons[] = {"OPTRE_SRM77_S1"};

        magazines[] = {"OPTRE_10Rnd_127x99","OPTRE_10Rnd_127x99"};
        respawnMagazines[] = {"OPTRE_10Rnd_127x99","OPTRE_10Rnd_127x99"};

        ALiVE_orbatCreator_loadout[] = {{"OPTRE_SRM77_S1","","acc_flashlight","OPTRE_SRM_Sight",{"OPTRE_10Rnd_127x99",10},{},"bipod_02_F_blk"},{},{},{"OPTRE_Ins_ER_rolled_surplus_black",{{"OPTRE_Biofoam",1},{"OPTRE_M2_Smoke",1,1}}},{"OPTRE_UNSC_M52A_Armor_Sniper_WDL",{{"ACE_EarPlugs",1},{"ACE_Flashlight_MX991",1},{"ACE_MapTools",1},{"ACE_splint",5},{"ACE_tourniquet",4},{"ACE_packingBandage",2},{"ACE_quikclot",2},{"ACE_elasticBandage",2},{"ACE_DAGR",1},{"ACE_RangeCard",1},{"OPTRE_M2_Smoke_Green",1,1},{"OPTRE_10Rnd_127x99",6,10}}},{},"H_Watchcap_cbr","LM_OPCAN_UP_Shemagh",{},{"ItemMap","","ItemRadio","ItemCompass","ItemWatch","ACE_NVG_Gen2"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_ColIns_Militia_MG_ALiVE_OPTRE_01 : OPTRE_Ins_ER_Militia_MG_OCimport_02 {
        author = "Capt. Houlston, L";
        scope = 2;
        scopeCurator = 2;
        displayName = "Militia [MG] [ALiVE]";
        side = 0;
        faction = "O_ColIns_OPTRE";

        identityTypes[] = {"Head_NATO","LanguageGRE_F","Miller","Kerry","EPA_B_Northgate","EPA_B_Hardy","EPA_B_James","EPA_B_McKay","G_IRAN_default"};

        uniformClass = "OPTRE_Ins_ER_rolled_OD_blknblu";

        linkedItems[] = {"LM_OPCAN_CPD_Vest_UP","H_Watchcap_cbr","ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch","ACE_NVG_Gen1"};
        respawnlinkedItems[] = {"LM_OPCAN_CPD_Vest_UP","H_Watchcap_cbr","ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch","ACE_NVG_Gen1"};

        weapons[] = {"OPTRE_M73","OPTRE_Binoculars"};
        respawnWeapons[] = {"OPTRE_M73","OPTRE_Binoculars"};

        magazines[] = {"OPTRE_100Rnd_95x40_Box_Tracer_Yellow","OPTRE_100Rnd_95x40_Box_Tracer_Yellow"};
        respawnMagazines[] = {"OPTRE_100Rnd_95x40_Box_Tracer_Yellow","OPTRE_100Rnd_95x40_Box_Tracer_Yellow"};

        ALiVE_orbatCreator_loadout[] = {{"OPTRE_M73","","","OPTRE_BR45_Scope",{"OPTRE_100Rnd_95x40_Box_Tracer_Yellow",100},{},"bipod_01_F_blk"},{},{},{"OPTRE_Ins_ER_rolled_OD_blknblu",{{"OPTRE_Biofoam",1},{"OPTRE_M9_Frag",2,1},{"OPTRE_M2_Smoke",1,1},{"OPTRE_M2_Smoke_Green",1,1}}},{"LM_OPCAN_CPD_Vest_UP",{{"ACE_quikclot",2},{"ACE_packingBandage",2},{"ACE_elasticBandage",2},{"ACE_fieldDressing",2},{"ACE_Banana",5},{"ACE_EarPlugs",1},{"ACE_MapTools",1},{"ACE_Flashlight_MX991",1},{"ACE_splint",5},{"ACE_tourniquet",4},{"OPTRE_100Rnd_95x40_Box_Tracer_Yellow",3,100}}},{},"H_Watchcap_cbr","",{"OPTRE_Binoculars","","","",{},{},""},{"ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch","ACE_NVG_Gen1"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_ColIns_Deserter_GL_ALiVE_OPTRE_01 : OPTRE_Ins_ER_Deserter_GL_OCimport_02 {
        author = "Capt. Houlston, L";
        scope = 2;
        scopeCurator = 2;
        displayName = "Deserter [GL] [ALiVE]";
        side = 0;
        faction = "O_ColIns_OPTRE";

        identityTypes[] = {"Head_NATO","LanguageGRE_F","Miller","Kerry","EPA_B_Northgate","EPA_B_Hardy","EPA_B_James","EPA_B_McKay","G_IRAN_default"};

        uniformClass = "OPTRE_Ins_ER_rolled_surplus_crimson";

        linkedItems[] = {"OPTRE_UNSC_M52A_Armor_Soft","LM_OPCAN_CH252_AR_W","ItemMap","ItemRadio","ItemCompass","ItemWatch","ACE_NVG_Gen1"};
        respawnlinkedItems[] = {"OPTRE_UNSC_M52A_Armor_Soft","LM_OPCAN_CH252_AR_W","ItemMap","ItemRadio","ItemCompass","ItemWatch","ACE_NVG_Gen1"};

        weapons[] = {"OPTRE_MA37GL"};
        respawnWeapons[] = {"OPTRE_MA37GL"};

        magazines[] = {"OPTRE_32Rnd_762x51_Mag","1Rnd_HE_Grenade_shell","OPTRE_32Rnd_762x51_Mag","1Rnd_HE_Grenade_shell"};
        respawnMagazines[] = {"OPTRE_32Rnd_762x51_Mag","1Rnd_HE_Grenade_shell","OPTRE_32Rnd_762x51_Mag","1Rnd_HE_Grenade_shell"};

        backpack = "B_AssaultPack_rgr";

        ALiVE_orbatCreator_loadout[] = {{"OPTRE_MA37GL","","","",{"OPTRE_32Rnd_762x51_Mag",32},{"1Rnd_HE_Grenade_shell",1},""},{},{},{"OPTRE_Ins_ER_rolled_surplus_crimson",{{"OPTRE_Biofoam",1},{"ACE_Banana",2},{"ACE_packingBandage",6},{"ACE_quikclot",5},{"ACE_elasticBandage",5},{"ACE_EarPlugs",1},{"ACE_Flashlight_MX991",1},{"ACE_MapTools",1},{"ACE_Flashlight_XL50",1},{"ACE_splint",2},{"ACE_tourniquet",2}}},{"OPTRE_UNSC_M52A_Armor_Soft",{{"OPTRE_32Rnd_762x51_Mag",6,32},{"1Rnd_HE_Grenade_shell",5,1}}},{"B_AssaultPack_rgr",{{"ACE_HuntIR_monitor",1},{"ACE_EarPlugs",1},{"OPTRE_M9_Frag",2,1},{"SmokeShell",2,1},{"ACE_HandFlare_Green",2,1},{"1Rnd_HE_Grenade_shell",10,1},{"UGL_FlareWhite_F",1,1},{"UGL_FlareGreen_F",2,1},{"UGL_FlareRed_F",2,1},{"UGL_FlareYellow_F",2,1},{"OPTRE_3Rnd_Smoke_Grenade_shell",2,3},{"ACE_HuntIR_M203",1,1},{"ACE_40mm_Flare_white",2,1}}},"LM_OPCAN_CH252_AR_W","",{},{"ItemMap","","ItemRadio","ItemCompass","ItemWatch","ACE_NVG_Gen1"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_ColIns_Farmer_MA37_ALiVE_OPTRE_01 : OPTRE_Ins_ER_Farmer_OCimport_02 {
        author = "Capt. Houlston, L";
        scope = 2;
        scopeCurator = 2;
        displayName = "Farmer [MA37] [ALiVE]";
        side = 0;
        faction = "O_ColIns_OPTRE";

        identityTypes[] = {"Head_NATO","LanguageGRE_F","Miller","Kerry","EPA_B_Northgate","EPA_B_Hardy","EPA_B_James","EPA_B_McKay","G_IRAN_default"};

        uniformClass = "OPTRE_Ins_ER_jacket_brown_surplus";

        linkedItems[] = {"V_BandollierB_blk","H_Watchcap_khk","ItemMap","ItemRadio","ItemCompass","ItemWatch","ACE_NVG_Gen1"};
        respawnlinkedItems[] = {"V_BandollierB_blk","H_Watchcap_khk","ItemMap","ItemRadio","ItemCompass","ItemWatch","ACE_NVG_Gen1"};

        weapons[] = {"OPTRE_MA37"};
        respawnWeapons[] = {"OPTRE_MA37"};

        magazines[] = {"OPTRE_32Rnd_762x51_Mag","OPTRE_32Rnd_762x51_Mag"};
        respawnMagazines[] = {"OPTRE_32Rnd_762x51_Mag","OPTRE_32Rnd_762x51_Mag"};

        ALiVE_orbatCreator_loadout[] = {{"OPTRE_MA37","","","",{"OPTRE_32Rnd_762x51_Mag",32},{},""},{},{},{"OPTRE_Ins_ER_jacket_brown_surplus",{{"OPTRE_Biofoam",1},{"ACE_tourniquet",2},{"ACE_splint",4},{"ACE_morphine",1},{"ACE_Flashlight_MX991",1}}},{"V_BandollierB_blk",{{"ACE_Banana",1},{"ACE_packingBandage",5},{"ACE_quikclot",5},{"ACE_elasticBandage",5},{"ACE_EarPlugs",1},{"ACE_MapTools",1},{"ACE_tourniquet",2},{"OPTRE_32Rnd_762x51_Mag",6,32}}},{},"H_Watchcap_khk","",{},{"ItemMap","","ItemRadio","ItemCompass","ItemWatch","ACE_NVG_Gen1"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_ColIns_Rebel_AT_ALiVE_OPTRE_01 : OPTRE_Ins_ER_Rebel_AT_OCimport_02 {
        author = "Capt. Houlston, L";
        scope = 2;
        scopeCurator = 2;
        displayName = "Rebel [AT] [ALiVE]";
        side = 0;
        faction = "O_ColIns_OPTRE";

        identityTypes[] = {"Head_NATO","LanguageGRE_F","Miller","Kerry","EPA_B_Northgate","EPA_B_Hardy","EPA_B_James","EPA_B_McKay","G_IRAN_default"};

        uniformClass = "OPTRE_Ins_ER_rolled_surplus_black";

        linkedItems[] = {"V_TacVestIR_blk","H_Bandanna_gry","ItemMap","ItemRadio","ItemCompass","ItemWatch","ACE_NVG_Gen1"};
        respawnlinkedItems[] = {"V_TacVestIR_blk","H_Bandanna_gry","ItemMap","ItemRadio","ItemCompass","ItemWatch","ACE_NVG_Gen1"};

        weapons[] = {"OPTRE_M7","OPTRE_M41_SSR","OPTRE_Binoculars"};
        respawnWeapons[] = {"OPTRE_M7","OPTRE_M41_SSR","OPTRE_Binoculars"};

        magazines[] = {"OPTRE_60Rnd_5x23mm_Mag","OPTRE_M41_Twin_HEAT","OPTRE_60Rnd_5x23mm_Mag"};
        respawnMagazines[] = {"OPTRE_60Rnd_5x23mm_Mag","OPTRE_M41_Twin_HEAT","OPTRE_60Rnd_5x23mm_Mag"};

        backpack = "OPTRE_B_TacticalPack_blk_M41";

        ALiVE_orbatCreator_loadout[] = {{"OPTRE_M7","","","",{"OPTRE_60Rnd_5x23mm_Mag",60},{},""},{"OPTRE_M41_SSR","","","",{"OPTRE_M41_Twin_HEAT",2},{},""},{},{"OPTRE_Ins_ER_rolled_surplus_black",{{"OPTRE_Biofoam",1}}},{"V_TacVestIR_blk",{{"ACE_tourniquet",4},{"ACE_Banana",1},{"ACE_EarPlugs",1},{"ACE_Flashlight_MX991",1},{"ACE_MapTools",1},{"ACE_morphine",1},{"ACE_splint",5},{"OPTRE_M9_Frag",2,1},{"OPTRE_M2_Smoke",1,1},{"OPTRE_M2_Smoke_Green",1,1},{"OPTRE_48Rnd_5x23mm_FMJ_Mag",3,48},{"OPTRE_48Rnd_5x23mm_JHP_Mag",5,48},{"SmokeShell",1,1}}},{"OPTRE_B_TacticalPack_blk_M41",{{"OPTRE_M41_Twin_HEAT",1,2},{"OPTRE_M41_Twin_HEAP",1,2}}},"H_Bandanna_gry","LM_OPCAN_URB_Shemagh",{"OPTRE_Binoculars","","","",{},{},""},{"ItemMap","","ItemRadio","ItemCompass","ItemWatch","ACE_NVG_Gen1"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_ColIns_Hunter_ALiVE_OPTRE_01 : OPTRE_Ins_ER_Insurgent_BR_OCimport_02 {
        author = "Capt. Houlston, L";
        scope = 2;
        scopeCurator = 2;
        displayName = "Hunter [ALiVE]";
        side = 0;
        faction = "O_ColIns_OPTRE";

        identityTypes[] = {"Head_NATO","LanguageGRE_F","Miller","Kerry","EPA_B_Northgate","EPA_B_Hardy","EPA_B_James","EPA_B_McKay","G_IRAN_default"};

        uniformClass = "OPTRE_Ins_ER_uniform_GGgrey";

        linkedItems[] = {"OPTRE_UNSC_M52A_Armor_Soft","H_Booniehat_oli","ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch","ACE_NVG_Gen1"};
        respawnlinkedItems[] = {"OPTRE_UNSC_M52A_Armor_Soft","H_Booniehat_oli","ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch","ACE_NVG_Gen1"};

        weapons[] = {"OPTRE_M392_DMR","OPTRE_Binoculars"};
        respawnWeapons[] = {"OPTRE_M392_DMR","OPTRE_Binoculars"};

        magazines[] = {"OPTRE_15Rnd_762x51_Mag","OPTRE_15Rnd_762x51_Mag"};
        respawnMagazines[] = {"OPTRE_15Rnd_762x51_Mag","OPTRE_15Rnd_762x51_Mag"};

        backpack = "B_AssaultPack_blk";

        ALiVE_orbatCreator_loadout[] = {{"OPTRE_M392_DMR","","OPTRE_BMR_Laser","OPTRE_BR45_Scope",{"OPTRE_15Rnd_762x51_Mag",15},{},"bipod_02_F_blk"},{},{},{"OPTRE_Ins_ER_uniform_GGgrey",{{"OPTRE_Biofoam",1},{"ACE_tourniquet",4},{"ACE_splint",4},{"ACE_EarPlugs",1},{"ACE_quikclot",3},{"ACE_elasticBandage",3},{"ACE_packingBandage",3},{"ACE_Banana",1},{"OPTRE_M2_Smoke",1,1}}},{"OPTRE_UNSC_M52A_Armor_Soft",{{"OPTRE_M9_Frag",2,1},{"OPTRE_M2_Smoke_Green",1,1},{"OPTRE_15Rnd_762x51_Mag",4,15}}},{"B_AssaultPack_blk",{{"ACE_SpottingScope",1},{"ACE_Tripod",1},{"ACE_EntrenchingTool",1}}},"H_Booniehat_oli","",{"OPTRE_Binoculars","","","",{},{},""},{"ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch","ACE_NVG_Gen1"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_ColIns_Signaler_MA37_OPTRE_01 : OPTRE_Ins_ER_Guerilla_AR_OCimport_02 {
        author = "Capt. Houlston, L";
        scope = 2;
        scopeCurator = 2;
        displayName = "Signaler [MA37]";
        side = 0;
        faction = "O_ColIns_OPTRE";

        identityTypes[] = {"Head_NATO","LanguageGRE_F","Miller","Kerry","EPA_B_Northgate","EPA_B_Hardy","EPA_B_James","EPA_B_McKay","G_IRAN_default"};

        uniformClass = "OPTRE_Ins_ER_rolled_surplus_black";

        linkedItems[] = {"LM_OPCAN_CPD_Rig","OPTRE_Ins_URF_Helmet3","ItemMap","ItemRadio","ItemCompass","ItemWatch","ACE_NVG_Gen1"};
        respawnlinkedItems[] = {"LM_OPCAN_CPD_Rig","OPTRE_Ins_URF_Helmet3","ItemMap","ItemRadio","ItemCompass","ItemWatch","ACE_NVG_Gen1"};

        weapons[] = {"OPTRE_BR55HB","OPTRE_M319s"};
        respawnWeapons[] = {"OPTRE_BR55HB","OPTRE_M319s"};

        magazines[] = {"OPTRE_36Rnd_95x40_Mag","1Rnd_HE_Grenade_shell","OPTRE_36Rnd_95x40_Mag","1Rnd_HE_Grenade_shell"};
        respawnMagazines[] = {"OPTRE_36Rnd_95x40_Mag","1Rnd_HE_Grenade_shell","OPTRE_36Rnd_95x40_Mag","1Rnd_HE_Grenade_shell"};

        ALiVE_orbatCreator_loadout[] = {{"OPTRE_BR55HB","","acc_flashlight","OPTRE_BR45_Scope",{"OPTRE_36Rnd_95x40_Mag",36},{},""},{},{"OPTRE_M319s","","","",{"1Rnd_HE_Grenade_shell",1},{},""},{"OPTRE_Ins_ER_rolled_surplus_black",{{"OPTRE_Biofoam",1},{"ACE_EarPlugs",1},{"ACE_fieldDressing",4},{"ACE_elasticBandage",4},{"ACE_packingBandage",4},{"ACE_Banana",1},{"ACE_tourniquet",4},{"OPTRE_M9_Frag",2,1}}},{"LM_OPCAN_CPD_Rig",{{"OPTRE_M2_Smoke",1,1},{"OPTRE_M2_Smoke_Green",1,1},{"OPTRE_36Rnd_95x40_Mag",6,36},{"UGL_FlareYellow_F",4,1},{"UGL_FlareRed_F",4,1},{"UGL_FlareGreen_F",4,1},{"UGL_FlareWhite_F",4,1}}},{},"OPTRE_Ins_URF_Helmet3","",{},{"ItemMap","","ItemRadio","ItemCompass","ItemWatch","ACE_NVG_Gen1"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_ColIns_Surgeon_ALiVE_OPTRE_01 : OPTRE_Ins_ER_Surgeon_OCimport_02 {
        author = "Capt. Houlston, L";
        scope = 2;
        scopeCurator = 2;
        displayName = "Surgeon [ALiVE]";
        side = 0;
        faction = "O_ColIns_OPTRE";

        identityTypes[] = {"Head_NATO","LanguageGRE_F","Miller","Kerry","EPA_B_Northgate","EPA_B_Hardy","EPA_B_James","EPA_B_McKay","G_IRAN_default"};

        uniformClass = "OPTRE_Ins_ER_jacket_surgeon2";

        linkedItems[] = {"V_BandollierB_blk","H_MilCap_gry","ItemMap","ItemRadio","ItemCompass","ItemWatch","ACE_NVG_Gen1"};
        respawnlinkedItems[] = {"V_BandollierB_blk","H_MilCap_gry","ItemMap","ItemRadio","ItemCompass","ItemWatch","ACE_NVG_Gen1"};

        weapons[] = {"OPTRE_M6G_SF"};
        respawnWeapons[] = {"OPTRE_M6G_SF"};

        magazines[] = {"OPTRE_8Rnd_127x40_Mag_Tracer","OPTRE_8Rnd_127x40_Mag_Tracer"};
        respawnMagazines[] = {"OPTRE_8Rnd_127x40_Mag_Tracer","OPTRE_8Rnd_127x40_Mag_Tracer"};

        backpack = "OPTRE_B_TacticalPack_blk_Medic";

        ALiVE_orbatCreator_loadout[] = {{},{},{"OPTRE_M6G_SF","","OPTRE_M6G_Flashlight","OPTRE_M6G_Scope",{"OPTRE_8Rnd_127x40_Mag_Tracer",8},{},""},{"OPTRE_Ins_ER_jacket_surgeon2",{{"OPTRE_Biofoam",1},{"OPTRE_8Rnd_127x40_Mag_Tracer",3,8}}},{"V_BandollierB_blk",{{"ACE_bodyBag",2},{"ACE_CableTie",10},{"ACE_EntrenchingTool",1},{"ACE_Banana",2},{"ACE_Flashlight_MX991",1},{"OPTRE_M2_Smoke",1,1},{"OPTRE_M2_Smoke_Orange",1,1},{"OPTRE_M2_Smoke_Green",1,1}}},{"OPTRE_B_TacticalPack_blk_Medic",{{"OPTRE_Medigel",10},{"OPTRE_MedKit",1},{"ACE_surgicalKit",1},{"ACE_tourniquet",8},{"ACE_splint",10},{"ACE_personalAidKit",1},{"ACE_epinephrine",10},{"ACE_morphine",10},{"ACE_adenosine",5},{"ACE_bloodIV",2},{"ACE_bloodIV_250",2},{"ACE_bloodIV_500",2},{"ACE_quikclot",10},{"ACE_packingBandage",10},{"ACE_elasticBandage",10},{"ACE_fieldDressing",10},{"ACE_Banana",1},{"ACE_EarPlugs",1},{"ACE_Flashlight_MX991",1}}},"H_MilCap_gry","",{},{"ItemMap","","ItemRadio","ItemCompass","ItemWatch","ACE_NVG_Gen1"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_ColIns_Monke_Tamer_ALiVE_OPTRE_01 : OPTRE_Ins_ER_Surgeon_OCimport_02 {
        author = "Capt. Houlston, L";
        scope = 2;
        scopeCurator = 2;
        displayName = "Monke Tamer [ALiVE]";
        side = 0;
        faction = "O_ColIns_OPTRE";

        identityTypes[] = {"Head_NATO","LanguageGRE_F","Miller","Kerry","EPA_B_Northgate","EPA_B_Hardy","EPA_B_James","EPA_B_McKay","G_IRAN_default"};

        uniformClass = "OPTRE_Ins_ER_jacket_surgeon2";

        linkedItems[] = {"V_BandollierB_blk","H_MilCap_gry","ItemMap","ItemRadio","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"V_BandollierB_blk","H_MilCap_gry","ItemMap","ItemRadio","ItemCompass","ItemWatch"};

        weapons[] = {"OPTRE_M6G_SF"};
        respawnWeapons[] = {"OPTRE_M6G_SF"};

        magazines[] = {"OPTRE_8Rnd_127x40_Mag_Tracer","OPTRE_8Rnd_127x40_Mag_Tracer"};
        respawnMagazines[] = {"OPTRE_8Rnd_127x40_Mag_Tracer","OPTRE_8Rnd_127x40_Mag_Tracer"};

        backpack = "OPTRE_B_TacticalPack_blk_Medic";

        ALiVE_orbatCreator_loadout[] = {{},{},{"OPTRE_M6G_SF","","OPTRE_M6G_Flashlight","OPTRE_M6G_Scope",{"OPTRE_8Rnd_127x40_Mag_Tracer",8},{},""},{"OPTRE_Ins_ER_jacket_surgeon2",{{"OPTRE_Biofoam",1},{"ACE_Banana",10},{"OPTRE_8Rnd_127x40_Mag_Tracer",3,8}}},{"V_BandollierB_blk",{{"ACE_Banana",68},{"OPTRE_M2_Smoke",1,1},{"OPTRE_M2_Smoke_Orange",1,1},{"OPTRE_M2_Smoke_Green",1,1}}},{"OPTRE_B_TacticalPack_blk_Medic",{{"OPTRE_Medigel",10},{"OPTRE_MedKit",1},{"ACE_Banana",160}}},"H_MilCap_gry","",{},{"ItemMap","","ItemRadio","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_ColIns_M274_Mongoose_Ins_ALiVE_OPTRE_01 : OPTRE_M274_ATV_Ins_OCimport_02 {
        author = "Capt. Houlston, L";
        scope = 2;
        scopeCurator = 2;
        displayName = "M274 Mongoose [Ins] [ALiVE]";
        side = 0;
        faction = "O_ColIns_OPTRE";
        crew = "O_ColIns_Hunter_ALiVE_OPTRE_01";


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_ColIns_M12_FAV_Ins_ALiVE_OPTRE_01 : OPTRE_M12_FAV_ins_OCimport_02 {
        author = "Capt. Houlston, L";
        scope = 2;
        scopeCurator = 2;
        displayName = "M12-FAV [Ins] [ALiVE]";
        side = 0;
        faction = "O_ColIns_OPTRE";
        crew = "O_ColIns_Deserter_GL_ALiVE_OPTRE_01";

        class Turrets : Turrets {
            class CargoGunner_1 : CargoGunner_1 { gunnerType = "O_ColIns_Farmer_MA37_ALiVE_OPTRE_01"; };
            class CargoTurret_02 : CargoTurret_02 { gunnerType = "O_ColIns_Rebel_AT_ALiVE_OPTRE_01"; };
            class CargoTurret_03 : CargoTurret_03 { gunnerType = "O_ColIns_Signaler_MA37_OPTRE_01"; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_ColIns_M1015_Mule_Ins_ALiVE_OPTRE_01 : OPTRE_m1015_mule_ins_OCimport_02 {
        author = "Capt. Houlston, L";
        scope = 2;
        scopeCurator = 2;
        displayName = "M1015 Mule [Ins] [ALiVE]";
        side = 0;
        faction = "O_ColIns_OPTRE";
        crew = "O_ColIns_Deserter_GL_ALiVE_OPTRE_01";

        class Turrets : Turrets {
            class CargoTurret_01 : CargoTurret_01 { gunnerType = "O_ColIns_Militia_MG_ALiVE_OPTRE_01"; };
            class CargoTurret_02 : CargoTurret_02 { gunnerType = "O_ColIns_Hunter_ALiVE_OPTRE_01"; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;_unit setObjectTextureGlobal [0,'\A3\soft_f_beta\Truck_02\Data\Truck_02_kab_opfor_co.paa'];_unit setObjectTextureGlobal [1,'\A3\soft_f_beta\Truck_02\Data\Truck_02_kuz_OPFOR_co.paa'];_unit setObjectTextureGlobal [2,'\a3\soft_f_beta\truck_02\data\truck_02_int_co.paa'];};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_texture = "Opfor";

    };

    class O_ColIns_M12_LRV_MG_Ins_ALiVE_OPTRE_01 : OPTRE_M12_LRV_ins_OCimport_02 {
        author = "Capt. Houlston, L";
        scope = 2;
        scopeCurator = 2;
        displayName = "M12 LRV [MG] [Ins] [ALiVE]";
        side = 0;
        faction = "O_ColIns_OPTRE";
        crew = "O_ColIns_Deserter_GL_ALiVE_OPTRE_01";

        class Turrets : Turrets {
            class CargoGunner_1 : CargoGunner_1 { gunnerType = "O_ColIns_Signaler_MA37_OPTRE_01"; };
            class MainTurret : MainTurret { gunnerType = "O_ColIns_Farmer_MA37_ALiVE_OPTRE_01"; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_ColIns_M12A1_LRV_ATGM_Ins_ALiVE_OPTRE_01 : OPTRE_M12A1_LRV_ins_OCimport_02 {
        author = "Capt. Houlston, L";
        scope = 2;
        scopeCurator = 2;
        displayName = "M12A1 LRV [ATGM] [Ins] [ALiVE]";
        side = 0;
        faction = "O_ColIns_OPTRE";
        crew = "O_ColIns_Farmer_MA37_ALiVE_OPTRE_01";

        class Turrets : Turrets {
            class CargoGunner_1 : CargoGunner_1 { gunnerType = "O_ColIns_Signaler_MA37_OPTRE_01"; };
            class MainTurret : MainTurret { gunnerType = "O_ColIns_Hunter_ALiVE_OPTRE_01"; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_ColIns_M12R_AA_Ins_ALiVE_OPTRE_01 : OPTRE_M12R_AA_ins_OCimport_02 {
        author = "Capt. Houlston, L";
        scope = 2;
        scopeCurator = 2;
        displayName = "M12R [AA] [Ins] [ALiVE]";
        side = 0;
        faction = "O_ColIns_OPTRE";
        crew = "O_ColIns_Farmer_MA37_ALiVE_OPTRE_01";

        class Turrets : Turrets {
            class CargoGunner_1 : CargoGunner_1 { gunnerType = "O_ColIns_Hunter_ALiVE_OPTRE_01"; };
            class MainTurret : MainTurret { gunnerType = "O_ColIns_Signaler_MA37_OPTRE_01"; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_ColIns_M914_RH_Ins_ALiVE_OPTRE_01 : OPTRE_M914_RV_ins_OCimport_02 {
        author = "Capt. Houlston, L";
        scope = 2;
        scopeCurator = 2;
        displayName = "M914 [RH] [Ins] [ALiVE]";
        side = 0;
        faction = "O_ColIns_OPTRE";
        crew = "O_ColIns_Deserter_GL_ALiVE_OPTRE_01";

        class Turrets : Turrets {
            class CargoGunner_1 : CargoGunner_1 { gunnerType = "O_ColIns_Signaler_MA37_OPTRE_01"; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_ColIns_M12_APC_Ins_ALiVE_OPTRE_01 : OPTRE_M12_ins_APC_OCimport_02 {
        author = "Capt. Houlston, L";
        scope = 2;
        scopeCurator = 2;
        displayName = "M12 APC [Ins] [ALiVE]";
        side = 0;
        faction = "O_ColIns_OPTRE";
        crew = "O_ColIns_Hunter_ALiVE_OPTRE_01";

        class Turrets : Turrets {
            class CargoGunner_1 : CargoGunner_1 { gunnerType = "O_ColIns_Deserter_GL_ALiVE_OPTRE_01"; };
            class CargoTurret_02 : CargoTurret_02 { gunnerType = "O_ColIns_Militia_MG_ALiVE_OPTRE_01"; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_ColIns_M12_Medical_APC_Ins_ALiVE_OPTRE_01 : OPTRE_M12_ins_MED_OCimport_02 {
        author = "Capt. Houlston, L";
        scope = 2;
        scopeCurator = 2;
        displayName = "M12 Medical APC [Ins] [ALiVE]";
        side = 0;
        faction = "O_ColIns_OPTRE";
        crew = "O_ColIns_Deserter_GL_ALiVE_OPTRE_01";

        class Turrets : Turrets {
            class CargoGunner_1 : CargoGunner_1 { gunnerType = "O_ColIns_Hunter_ALiVE_OPTRE_01"; };
            class CargoTurret_02 : CargoTurret_02 { gunnerType = "O_ColIns_Militia_MG_ALiVE_OPTRE_01"; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_ColIns_MAKO_Drone_ALiVE_OPTRE_01 : OPTRE_mako_drone_CAS_ins_OCimport_02 {
        author = "Capt. Houlston, L";
        scope = 2;
        scopeCurator = 2;
        displayName = "MAKO Drone [ALiVE]";
        side = 0;
        faction = "O_ColIns_OPTRE";
        crew = "O_ColIns_Deserter_GL_ALiVE_OPTRE_01";

        class Turrets : Turrets {
            class MainTurret : MainTurret { gunnerType = "O_ColIns_Deserter_GL_ALiVE_OPTRE_01"; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_ColIns_AV_14_Hornet_Ins_ALiVE_OPTRE_01 : OPTRE_UNSC_hornet_ins_OCimport_02 {
        author = "Capt. Houlston, L";
        scope = 2;
        scopeCurator = 2;
        displayName = "AV-14 Hornet [Ins] [ALiVE]";
        side = 0;
        faction = "O_ColIns_OPTRE";
        crew = "O_ColIns_Deserter_GL_ALiVE_OPTRE_01";

        class Turrets : Turrets {
            class CargoTurret_01 : CargoTurret_01 { gunnerType = "O_ColIns_Rebel_AT_ALiVE_OPTRE_01"; };
            class CargoTurret_02 : CargoTurret_02 { gunnerType = "O_ColIns_Rebel_AT_ALiVE_OPTRE_01"; };
            class CargoTurret_03 : CargoTurret_03 { gunnerType = ""; };
            class CargoTurret_04 : CargoTurret_04 { gunnerType = ""; };
            class CargoTurret_05 : CargoTurret_05 { gunnerType = ""; };
            class CargoTurret_06 : CargoTurret_06 { gunnerType = ""; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_ColIns_D77H_TCI_Pelican_Ins_ALiVE_OPTRE_01 : OPTRE_Pelican_unarmed_ins_OCimport_02 {
        author = "Capt. Houlston, L";
        scope = 2;
        scopeCurator = 2;
        displayName = "D77H-TCI Pelican [Ins] [ALiVE]";
        side = 0;
        faction = "O_ColIns_OPTRE";
        crew = "O_ColIns_Deserter_GL_ALiVE_OPTRE_01";

        class Turrets : Turrets {
            class CopilotTurret : CopilotTurret { gunnerType = "O_ColIns_Hunter_ALiVE_OPTRE_01"; };
            class CargoTurret_01 : CargoTurret_01 { gunnerType = "O_ColIns_Militia_MG_ALiVE_OPTRE_01"; };
            class CargoTurret_02 : CargoTurret_02 { gunnerType = "O_ColIns_Signaler_MA37_OPTRE_01"; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_ColIns_D77H_TCI_AV_Pelican_Ins_ALiVE_OPTRE_01 : OPTRE_Pelican_armed_ins_OCimport_02 {
        author = "Capt. Houlston, L";
        scope = 2;
        scopeCurator = 2;
        displayName = "D77H-TCI/AV Pelican [Ins] [ALiVE]";
        side = 0;
        faction = "O_ColIns_OPTRE";
        crew = "O_ColIns_Deserter_GL_ALiVE_OPTRE_01";

        class Turrets : Turrets {
            class CopilotTurret : CopilotTurret { gunnerType = "O_ColIns_Deserter_GL_ALiVE_OPTRE_01"; };
            class CargoTurret_01 : CargoTurret_01 { gunnerType = "O_ColIns_Militia_MG_ALiVE_OPTRE_01"; };
            class CargoTurret_02 : CargoTurret_02 { gunnerType = "O_ColIns_Militia_MG_ALiVE_OPTRE_01"; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_ColIns_M41_LAAG_Turret_Ins_ALiVE_OPTRE_01 : OPTRE_Static_M41_Ins_OCimport_02 {
        author = "Capt. Houlston, L";
        scope = 2;
        scopeCurator = 2;
        displayName = "M41 LAAG Turret [Ins] [ALiVE]";
        side = 0;
        faction = "O_ColIns_OPTRE";
        crew = "OPTRE_Ins_URF_Rifleman_AR";

        class Turrets : Turrets {
            class MainTurret : MainTurret { gunnerType = ""; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_ColIns_M79_AA_Turret_Ins_ALiVE_OPTRE_01 : OPTRE_Static_AA_Ins_OCimport_02 {
        author = "Capt. Houlston, L";
        scope = 2;
        scopeCurator = 2;
        displayName = "M79 AA Turret [Ins] [ALiVE]";
        side = 0;
        faction = "O_ColIns_OPTRE";
        crew = "OPTRE_Ins_URF_Rifleman_AR";

        class Turrets : Turrets {
            class MainTurret : MainTurret { gunnerType = ""; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_ColIns_FG75_AT_Gun_Ins_ALiVE_OPTRE_01 : OPTRE_Static_FG75_OCimport_02 {
        author = "Capt. Houlston, L";
        scope = 2;
        scopeCurator = 2;
        displayName = "FG75 AT Gun [Ins] [ALiVE]";
        side = 0;
        faction = "O_ColIns_OPTRE";
        crew = "OPTRE_Ins_URF_Engineer";

        class Turrets : Turrets {
            class MainTurret : MainTurret { gunnerType = ""; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_ColIns_Mk6_Mortar_Ins_ALiVE_OPTRE_01 : O_Mortar_01_F_OCimport_02 {
        author = "Capt. Houlston, L";
        scope = 2;
        scopeCurator = 2;
        displayName = "Mk6 Mortar [Ins] [ALiVE]";
        side = 0;
        faction = "O_ColIns_OPTRE";
        crew = "O_Soldier_F";

        class Turrets : Turrets {
            class MainTurret : MainTurret { gunnerType = "O_ColIns_Hunter_ALiVE_OPTRE_01"; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

};