//////////////////////////////////////////////////////////////////////////////////
// Config Automatically Generated by ALiVE ORBAT Creator
// Generated with Arma 3 version 204.147719 on Stable branch
// Generated with ALiVE version 1.14.1.2105061
//////////////////////////////////////////////////////////////////////////////////

class CfgFactionClasses {
    class C_ColCiv_OPTRE {
        displayName = "Civilian [OPTRE] [ALiVE]";
        side = 3;
        flag = "";
        icon = "";
        priority = 0;
    };
};

class CfgGroups {
    class Civilian {

        class C_ColCiv_OPTRE {
            name = "Civilian [OPTRE] [ALiVE]";

            class Infantry {
                name = "Infantry";

            };

            class SpecOps {
                name = "Special Forces";

            };

            class Motorized {
                name = "Motorized Infantry";

            };

            class Motorized_MTP {
                name = "Motorized Infantry (MTP)";

            };

            class Support {
                name = "Support Infantry";

            };

            class Mechanized {
                name = "Mechanized Infantry";

            };

            class Armored {
                name = "Armor";

            };

            class Artillery {
                name = "Artillery";

            };

            class Naval {
                name = "Naval";

            };

            class Air {
                name = "Air";

            };


        };

    };
};


class CBA_Extended_EventHandlers_base;

class CfgVehicles {

    class C_man_1;
    class C_man_1_OCimport_01 : C_man_1 { scope = 0; class EventHandlers; };
    class C_man_1_OCimport_02 : C_man_1_OCimport_01 { class EventHandlers; };

    class C_man_1_1_F;
    class C_man_1_1_F_OCimport_01 : C_man_1_1_F { scope = 0; class EventHandlers; };
    class C_man_1_1_F_OCimport_02 : C_man_1_1_F_OCimport_01 { class EventHandlers; };

    class C_man_polo_3_F;
    class C_man_polo_3_F_OCimport_01 : C_man_polo_3_F { scope = 0; class EventHandlers; };
    class C_man_polo_3_F_OCimport_02 : C_man_polo_3_F_OCimport_01 { class EventHandlers; };

    class C_man_pilot_F;
    class C_man_pilot_F_OCimport_01 : C_man_pilot_F { scope = 0; class EventHandlers; };
    class C_man_pilot_F_OCimport_02 : C_man_pilot_F_OCimport_01 { class EventHandlers; };

    class C_journalist_F;
    class C_journalist_F_OCimport_01 : C_journalist_F { scope = 0; class EventHandlers; };
    class C_journalist_F_OCimport_02 : C_journalist_F_OCimport_01 { class EventHandlers; };

    class C_Man_ConstructionWorker_01_Blue_F;
    class C_Man_ConstructionWorker_01_Blue_F_OCimport_01 : C_Man_ConstructionWorker_01_Blue_F { scope = 0; class EventHandlers; };
    class C_Man_ConstructionWorker_01_Blue_F_OCimport_02 : C_Man_ConstructionWorker_01_Blue_F_OCimport_01 { class EventHandlers; };

    class C_Man_Paramedic_01_F;
    class C_Man_Paramedic_01_F_OCimport_01 : C_Man_Paramedic_01_F { scope = 0; class EventHandlers; };
    class C_Man_Paramedic_01_F_OCimport_02 : C_Man_Paramedic_01_F_OCimport_01 { class EventHandlers; };

    class C_Man_UtilityWorker_01_F;
    class C_Man_UtilityWorker_01_F_OCimport_01 : C_Man_UtilityWorker_01_F { scope = 0; class EventHandlers; };
    class C_Man_UtilityWorker_01_F_OCimport_02 : C_Man_UtilityWorker_01_F_OCimport_01 { class EventHandlers; };

    class C_Man_Fisherman_01_F;
    class C_Man_Fisherman_01_F_OCimport_01 : C_Man_Fisherman_01_F { scope = 0; class EventHandlers; };
    class C_Man_Fisherman_01_F_OCimport_02 : C_Man_Fisherman_01_F_OCimport_01 { class EventHandlers; };

    class C_Man_Messenger_01_F;
    class C_Man_Messenger_01_F_OCimport_01 : C_Man_Messenger_01_F { scope = 0; class EventHandlers; };
    class C_Man_Messenger_01_F_OCimport_02 : C_Man_Messenger_01_F_OCimport_01 { class EventHandlers; };

    class C_Man_formal_2_F;
    class C_Man_formal_2_F_OCimport_01 : C_Man_formal_2_F { scope = 0; class EventHandlers; };
    class C_Man_formal_2_F_OCimport_02 : C_Man_formal_2_F_OCimport_01 { class EventHandlers; };

    class C_Boat_Civil_01_F;
    class C_Boat_Civil_01_F_OCimport_01 : C_Boat_Civil_01_F { scope = 0; class EventHandlers; };
    class C_Boat_Civil_01_F_OCimport_02 : C_Boat_Civil_01_F_OCimport_01 { scope = 0; class EventHandlers; };

    class OPTRE_forklift;
    class OPTRE_forklift_OCimport_01 : OPTRE_forklift { scope = 0; class EventHandlers; };
    class OPTRE_forklift_OCimport_02 : OPTRE_forklift_OCimport_01 { scope = 0; class EventHandlers; };

    class OPTRE_Genet;
    class OPTRE_Genet_OCimport_01 : OPTRE_Genet { scope = 0; class EventHandlers; };
    class OPTRE_Genet_OCimport_02 : OPTRE_Genet_OCimport_01 { scope = 0; class EventHandlers; };

    class OPTRE_M12_CIV;
    class OPTRE_M12_CIV_OCimport_01 : OPTRE_M12_CIV { scope = 0; class EventHandlers; class Turrets; };
    class OPTRE_M12_CIV_OCimport_02 : OPTRE_M12_CIV_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class CargoGunner_1;
            class CargoTurret_02;
            class CargoTurret_03;
        };
    };

    class OPTRE_M12_CIV2;
    class OPTRE_M12_CIV2_OCimport_01 : OPTRE_M12_CIV2 { scope = 0; class EventHandlers; class Turrets; };
    class OPTRE_M12_CIV2_OCimport_02 : OPTRE_M12_CIV2_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class CargoGunner_1;
            class CargoTurret_02;
            class CargoTurret_03;
        };
    };

    class C_Heli_Light_01_civil_F;
    class C_Heli_Light_01_civil_F_OCimport_01 : C_Heli_Light_01_civil_F { scope = 0; class EventHandlers; class Turrets; };
    class C_Heli_Light_01_civil_F_OCimport_02 : C_Heli_Light_01_civil_F_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class CopilotTurret;
        };
    };

    class C_Plane_Civil_01_F;
    class C_Plane_Civil_01_F_OCimport_01 : C_Plane_Civil_01_F { scope = 0; class EventHandlers; class Turrets; };
    class C_Plane_Civil_01_F_OCimport_02 : C_Plane_Civil_01_F_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class MainTurret;
        };
    };

    class C_Man_casual_4_v2_F;
    class C_Man_casual_4_v2_F_OCimport_01 : C_Man_casual_4_v2_F { scope = 0; class EventHandlers; };
    class C_Man_casual_4_v2_F_OCimport_02 : C_Man_casual_4_v2_F_OCimport_01 { class EventHandlers; };

    class C_Man_casual_8_F;
    class C_Man_casual_8_F_OCimport_01 : C_Man_casual_8_F { scope = 0; class EventHandlers; };
    class C_Man_casual_8_F_OCimport_02 : C_Man_casual_8_F_OCimport_01 { class EventHandlers; };


    class O_ColCiv_Civilian_ALiVE_OPTRE_01 : C_man_1_OCimport_02 {
        author = "Capt. Houlston, L";
        scope = 2;
        scopeCurator = 2;
        displayName = "Civilian [ALiVE]";
        side = 3;
        faction = "C_ColCiv_OPTRE";

        identityTypes[] = {"Head_Greek","LanguageGRE_F","G_CIVIL_male"};

        uniformClass = "U_C_Poloshirt_stripped";

        linkedItems[] = {"H_Hat_grey","ItemMap","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"H_Hat_grey","ItemMap","ItemCompass","ItemWatch"};

        weapons[] = {};
        respawnWeapons[] = {};

        magazines[] = {};
        respawnMagazines[] = {};

        ALiVE_orbatCreator_loadout[] = {{},{},{},{"U_C_Poloshirt_stripped",{}},{},{},"H_Hat_grey","",{},{"ItemMap","","","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_ColCiv_Civilian_2ALiVE_OPTRE_01 : C_man_1_1_F_OCimport_02 {
        author = "Capt. Houlston, L";
        scope = 2;
        scopeCurator = 2;
        displayName = "Civilian 2 [ALiVE]";
        side = 3;
        faction = "C_ColCiv_OPTRE";

        identityTypes[] = {"Head_Greek","LanguageGRE_F","G_CIVIL_male"};

        uniformClass = "U_C_Commoner1_1";

        linkedItems[] = {"H_Beret_blk","ItemMap","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"H_Beret_blk","ItemMap","ItemCompass","ItemWatch"};

        weapons[] = {};
        respawnWeapons[] = {};

        magazines[] = {};
        respawnMagazines[] = {};

        ALiVE_orbatCreator_loadout[] = {{},{},{},{"U_C_Commoner1_1",{}},{},{},"H_Beret_blk","",{},{"ItemMap","","","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_ColCiv_Civilian_3ALiVE_OPTRE_01 : C_man_polo_3_F_OCimport_02 {
        author = "Capt. Houlston, L";
        scope = 2;
        scopeCurator = 2;
        displayName = "Civilian 3 [ALiVE]";
        side = 3;
        faction = "C_ColCiv_OPTRE";

        identityTypes[] = {"Head_Greek","LanguageGRE_F","G_CIVIL_male"};

        uniformClass = "U_C_Poloshirt_stripped";

        linkedItems[] = {"H_Bandanna_surfer","ItemMap","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"H_Bandanna_surfer","ItemMap","ItemCompass","ItemWatch"};

        weapons[] = {};
        respawnWeapons[] = {};

        magazines[] = {};
        respawnMagazines[] = {};

        ALiVE_orbatCreator_loadout[] = {{},{},{},{"U_C_Poloshirt_stripped",{}},{},{},"H_Bandanna_surfer","",{},{"ItemMap","","","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_ColCiv_Civilian_Pilot_ALiVE_OPTRE_01 : C_man_pilot_F_OCimport_02 {
        author = "Capt. Houlston, L";
        scope = 2;
        scopeCurator = 2;
        displayName = "Civilian Pilot [ALiVE]";
        side = 3;
        faction = "C_ColCiv_OPTRE";

        identityTypes[] = {"Head_Greek","LanguageGRE_F","G_CIVIL_male"};

        uniformClass = "U_C_WorkerCoveralls";

        linkedItems[] = {"ItemMap","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"ItemMap","ItemCompass","ItemWatch"};

        weapons[] = {};
        respawnWeapons[] = {};

        magazines[] = {};
        respawnMagazines[] = {};

        backpack = "B_Parachute";

        ALiVE_orbatCreator_loadout[] = {{},{},{},{"U_C_WorkerCoveralls",{}},{},{"B_Parachute",{}},"","G_Sport_BlackWhite",{},{"ItemMap","","","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_ColCiv_Civilian_Journalist_ALiVE_OPTRE_01 : C_journalist_F_OCimport_02 {
        author = "Capt. Houlston, L";
        scope = 2;
        scopeCurator = 2;
        displayName = "Civilian Journalist [ALiVE]";
        side = 3;
        faction = "C_ColCiv_OPTRE";

        identityTypes[] = {"Head_Greek","LanguageGRE_F","G_CIVIL_male"};

        uniformClass = "U_C_Journalist";

        linkedItems[] = {"V_Press_F","H_Cap_press","ItemMap","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"V_Press_F","H_Cap_press","ItemMap","ItemCompass","ItemWatch"};

        weapons[] = {};
        respawnWeapons[] = {};

        magazines[] = {};
        respawnMagazines[] = {};

        ALiVE_orbatCreator_loadout[] = {{},{},{},{"U_C_Journalist",{}},{"V_Press_F",{}},{},"H_Cap_press","",{},{"ItemMap","","","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_ColCiv_Civilian_Construction_ALiVE_OPTRE_01 : C_Man_ConstructionWorker_01_Blue_F_OCimport_02 {
        author = "Capt. Houlston, L";
        scope = 2;
        scopeCurator = 2;
        displayName = "Civilian Construction [ALiVE]";
        side = 3;
        faction = "C_ColCiv_OPTRE";

        identityTypes[] = {"Head_Euro","G_CIVIL_constructionworker"};

        uniformClass = "U_C_ConstructionCoverall_Blue_F";

        linkedItems[] = {"H_Construction_headset_red_F","ItemMap","ItemRadio","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"H_Construction_headset_red_F","ItemMap","ItemRadio","ItemCompass","ItemWatch"};

        weapons[] = {};
        respawnWeapons[] = {};

        magazines[] = {};
        respawnMagazines[] = {};

        ALiVE_orbatCreator_loadout[] = {{},{},{},{"U_C_ConstructionCoverall_Blue_F",{{"FirstAidKit",1}}},{},{},"H_Construction_headset_red_F","G_Respirator_yellow_F",{},{"ItemMap","","ItemRadio","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_ColCiv_Paramedic_ALiVE_OPTRE_01 : C_Man_Paramedic_01_F_OCimport_02 {
        author = "Capt. Houlston, L";
        scope = 2;
        scopeCurator = 2;
        displayName = "Paramedic [ALiVE]";
        side = 3;
        faction = "C_ColCiv_OPTRE";

        identityTypes[] = {"Head_Euro","G_CIVIL_Paramedic"};

        uniformClass = "U_C_Paramedic_01_F";

        linkedItems[] = {"ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch"};

        weapons[] = {};
        respawnWeapons[] = {};

        magazines[] = {};
        respawnMagazines[] = {};

        backpack = "B_Messenger_Gray_Medical_F";

        ALiVE_orbatCreator_loadout[] = {{},{},{},{"U_C_Paramedic_01_F",{{"FirstAidKit",3}}},{},{"B_Messenger_Gray_Medical_F",{{"Medikit",1},{"FirstAidKit",7}}},"","G_Respirator_white_F",{},{"ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_ColCiv_Civilian_Utilities_ALiVE_OPTRE_01 : C_Man_UtilityWorker_01_F_OCimport_02 {
        author = "Capt. Houlston, L";
        scope = 2;
        scopeCurator = 2;
        displayName = "Civilian Utilities [ALiVE]";
        side = 3;
        faction = "C_ColCiv_OPTRE";

        identityTypes[] = {"Head_Euro","G_CIVIL_man"};

        uniformClass = "U_C_ConstructionCoverall_Blue_F";

        linkedItems[] = {"V_Safety_yellow_F","H_Bandanna_sgg","ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"V_Safety_yellow_F","H_Bandanna_sgg","ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch"};

        weapons[] = {};
        respawnWeapons[] = {};

        magazines[] = {};
        respawnMagazines[] = {};

        backpack = "B_LegStrapBag_black_repair_F";

        ALiVE_orbatCreator_loadout[] = {{},{},{},{"U_C_ConstructionCoverall_Blue_F",{{"FirstAidKit",2}}},{"V_Safety_yellow_F",{}},{"B_LegStrapBag_black_repair_F",{{"ToolKit",1}}},"H_Bandanna_sgg","G_Shades_Blue",{},{"ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_ColCiv_Civilian_Fisherman_ALiVE_OPTRE_01 : C_Man_Fisherman_01_F_OCimport_02 {
        author = "Capt. Houlston, L";
        scope = 2;
        scopeCurator = 2;
        displayName = "Civilian Fisherman [ALiVE]";
        side = 3;
        faction = "C_ColCiv_OPTRE";

        identityTypes[] = {"Head_Euro","G_CIVIL_man"};

        uniformClass = "U_C_Poloshirt_blue";

        linkedItems[] = {"V_Pocketed_coyote_F","H_Booniehat_tan","ItemMap","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"V_Pocketed_coyote_F","H_Booniehat_tan","ItemMap","ItemCompass","ItemWatch"};

        weapons[] = {};
        respawnWeapons[] = {};

        magazines[] = {};
        respawnMagazines[] = {};

        ALiVE_orbatCreator_loadout[] = {{},{},{},{"U_C_Poloshirt_blue",{}},{"V_Pocketed_coyote_F",{}},{},"H_Booniehat_tan","G_Spectacles",{},{"ItemMap","","","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_ColCiv_Messenger_ALiVE_OPTRE_01 : C_Man_Messenger_01_F_OCimport_02 {
        author = "Capt. Houlston, L";
        scope = 2;
        scopeCurator = 2;
        displayName = "Messenger [ALiVE]";
        side = 3;
        faction = "C_ColCiv_OPTRE";

        identityTypes[] = {"Head_Euro","G_CIVIL_man"};

        uniformClass = "U_C_Poor_1";

        linkedItems[] = {"V_LegStrapBag_coyote_F","H_Bandanna_blu","ItemMap","ItemGPS","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"V_LegStrapBag_coyote_F","H_Bandanna_blu","ItemMap","ItemGPS","ItemCompass","ItemWatch"};

        weapons[] = {};
        respawnWeapons[] = {};

        magazines[] = {};
        respawnMagazines[] = {};

        backpack = "B_Messenger_Coyote_F";

        ALiVE_orbatCreator_loadout[] = {{},{},{},{"U_C_Poor_1",{}},{"V_LegStrapBag_coyote_F",{}},{"B_Messenger_Coyote_F",{}},"H_Bandanna_blu","",{},{"ItemMap","ItemGPS","","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class C_ColCiv_Civilian_Formal_ALiVE_OPTRE_01 : C_Man_formal_2_F_OCimport_02 {
        author = "Capt. Houlston, L";
        scope = 2;
        scopeCurator = 2;
        displayName = "Civilian Formal [ALiVE]";
        side = 3;
        faction = "C_ColCiv_OPTRE";

        identityTypes[] = {"Head_Greek","LanguageGRE_F","G_CIVIL_male"};

        uniformClass = "U_C_FormalSuit_01_gray_F";

        linkedItems[] = {"ItemMap","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"ItemMap","ItemCompass","ItemWatch"};

        weapons[] = {};
        respawnWeapons[] = {};

        magazines[] = {};
        respawnMagazines[] = {};

        ALiVE_orbatCreator_loadout[] = {{},{},{},{"U_C_FormalSuit_01_gray_F",{}},{},{},"","",{},{"ItemMap","","","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class C_ColCiv_Motorboat_ALiVE_OPTRE_01 : C_Boat_Civil_01_F_OCimport_02 {
        author = "Capt. Houlston, L";
        scope = 2;
        scopeCurator = 2;
        displayName = "Motorboat [ALiVE]";
        side = 3;
        faction = "C_ColCiv_OPTRE";
        crew = "C_man_1";


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class C_ColCiv_S2_Cargo_Transporter_ALiVE_OPTRE_01 : OPTRE_forklift_OCimport_02 {
        author = "Capt. Houlston, L";
        scope = 2;
        scopeCurator = 2;
        displayName = "S-2 Cargo Transporter [ALiVE]";
        side = 3;
        faction = "C_ColCiv_OPTRE";
        crew = "O_ColCiv_Civilian_Utilities_ALiVE_OPTRE_01";


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class C_ColCiv_HuCiv_Genet_ALiVE_OPTRE_01 : OPTRE_Genet_OCimport_02 {
        author = "Capt. Houlston, L";
        scope = 2;
        scopeCurator = 2;
        displayName = "HuCiv Genet [ALiVE]";
        side = 3;
        faction = "C_ColCiv_OPTRE";
        crew = "O_ColCiv_Civilian_ALiVE_OPTRE_01";


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class C_ColCiv_AMG_Hog_ALiVE_OPTRE_01 : OPTRE_M12_CIV_OCimport_02 {
        author = "Capt. Houlston, L";
        scope = 2;
        scopeCurator = 2;
        displayName = "AMG Hog [ALiVE]";
        side = 3;
        faction = "C_ColCiv_OPTRE";
        crew = "C_man_1";

        class Turrets : Turrets {
            class CargoGunner_1 : CargoGunner_1 { gunnerType = ""; };
            class CargoTurret_02 : CargoTurret_02 { gunnerType = ""; };
            class CargoTurret_03 : CargoTurret_03 { gunnerType = ""; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class C_ColCiv_Racing_Hog_ALiVE_OPTRE_01 : OPTRE_M12_CIV2_OCimport_02 {
        author = "Capt. Houlston, L";
        scope = 2;
        scopeCurator = 2;
        displayName = "Racing Hog [ALiVE]";
        side = 3;
        faction = "C_ColCiv_OPTRE";
        crew = "C_man_1";

        class Turrets : Turrets {
            class CargoGunner_1 : CargoGunner_1 { gunnerType = ""; };
            class CargoTurret_02 : CargoTurret_02 { gunnerType = ""; };
            class CargoTurret_03 : CargoTurret_03 { gunnerType = ""; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class C_ColCiv_MD_500_ALiVE_OPTRE_01 : C_Heli_Light_01_civil_F_OCimport_02 {
        author = "Capt. Houlston, L";
        scope = 2;
        scopeCurator = 2;
        displayName = "MD 500 [ALiVE]";
        side = 3;
        faction = "C_ColCiv_OPTRE";
        crew = "O_ColCiv_Civilian_Pilot_ALiVE_OPTRE_01";

        class Turrets : Turrets {
            class CopilotTurret : CopilotTurret { gunnerType = "O_ColCiv_Civilian_Pilot_ALiVE_OPTRE_01"; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class C_ColCiv_Cessna_TTx_ALiVE_OPTRE_01 : C_Plane_Civil_01_F_OCimport_02 {
        author = "Capt. Houlston, L";
        scope = 2;
        scopeCurator = 2;
        displayName = "Cessna TTx [ALiVE]";
        side = 3;
        faction = "C_ColCiv_OPTRE";
        crew = "O_ColCiv_Civilian_Pilot_ALiVE_OPTRE_01";

        class Turrets : Turrets {
            class MainTurret : MainTurret { gunnerType = "O_ColCiv_Civilian_Pilot_ALiVE_OPTRE_01"; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class C_ColCiv_Civilian_4ALiVE_OPTRE_01 : C_Man_casual_4_v2_F_OCimport_02 {
        author = "Capt. Houlston, L";
        scope = 2;
        scopeCurator = 2;
        displayName = "Civilian 4 [ALiVE]";
        side = 3;
        faction = "C_ColCiv_OPTRE";

        identityTypes[] = {"Head_Greek","LanguageGRE_F","G_CIVIL_male"};

        uniformClass = "U_C_ArtTShirt_01_v1_F";

        linkedItems[] = {"ItemMap","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"ItemMap","ItemCompass","ItemWatch"};

        weapons[] = {};
        respawnWeapons[] = {};

        magazines[] = {};
        respawnMagazines[] = {};

        backpack = "B_CivilianBackpack_01_Sport_Blue_F";

        ALiVE_orbatCreator_loadout[] = {{},{},{},{"U_C_ArtTShirt_01_v1_F",{}},{},{"B_CivilianBackpack_01_Sport_Blue_F",{}},"","",{},{"ItemMap","","","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class C_ColCiv_Civilian_5ALiVE_OPTRE_01 : C_Man_casual_8_F_OCimport_02 {
        author = "Capt. Houlston, L";
        scope = 2;
        scopeCurator = 2;
        displayName = "Civilian 5 [ALiVE]";
        side = 3;
        faction = "C_ColCiv_OPTRE";

        identityTypes[] = {"Head_Greek","LanguageGRE_F","G_CIVIL_male"};

        uniformClass = "U_C_ArtTShirt_01_v5_F";

        linkedItems[] = {"ItemMap","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"ItemMap","ItemCompass","ItemWatch"};

        weapons[] = {};
        respawnWeapons[] = {};

        magazines[] = {};
        respawnMagazines[] = {};

        ALiVE_orbatCreator_loadout[] = {{},{},{},{"U_C_ArtTShirt_01_v5_F",{}},{},{},"","",{},{"ItemMap","","","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

};