//////////////////////////////////////////////////////////////////////////////////
// Config Automatically Generated by ALiVE ORBAT Creator
// Generated with Arma 3 version 206.148221 on Stable branch
// Generated with ALiVE version 1.15.0.2110111
//////////////////////////////////////////////////////////////////////////////////

class CfgFactionClasses {
    class O_ColIns_Sneaky {
        displayName = "Stealth AI";
        side = 0;
        flag = "\OPTRE_Core\Data\flag_Ins_ca.paa";
        icon = "\OPTRE_Core\Data\flag_Ins_ca.paa";
        priority = 0;
    };
};

class CfgGroups {
    class EAST {

        class O_ColIns_Sneaky {
            name = "Stealth AI";

            class Infantry {
                name = "Infantry";

                class o_colins_infantry_patrol_sneaky {
                    name = "Patrol";
                    side = 0;
                    faction = "O_ColIns_Sneaky";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_ColIns_Rifleman_URF_Sneaky_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_ColIns_Marksman_URF_Sneaky_01";
                    };
                };

                class o_colins_infantry_fireteam_sneaky {
                    name = "Fireteam";
                    side = 0;
                    faction = "O_ColIns_Sneaky";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_ColIns_Squad_Lead_URF_Sneaky_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_ColIns_Rifleman_URF_Sneaky_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_ColIns_Autorifleman_URF_Sneaky_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_ColIns_Marksman_URF_Sneaky_01";
                    };
                };

            };

            class SpecOps {
                name = "Special Forces";

            };

            class Motorized {
                name = "Motorized Infantry";

            };

            class Motorized_MTP {
                name = "Motorized Infantry (MTP)";

            };

            class Support {
                name = "Support Infantry";

            };

            class Mechanized {
                name = "Mechanized Infantry";

            };

            class Armored {
                name = "Armor";

            };

            class Artillery {
                name = "Artillery";

            };

            class Naval {
                name = "Naval";

            };

            class Air {
                name = "Air";

            };


        };

    };
};


class CBA_Extended_EventHandlers_base;

class CfgVehicles {

    class O_soldier_STEALTH;
    class O_soldier_STEALTH_OCimport_01 : O_soldier_STEALTH { scope = 0; class EventHandlers; };
    class O_soldier_STEALTH_OCimport_02 : O_soldier_STEALTH_OCimport_01 { class EventHandlers; };


    class O_ColIns_Rifleman_URF_Sneaky_01 : O_soldier_STEALTH_OCimport_02 {
        author = "Capt. Houlston, L";
        scope = 2;
        scopeCurator = 2;
        displayName = "Rifleman [URF]";
        side = 0;
        faction = "O_ColIns_Sneaky";

        identityTypes[] = {"Head_NATO","LanguageENG_F","G_NATO_default"};

        uniformClass = "LM_OPCAN_URA_Uni";

        linkedItems[] = {"LM_OPCAN_MTMV_VEST","LM_OPCAN_ACH43","ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"LM_OPCAN_MTMV_VEST","LM_OPCAN_ACH43","ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch"};

        weapons[] = {"OPTRE_MA5C","OPTRE_Binoculars"};
        respawnWeapons[] = {"OPTRE_MA5C","OPTRE_Binoculars"};

        magazines[] = {"OPTRE_32Rnd_762x51_Mag","OPTRE_32Rnd_762x51_Mag"};
        respawnMagazines[] = {"OPTRE_32Rnd_762x51_Mag","OPTRE_32Rnd_762x51_Mag"};

        ALiVE_orbatCreator_loadout[] = {{"OPTRE_MA5C","","acc_pointer_IR","OPTRE_M393_EOTECH",{"OPTRE_32Rnd_762x51_Mag",32},{},""},{},{},{"LM_OPCAN_URA_Uni",{{"ACE_tourniquet",2},{"ACE_splint",2},{"ACE_elasticBandage",10},{"ACE_packingBandage",10},{"ACE_EarPlugs",1},{"Chemlight_red",1,1}}},{"LM_OPCAN_MTMV_VEST",{{"ACE_CableTie",2},{"ACE_Flashlight_XL50",1},{"ACE_morphine",1},{"ACE_epinephrine",2},{"ACE_personalAidKit",1},{"MiniGrenade",2,1},{"SmokeShell",4,1},{"OPTRE_32Rnd_762x51_Mag",8,32}}},{},"LM_OPCAN_ACH43","LM_OPCAN_Shemagh",{"OPTRE_Binoculars","","","",{},{},""},{"ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_ColIns_Autorifleman_URF_Sneaky_01 : O_soldier_STEALTH_OCimport_02 {
        author = "Capt. Houlston, L";
        scope = 2;
        scopeCurator = 2;
        displayName = "Autorifleman [URF]";
        side = 0;
        faction = "O_ColIns_Sneaky";

        identityTypes[] = {"Head_NATO","LanguageENG_F","G_NATO_default"};

        uniformClass = "LM_OPCAN_URA_Uni";

        linkedItems[] = {"LM_OPCAN_MTMV_VEST","LM_OPCAN_ACH43","ItemMap","ItemRadio","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"LM_OPCAN_MTMV_VEST","LM_OPCAN_ACH43","ItemMap","ItemRadio","ItemCompass","ItemWatch"};

        weapons[] = {"OPTRE_M73","OPTRE_M6G"};
        respawnWeapons[] = {"OPTRE_M73","OPTRE_M6G"};

        magazines[] = {"OPTRE_200Rnd_95x40_Box","OPTRE_8Rnd_127x40_Mag","OPTRE_200Rnd_95x40_Box","OPTRE_8Rnd_127x40_Mag"};
        respawnMagazines[] = {"OPTRE_200Rnd_95x40_Box","OPTRE_8Rnd_127x40_Mag","OPTRE_200Rnd_95x40_Box","OPTRE_8Rnd_127x40_Mag"};

        backpack = "OPTRE_UNSC_Rucksack_Heavy";

        ALiVE_orbatCreator_loadout[] = {{"OPTRE_M73","","","OPTRE_M73_SmartLink",{"OPTRE_200Rnd_95x40_Box",200},{},"bipod_01_F_blk"},{},{"OPTRE_M6G","","OPTRE_M6G_Flashlight","OPTRE_M6G_Scope",{"OPTRE_8Rnd_127x40_Mag",8},{},""},{"LM_OPCAN_URA_Uni",{{"FirstAidKit",1},{"ACE_EarPlugs",1},{"OPTRE_8Rnd_127x40_Mag",2,8},{"Chemlight_green",2,1}}},{"LM_OPCAN_MTMV_VEST",{{"HandGrenade",2,1},{"OPTRE_100Rnd_95x40_Box",2,100}}},{"OPTRE_UNSC_Rucksack_Heavy",{{"OPTRE_100Rnd_95x40_Box",2,100}}},"LM_OPCAN_ACH43","LM_OPCAN_UP_Shemagh",{},{"ItemMap","","ItemRadio","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_ColIns_Officer_URF_Sneaky_01 : O_soldier_STEALTH_OCimport_02 {
        author = "Capt. Houlston, L";
        scope = 2;
        scopeCurator = 2;
        displayName = "Officer [URF]";
        side = 0;
        faction = "O_ColIns_Sneaky";

        identityTypes[] = {"Head_NATO","LanguageENG_F","G_NATO_default"};

        uniformClass = "LM_OPCAN_URA_Uni";

        linkedItems[] = {"LM_OPCAN_MTMV_VEST","H_Beret_blk","ItemMap","ItemRadio","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"LM_OPCAN_MTMV_VEST","H_Beret_blk","ItemMap","ItemRadio","ItemCompass","ItemWatch"};

        weapons[] = {"OPTRE_MA32","OPTRE_M6G"};
        respawnWeapons[] = {"OPTRE_MA32","OPTRE_M6G"};

        magazines[] = {"OPTRE_32Rnd_762x51_Mag","OPTRE_8Rnd_127x40_Mag","OPTRE_32Rnd_762x51_Mag","OPTRE_8Rnd_127x40_Mag"};
        respawnMagazines[] = {"OPTRE_32Rnd_762x51_Mag","OPTRE_8Rnd_127x40_Mag","OPTRE_32Rnd_762x51_Mag","OPTRE_8Rnd_127x40_Mag"};

        ALiVE_orbatCreator_loadout[] = {{"OPTRE_MA32","","","",{"OPTRE_32Rnd_762x51_Mag",32},{},""},{},{"OPTRE_M6G","","OPTRE_M6G_Flashlight","OPTRE_M6G_Scope",{"OPTRE_8Rnd_127x40_Mag",8},{},""},{"LM_OPCAN_URA_Uni",{{"FirstAidKit",1},{"ACE_EarPlugs",1},{"OPTRE_32Rnd_762x51_Mag",2,32},{"Chemlight_green",2,1}}},{"LM_OPCAN_MTMV_VEST",{{"OPTRE_32Rnd_762x51_Mag",7,32},{"OPTRE_8Rnd_127x40_Mag",2,8},{"HandGrenade",2,1}}},{},"H_Beret_blk","LM_OPCAN_Shemagh",{},{"ItemMap","","ItemRadio","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_ColIns_Marksman_URF_Sneaky_01 : O_soldier_STEALTH_OCimport_02 {
        author = "Capt. Houlston, L";
        scope = 2;
        scopeCurator = 2;
        displayName = "Marksman [URF]";
        side = 0;
        faction = "O_ColIns_Sneaky";

        identityTypes[] = {"Head_NATO","LanguageENG_F","G_NATO_default"};

        uniformClass = "LM_OPCAN_URA_Uni";

        linkedItems[] = {"LM_OPCAN_MTMV_VEST","LM_OPCAN_ACH43","ItemMap","ItemRadio","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"LM_OPCAN_MTMV_VEST","LM_OPCAN_ACH43","ItemMap","ItemRadio","ItemCompass","ItemWatch"};

        weapons[] = {"OPTRE_M295_BMR","OPTRE_M6G"};
        respawnWeapons[] = {"OPTRE_M295_BMR","OPTRE_M6G"};

        magazines[] = {"OPTRE_15Rnd_762x51_Mag","OPTRE_8Rnd_127x40_Mag","OPTRE_15Rnd_762x51_Mag","OPTRE_8Rnd_127x40_Mag"};
        respawnMagazines[] = {"OPTRE_15Rnd_762x51_Mag","OPTRE_8Rnd_127x40_Mag","OPTRE_15Rnd_762x51_Mag","OPTRE_8Rnd_127x40_Mag"};

        ALiVE_orbatCreator_loadout[] = {{"OPTRE_M295_BMR","","","",{"OPTRE_15Rnd_762x51_Mag",15},{},""},{},{"OPTRE_M6G","","","",{"OPTRE_8Rnd_127x40_Mag",8},{},""},{"LM_OPCAN_URA_Uni",{{"FirstAidKit",1},{"ACE_EarPlugs",1},{"OPTRE_15Rnd_762x51_Mag",2,15},{"Chemlight_green",2,1}}},{"LM_OPCAN_MTMV_VEST",{{"OPTRE_15Rnd_762x51_Mag",7,15},{"OPTRE_8Rnd_127x40_Mag",2,8}}},{},"LM_OPCAN_ACH43","LM_OPCAN_UP_Shemagh",{},{"ItemMap","","ItemRadio","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_ColIns_Squad_Lead_URF_Sneaky_01 : O_soldier_STEALTH_OCimport_02 {
        author = "Capt. Houlston, L";
        scope = 2;
        scopeCurator = 2;
        displayName = "Squad Lead [URF]";
        side = 0;
        faction = "O_ColIns_Sneaky";

        identityTypes[] = {"Head_NATO","LanguageENG_F","G_NATO_default"};

        uniformClass = "LM_OPCAN_URA_Uni";

        linkedItems[] = {"LM_OPCAN_MTMV_VEST","LM_OPCAN_ACH43","ItemMap","ItemRadio","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"LM_OPCAN_MTMV_VEST","LM_OPCAN_ACH43","ItemMap","ItemRadio","ItemCompass","ItemWatch"};

        weapons[] = {"OPTRE_MA5CGL","OPTRE_M6G"};
        respawnWeapons[] = {"OPTRE_MA5CGL","OPTRE_M6G"};

        magazines[] = {"OPTRE_32Rnd_762x51_Mag","OPTRE_8Rnd_127x40_Mag","OPTRE_32Rnd_762x51_Mag","OPTRE_8Rnd_127x40_Mag"};
        respawnMagazines[] = {"OPTRE_32Rnd_762x51_Mag","OPTRE_8Rnd_127x40_Mag","OPTRE_32Rnd_762x51_Mag","OPTRE_8Rnd_127x40_Mag"};

        backpack = "OPTRE_UNSC_Rucksack_Heavy";

        ALiVE_orbatCreator_loadout[] = {{"OPTRE_MA5CGL","","","",{"OPTRE_32Rnd_762x51_Mag",32},{},""},{},{"OPTRE_M6G","","OPTRE_M6G_Flashlight","OPTRE_M6G_Scope",{"OPTRE_8Rnd_127x40_Mag",8},{},""},{"LM_OPCAN_URA_Uni",{{"FirstAidKit",1},{"ACE_EarPlugs",1},{"Chemlight_green",2,1},{"OPTRE_32Rnd_762x51_Mag",3,32}}},{"LM_OPCAN_MTMV_VEST",{{"OPTRE_8Rnd_127x40_Mag",2,8},{"HandGrenade",2,1},{"1Rnd_HE_Grenade_shell",3,1}}},{"OPTRE_UNSC_Rucksack_Heavy",{{"1Rnd_HE_Grenade_shell",6,1},{"ACE_40mm_Flare_white",6,1},{"OPTRE_3Rnd_SmokeOrange_Grenade_shell",1,3},{"OPTRE_3Rnd_Smoke_Grenade_shell",4,3},{"OPTRE_1Rnd_SmokeGreen_Grenade_shell",2,1},{"3Rnd_HE_Grenade_shell",2,3},{"OPTRE_32Rnd_762x51_Mag",5,32}}},"LM_OPCAN_ACH43","LM_OPCAN_UP_Shemagh",{},{"ItemMap","","ItemRadio","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

};